### ISSUE TITLE
[beta] webui: increase contrast on default text

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#7254] opened 2019-03-21 13:12 UTC
Currently, the beta webui, by way of bootstrap, declares a color `#212529` that is used for the body, and color `#495057` for e.g. `<textarea>`, and these choices suffer from the problems previously fixed in #4608. Please change all occurrences of these two strings to `#000000`.

**Comment by hennevogel** [comment] 2019-05-13 13:51
![](https://github.trello.services/images/mini-trello-icon.png) [Address Feedback](https://trello.com/c/KybHivS4/1686-address-feedback)

**Comment by coolo** [comment] 2019-05-16 11:43
we lookup up the reason why sites us dark grey instead of black and the reason is actually convincingly enough for me to close the issue:
https://ux.stackexchange.com/questions/23965/is-there-a-problem-with-using-black-text-on-white-backgrounds

Basically the higher constrast might be good for you, but it's bad for more people. Bento used 0x444 which has far less contrast than what the bootstrap community came up with as default.

So I'd vote for closing this issue - having custom/easy themes might be a worthwhile addition later on, but 0x000 is just not a good default for overall mankind :)

**Comment by dmarcoux** [comment] 2019-05-16 12:10
I would also close this issue. I suggest reading this: https://ianstormtaylor.com/design-tip-never-use-black/

**Comment by vpereira** [comment] 2019-05-16 12:21
everyone can have a link  to support their argument, there is a study for example saying the opposite:  https://jov.arvojournals.org/article.aspx?articleid=2132608.  Said that, I don't think we should take a major design decision based in one GH issue. So maybe the issue could stay open, to collect opinions on that but the PR #7576 should be closed for now.

**Comment by eduardoj** [comment] 2019-05-16 13:56
> [...] and these choices suffer from the problems previously fixed in #4608. [...]

I'm not hundred percent sure that we suffer again the problems previously fixed in #4608.

As @coolo said:
 
> Basically the higher constrast might be good for you, but it's bad for more people. Bento used 0x444 which has far less contrast than what the bootstrap community came up with as default.

Maybe some screenshots can help. These show that with the new UI the backgrounds have changed, and therefore the contrast has increased:

Before:

![Screenshot from 2019-05-16 15-35-37 Bootstrap request with text](https://user-images.githubusercontent.com/24919/57858552-901aa600-77f1-11e9-979d-ece371e3c0d0.png)

After:

![Screenshot from 2019-05-16 15-46-04 Bootstrap request with text](https://user-images.githubusercontent.com/24919/57858696-cd7f3380-77f1-11e9-9df8-93342e290345.png)

So my question, @jengelh, will be: do you also have in the new UI the same problems already addressed in Bento? Is this increase of contrast enough?

**Comment by eduardoj** [comment] 2019-07-22 09:58
Closing due of lack of response to the questions made.

**Closed by eduardoj** 2019-07-22 09:58 UTC
Labels: Bootstrap :rocket:, Design, Frontend

**Comment by jengelh** [comment] 2022-09-08 16:23
I don't recall and/or the question was too complicated.
Anyway, the current UI of 2022 has the issue (or has it again).

view-source:https://build.opensuse.org/assets/webui/application-0a0979874cefc574479ab69005ee5999340481ed4ce559866ef730d425a821ef.css

The offending color is #212529 and #495057.

![1](https://user-images.githubusercontent.com/8861948/189174689-fd93ecbe-1dab-4f67-9da0-a2ca4c2d6d74.png)

**Comment by eduardoj** [comment] 2022-09-09 10:19
@jengelh, the current UI uses the color #212529 as the default font color, instead of #000000. If I'm not wrong, the color #000000 is not used for the font in any other place on the website.

This makes the "non-bold" effect of fonts with color #495047 only relative to the default font color #212529. So the issue is only with one color: #495047. This difference is smaller, and not so obvious to notice, as with the original issue between #444 and #000.

Also, the color #495047 is used for the font used inside the textarea, which is temporary content. Once the textarea content is saved, the font color goes back to the default. We could say that the inconsistency of the page design only happens when entering text.

With the above-mentioned reasons, and also taking into account other comments in this same issue, I don't consider that using the current font colors design still suffers from a 'weird design choice to mix that "semi-bold" and "non-bold" text'.

Please correct me if I understood you wrong, or if you wanted to point out a different issue.

**Comment by jengelh** [comment] 2022-09-09 11:34
I don't have a QD-OLED like the cool kids or CRT like the retro kids, so 000000 already is some backlit gray and not black. I am also a user of glasses, and color 212529 can appear as if the glasses need cleaning. Please just use 000000, or provide a way for user accounts to inject custom CSS (e.g. something like [lwn.net has](https://paste.opensuse.org/67362360)).

I recognize that colors induce a "perceived boldness" (I do notice that when comparing white-on-black vs black-on-white xterms with thin fonts), but this ticket is not about boldness.

**Comment by eduardoj** [comment] 2022-09-09 11:57
> Please just use 000000, or provide a way for user accounts to inject custom CSS (e.g. something like [lwn.net has](https://paste.opensuse.org/67362360)).

Let's agree that this belongs to #6311.
