### ISSUE TITLE
incompatible character encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#3550] opened 2017-08-09 10:12 UTC
threw this 2 times
<pre>
incompatible character encodings: UTF-8 and ASCII-8BIT
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59881fb0178744000e940a26)

**Comment by hennevogel** [comment] 2017-08-09 10:12
This happens when rendering emails

**Comment by ChrisBr** [comment] 2017-08-09 13:22
duplicate of https://github.com/openSUSE/open-build-service/issues/3550
(which you created :smile: )

**Closed by ChrisBr** 2017-08-09 13:22 UTC
Labels: Bug, frontend
