### ISSUE TITLE
Wrong parsing of Mentioned issues

### ISSUE THREAD

**Issue by marxin** [openSUSE/open-build-service#12614] opened 2022-05-20 11:39 UTC
ChangeLog entry:
```
- Add uwsgi-ld-noexecstack.patch in order to fix gh#unbit/uwsgi#2436.
```

Is parsed on WEB UI here:
https://build.opensuse.org/request/show/978261

as:

```
Mentioned Issues (2)
[gh#unbit/uwsgi#2436](https://github.com/unbit/uwsgi/issues/2436)
[i#2436](http://openoffice.org/bugzilla/show_bug.cgi?id=2436)
```

**Comment by hennevogel** [comment] 2022-05-20 11:40
Duplicate of #12031

**Closed by hennevogel** 2022-05-20 11:40 UTC
