### ISSUE TITLE
[production][package#rpmlint_log] <status code="400">
  <summary>unknown request: GET:/build/home:CZ-NIC:knot-resolver-latest/&lt;f...

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#7545] opened 2019-05-13 08:22 UTC
package#rpmlint_log threw this 9 times
<pre>
&lt;status code=&quot;400&quot;&gt;
  &lt;summary&gt;unknown request: GET:/build/home:CZ-NIC:knot-resolver-latest/&amp;lt;font+style=&amp;quot;vertical-align:+inherit;&amp;quot;&amp;gt;&amp;lt;font+style=&amp;quot;vertical-align:+inherit;&amp;quot;&amp;gt;Debian_9.0&amp;lt;/font&amp;gt;&amp;lt;/font&amp;gt;/armv7l/knot-resolver/rpmlint.log&lt;/summary&gt;
  &lt;details&gt;400 unknown request: GET:/build/home:CZ-NIC:knot-resolver-latest/&amp;lt;font+style=&amp;quot;vertical-align:+inherit;&amp;quot;&amp;gt;&amp;lt;font+style=&amp;quot;vertical-align:+inherit;&amp;quot;&amp;gt;Debian_9.0&amp;lt;/font&amp;gt;&amp;lt;/font&amp;gt;/armv7l/knot-resolver/rpmlint.log&lt;/details&gt;
&lt;/status&gt;

</pre>
[https://build.opensuse.org/package/rpmlint_log?project=home%3ACZ-NIC%3Aknot-resolver-latest&amp;package=knot-resolver&amp;repository=%3Cfont+style%3D%22vertical-align%3A+inherit%3B%22%3E%3Cfont+style%3D%22vertical-align%3A+inherit%3B%22%3EDebian_9.0%3C%2Ffont%3E%3C%2Ffont%3E&amp;architecture=armv7l](https://build.opensuse.org/package/rpmlint_log?project=home%3ACZ-NIC%3Aknot-resolver-latest&amp;package=knot-resolver&amp;repository=%3Cfont+style%3D%22vertical-align%3A+inherit%3B%22%3E%3Cfont+style%3D%22vertical-align%3A+inherit%3B%22%3EDebian_9.0%3C%2Ffont%3E%3C%2Ffont%3E&amp;architecture=armv7l)"

~[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5cc0c1316f74b0000824ca37)~

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5d96fb1528af88000889d0b9)

**Comment by bgeuken** [comment] 2019-05-13 08:24
Started to occur on 'Apr 24 20:04:01'

**Comment by eduardoj** [comment] 2024-08-26 14:18
I couldn't reproduce the issue by browsing the web UI. It seems that the URL is handcrafted.

I hide the URL in the description. Closing.

**Closed by eduardoj** 2024-08-26 14:18 UTC
Labels: Bug, Frontend
