### ISSUE TITLE
Validation failed: Flags Duplicated flags

### ISSUE THREAD

**Issue by danidoni** [openSUSE/open-build-service#11757] opened 2021-10-20 08:23 UTC
[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/616aa78d84bf46053f6ea5d4)
# Validation failed: Flags Duplicated flags #
### URL ###
[https://build.opensuse.org/flag/home:predivan:nvidia](https://build.opensuse.org/flag/home:predivan:nvidia)"
### Where ###
repositories#change_flag

### Occured ###
Oct 16 10:21am

### Similar ###
0

## Params ##
~~~
{
  &quot;action&quot; =&gt; &quot;change_flag&quot;,
  &quot;command&quot; =&gt; &quot;set-disable&quot;,
  &quot;controller&quot; =&gt; &quot;webui/repositories&quot;,
  &quot;flag&quot; =&gt; &quot;build&quot;,
  &quot;project&quot; =&gt; &quot;home:predivan:nvidia&quot;
}
~~~

## Session ##
~~~
{
  &quot;_csrf_token&quot; =&gt; &quot;6glpBN0m1wtmJUMI2k5A69zdn+sZXq+9F7vXwIbw+rw=&quot;,
  &quot;session_id&quot; =&gt; &quot;12aa227350e167a7fa4f925162a571b5&quot;
}
~~~

## Backtrace ##
~~~
80:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/validations.rb -> **raise_validation_error**
53:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/validations.rb -> **save!**
302:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/transactions.rb -> **block in save!**
354:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/transactions.rb -> **block in with_transaction_returning_status**
318:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb -> **transaction**
350:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/transactions.rb -> **with_transaction_returning_status**
302:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/transactions.rb -> **save!**
48:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/suppressor.rb -> **save!**
709:  app/models/project.rb -> **block in store**
320:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb -> **block in transaction**
319:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/connection_adapters/abstract/transaction.rb -> **block in within_new_transaction**
26:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **block (2 levels) in synchronize**
25:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **handle_interrupt**
25:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **block in synchronize**
21:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **handle_interrupt**
21:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **synchronize**
317:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/connection_adapters/abstract/transaction.rb -> **within_new_transaction**
320:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb -> **transaction**
209:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/transactions.rb -> **transaction**
290:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/transactions.rb -> **transaction**
708:  app/models/project.rb -> **store**
180:  app/controllers/webui/repositories_controller.rb -> **follow_change_flag_command**
159:  app/controllers/webui/repositories_controller.rb -> **change_flag**
6:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal/basic_implicit_render.rb -> **send_action**
228:  /GEM_ROOT/gems/actionpack-6.1.4/lib/abstract_controller/base.rb -> **process_action**
30:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal/rendering.rb -> **process_action**
42:  /GEM_ROOT/gems/actionpack-6.1.4/lib/abstract_controller/callbacks.rb -> **block in process_action**
106:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/callbacks.rb -> **run_callbacks**
41:  /GEM_ROOT/gems/actionpack-6.1.4/lib/abstract_controller/callbacks.rb -> **process_action**
22:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal/rescue.rb -> **process_action**
34:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal/instrumentation.rb -> **block in process_action**
203:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/notifications/instrumenter.rb -> **instrument**
203:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/notifications.rb -> **instrument**
33:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal/instrumentation.rb -> **process_action**
249:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal/params_wrapper.rb -> **process_action**
27:  /GEM_ROOT/gems/activerecord-6.1.4/lib/active_record/railties/controller_runtime.rb -> **process_action**
165:  /GEM_ROOT/gems/actionpack-6.1.4/lib/abstract_controller/base.rb -> **process**
39:  /GEM_ROOT/gems/actionview-6.1.4/lib/action_view/rendering.rb -> **process**
190:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal.rb -> **dispatch**
254:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_controller/metal.rb -> **dispatch**
50:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/routing/route_set.rb -> **dispatch**
33:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/routing/route_set.rb -> **serve**
19:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/routing/mapper.rb -> **block in &lt;class:Constraints&gt;**
49:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/routing/mapper.rb -> **serve**
50:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/journey/router.rb -> **block in serve**
32:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/journey/router.rb -> **each**
32:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/journey/router.rb -> **serve**
842:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/routing/route_set.rb -> **call**
37:  config/initializers/wrap_parameters.rb -> **call**
77:  /GEM_ROOT/gems/flipper-0.22.2/lib/flipper/middleware/memoizer.rb -> **memoized_call**
42:  /GEM_ROOT/gems/flipper-0.22.2/lib/flipper/middleware/memoizer.rb -> **call**
44:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/deflater.rb -> **call**
15:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/etag.rb -> **call**
40:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/conditional_get.rb -> **call**
12:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/head.rb -> **call**
22:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/http/permissions_policy.rb -> **call**
18:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/http/content_security_policy.rb -> **call**
266:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/session/abstract/id.rb -> **context**
260:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/session/abstract/id.rb -> **call**
689:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/cookies.rb -> **call**
27:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/callbacks.rb -> **block in call**
98:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/callbacks.rb -> **run_callbacks**
26:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/callbacks.rb -> **call**
18:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/actionable_exceptions.rb -> **call**
32:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call!**
21:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call**
29:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/debug_exceptions.rb -> **call**
33:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/show_exceptions.rb -> **call**
15:  /GEM_ROOT/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb -> **call_app**
26:  /GEM_ROOT/gems/railties-6.1.4/lib/rails/rack/logger.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/tagged_logging.rb -> **block in tagged**
37:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/tagged_logging.rb -> **tagged**
99:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/tagged_logging.rb -> **tagged**
26:  /GEM_ROOT/gems/railties-6.1.4/lib/rails/rack/logger.rb -> **call**
81:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/remote_ip.rb -> **call**
81:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/remote_ip.rb -> **call**
19:  /GEM_ROOT/gems/request_store-1.5.0/lib/request_store/middleware.rb -> **call**
26:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/request_id.rb -> **call**
24:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/method_override.rb -> **call**
22:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/runtime.rb -> **call**
29:  /GEM_ROOT/gems/activesupport-6.1.4/lib/active_support/cache/strategy/local_cache_middleware.rb -> **call**
14:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/executor.rb -> **call**
18:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/lock.rb -> **call**
110:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/sendfile.rb -> **call**
92:  /GEM_ROOT/gems/actionpack-6.1.4/lib/action_dispatch/middleware/host_authorization.rb -> **call**
539:  /GEM_ROOT/gems/railties-6.1.4/lib/rails/engine.rb -> **call**
207:  /GEM_ROOT/gems/railties-6.1.4/lib/rails/railtie.rb -> **public_send**
207:  /GEM_ROOT/gems/railties-6.1.4/lib/rails/railtie.rb -> **method_missing**
74:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/urlmap.rb -> **block in call**
58:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/urlmap.rb -> **each**
58:  /GEM_ROOT/gems/rack-2.2.3/lib/rack/urlmap.rb -> **call**
107:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.8/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb -> **process_request**
157:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.8/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **accept_and_process_next_request**
110:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.8/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **main_loop**
416:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.8/src/ruby_supportlib/phusion_passenger/request_handler.rb -> **block (3 levels) in start_threads**
113:  /usr/lib64/ruby/gems/2.5.0/gems/passenger-6.0.8/src/ruby_supportlib/phusion_passenger/utils.rb -> **block in create_thread_and_abort_on_exception**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| program_name | Passenger RubyApp: /srv/www/obs/api (production) |
| HTTP_USER_AGENT | Mozilla/5.0 (X11; Linux x86_64; rv:93.0) Gecko/20100101 Firefox/93.0 |

**Comment by eduardoj** [comment] 2021-11-03 16:57
Duplicate of #7893. Closing.

**Closed by eduardoj** 2021-11-03 16:57 UTC
Labels: Bug, Frontend
