### ISSUE TITLE
[WebUI] login failure for non admin users in git master

### ISSUE THREAD

**Issue by mmohring** [openSUSE/open-build-service#5574] opened 2018-08-07 15:37 UTC
# Issue Description
With the current git master changes, you cannot login as a normal "non admin" user anymore. It worked with with git commit 302dd59f0 and doesnt with git commit 2ad3691ac, so anything inbetween borked it.

Expected Result
============
Login as normal non Admin user should still work.

How to Reproduce
===============
1. Deploy OBS snapshot based on git commit 2ad3691ac
2. goto <OBS URL>/session/new
3. If the credentials are of a non Admin user, you get "Authentication failed "
4. If you use a Admin user, it works

Further Information
===============
I guess this has something to do with the fact that Admin Users now get the new WebUI, and normal users dont. So the old WebUI code got borked with some of the recent changes.

Suggestion
===============
It would be great if the user could select if he wants to test the new WebUI or use the old, not based on a fixed decision if he is Admin or not.

**Comment by hennevogel** [comment] 2018-08-07 15:41
@dmarcoux can you have a look at this next?

**Comment by dmarcoux** [comment] 2018-08-07 16:04
@hennevogel I will

**Comment by mmohring** [comment] 2018-08-07 17:43
Hi folks, I have now tried 7f28f1b8c80038e0a9fabd980ffce7ed4369ee29, e.g. the commit to remove Statistic 'model'. This has the same problem than current git master - e.g. cannot login as non Admin user. Some something must have gone wrong there.

**Comment by mmohring** [comment] 2018-08-07 19:57
Hi folks. seems to be more complicated. Can you put this on hold until I figure out what happens here ?

**Comment by mmohring** [comment] 2018-08-07 20:47
To come further, I will try to add a function to change the password of a login by the Admin and will anyway come back what I found.

**Comment by dmarcoux** [comment] 2018-08-08 09:54
@mmohring I tested this locally with the [current master](https://github.com/openSUSE/open-build-service/commit/2ad3691acf04d11cc7d0f13d17f4e0a1c149b31a) and I can login with a non-admin user. I cannot reproduce the issue. I will close the issue. Feel free to open it again if you can reproduce it on the [current master](https://github.com/openSUSE/open-build-service/commit/2ad3691acf04d11cc7d0f13d17f4e0a1c149b31a).

**Closed by dmarcoux** 2018-08-08 09:54 UTC
Labels: Frontend 👻

**Comment by bgeuken** [comment] 2018-08-10 08:43
Turns out that we don't seed the database in our dev docker containers anymore.

@mmohring I suspect you are not using our dev containers, right? How are you deploying these snapshots? / What are they?

**Comment by mmohring** [comment] 2018-08-10 09:28
I prepare a new test system based on openSUSE Leap 15.0 now in a VM, never used the new Leap yet for this and report back. I will use git master 6f0181e2bf08d57f754e8cfe93b4ff7787322703 for this.

**Comment by bgeuken** [comment] 2018-08-10 11:16
Alright. Thanks for the explanation. I am having a look at this

**Comment by mmohring** [comment] 2018-08-12 10:28
I have now installed a fresh copy of the actual git master on OSL 15.0, in a VM. File storage is via NFS, MySQL DB is on a remote DB server, I set `<anonymous>off</anonymous>` and `<registration>deny</registration>` . I do **not configure LDAP**, the users are local OBS users. Then I created 3 users, one with Admin,  one with Staff and one with none of both Roles. Then I opened the front page, logged in with the Admin User and get the new WebUI Frontpage. Logged out and logged in with the User with Role Staff and get the new WebUI dito. Then logged in with the normal user (no Roles Staff or Admin) and I get the old WebUI frontpage. I open a new tab with the URL "/monitor/old". I switch to the tab with the frontpage, logout. Then I reload the tab with URL "/monitor/old" and get an error "The page isn’t redirecting properly". If I now login on the frontpage again, I get logged in but get an error "No anonymous access. Please log in!". If I reload the frontpage, I am still logged in and the error goes away. Maybe this error message made the confusion ? If you have pages which load updates in the background like the monitor page, it can happend in case of logout that you get "No anonymous access. Please log in!" on the frontpage when you dont expect it, even when you re-login.

Anyway, with a fresh install I **could not** reproduce issue #5574 as described in the beginning.

Could you anyway make the use of the new WebUI configurable per user and **not depending** on the user roles as long as the new WebUI is work in progress ?

**Comment by mmohring** [comment] 2018-08-12 10:41
If I open the "/users" page as Admin in a new tab, logout and re-login with a the normal user, and re-load the "/users" Admin page, I get also a "The page isn’t redirecting properly". If I re-load the frontpage now, I get the error "Requires admin privileges" on the frontpage. So there seems to be in general the problem that those error messages which stem from another Browser Tab are displayed on the frontpage if it gets re-loaded.
