### ISSUE TITLE
Files could not be expanded: 400 remote error: /bs/service/26960 not writable for me at /usr/lib/obs/server/bs_service line 115.

### ISSUE THREAD

**Issue by Mailaender** [openSUSE/open-build-service#2281] opened 2016-10-29 12:01 UTC
![image](https://cloud.githubusercontent.com/assets/756669/19829394/3a1c73d4-9de0-11e6-961b-0c93821a15b3.png)

**Comment by bgeuken** [comment] 2016-10-30 16:28
Duplicate of #2280

**Closed by bgeuken** 2016-10-30 16:28 UTC
