### ISSUE TITLE
[production][repositories#index] undefined method `each_with_index' for nil:NilClass

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#6012] opened 2018-10-04 08:34 UTC
repositories#index threw this 1 time
<pre>
undefined method `each_with_index&#39; for nil:NilClass
</pre>
[https://build.opensuse.org/repositories/home:AndreasStieger:branches:filesystems](https://build.opensuse.org/repositories/home:AndreasStieger:branches:filesystems)

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5bb3cc9a90912e00066be12f)

**Comment by saraycp** [comment] 2018-10-17 12:42
It seems to be related to #3642 and this, in turn, to #2200.

**Comment by saraycp** [comment] 2018-10-18 14:43
It is also not possible to reproduce it, the subproject doesn't exist anymore. I close it, please re-open if it happens again.

**Comment by coolo** [comment] 2018-10-18 15:33
http://pastebin.nue.suse.com/20200/src - notice how @andreasstieger changed the repositories the very same second (save_meta in a different rails worker).

I think the problem is that the view accesses @project.repositories while the controller only filled the flags hash for the repositories that existed then.

Hope that makes sense to you - the issue seems to happen every couple of months :)

**Comment by coolo** [comment] 2018-10-18 15:46
I can reproduce it this way: add a repository through the meta tab and after you pressed save, reload in the repositories tab (you better have 2 windows open :)

**Comment by coolo** [comment] 2019-01-10 09:42
note that this problem no longer exists in webui2 due the refactoring @Ana06 and me did. So possibly we can close this as no longer relevant (in the illusion webui2 will be finished soon :)

**Closed** 2019-01-11 11:00 UTC
Labels: Bug :skull:, Frontend 👻
