### ISSUE TITLE
Monitoring Plot loose Timeframe mode on reload

### ISSUE THREAD

**Issue by frispete** [openSUSE/open-build-service#7928] opened 2019-07-17 08:23 UTC
Reproduce:
/monitor: switch to 1 hour; reload page -> plots show 1 day mode, but Timeframe chooser shows 1 hour still.

Expected:
Keep the plots in the selected Timeframe mode.

**Comment by vpereira** [comment] 2019-07-17 13:28
hi @frispete is that a duplicate of https://github.com/openSUSE/open-build-service/issues/4952 ?

**Comment by frispete** [comment] 2019-07-17 14:26
> hi @frispete is that a duplicate of #4952 ?

Yes, sure. Damn, Ff.

Wouldn't `<form autocomplete="off">` fix that for Ff as well?

**Comment by hennevogel** [comment] 2019-07-18 07:12
Duplicate of #4952 

please continue there..

**Closed by hennevogel** 2019-07-18 07:12 UTC
Labels: Frontend
