### ISSUE TITLE
WebUi regression in display of https://build.opensuse.org/user/show/username

### ISSUE THREAD

**Issue by plinnell** [openSUSE/open-build-service#2381] opened 2016-11-28 02:36 UTC
Clicking on the type column has no effect, unlike recently.  This is a regression from prior behavior and is important for factory reviewers, as we want to see "release" type sorted before "submit" types.

**Comment by bgeuken** [comment] 2016-11-28 09:07
I am sorry but I can't reproduce this. Please double check.

**Comment by bgeuken** [comment] 2016-11-30 08:50
Closing for now. Please let us know when this happens again.

**Closed by bgeuken** 2016-11-30 08:50 UTC
