### ISSUE TITLE
Provide a hint for easy copy-and-paste command line on the project's home page

### ISSUE THREAD

**Issue by tomschr** [openSUSE/open-build-service#10179] opened 2020-09-21 09:45 UTC
**Is your feature request related to a problem? Please describe.**
This request is just a usability improvement. Hope there is no similar issue.

Consider the following use case:
When a developer sees a project and would like to work on OBS what does that person do? Probably checkout or branch the project with the `osc` command line tool. However, OBS doesn't provide such "hints".

For example, look at GitHub. Every GitHub project contains a "Code" button which (once clicked) opens a short menu. It gives you a hint about how to clone the project with either SSH or HTTPS. 

We don't have such a hint for OBS.

**Describe the solution you'd like**
Couldn't we have something similar on each project's page for OBS? For example, a project page could look like this:

```
Projects / home:obstux / foo

foo

A short description about the foo package [...]

------
Code:
   Cloning:   osc checkout home:obstux/foo
   Branching: osc branch home:obstux/foo
```

Benefits:

* User-friendly: developer can easy copy and paste the line to the shell and execute it.
* Easy to implement
* What else do I need to say here that you buy it? :wink: 

**Describe alternatives you've considered**
Depending on how much you want to replicate the idea from GitHub, you could consider several alternatives:

* Write out the cloning and branching as shown above.
* "Hide" the options under a "Code" button similar to GitHub.
* Move/group also the "Download Package" link into something like this "Code" button.
* Add this under the sidebar (could be named "Code" or whatever you like).

If you want to go a step further, you could consider linking to the documentation to provide further help. Maybe that implies to improve the documentation too, but that's a topic for another PR. :wink: 

Probably also ask usability experts. It doesn't matter to me where exactly it is located. Thanks!

**Additional context**
See GitHub and the "Code" button.

**Comment by dmarcoux** [comment] 2020-09-21 10:08
Thank you @tomschr for your feedback. It totally makes sense.

**Comment by hennevogel** [comment] 2020-09-22 09:57
duplicate of #63

**Closed by hennevogel** 2020-09-22 09:57 UTC
Labels: Feature, Frontend
