### ISSUE TITLE
webui rejects showing file of a specific revision

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#10298] opened 2020-10-14 10:57 UTC
# Issue Description
The "view file" button of a SR (e.g. https://build.opensuse.org/request/show/841704 ) leads to "File not found".

How to Reproduce
===============
1. Go to https://build.opensuse.org/package/view_file/network:ha-clustering:Factory/libdlm/libdlm.spec?rev=80
4. See error "File not found: libdlm.spec"

**Comment by vpereira** [comment] 2020-10-15 11:31
Hi @jengelh 

The issue is that the file in this revision doesn't exist on the backend. Trying to access the file  https://build.opensuse.org/package/view_file/network:ha-clustering:Factory/libdlm/libdlm.changes?rev=80, gives me 404 on the backend:

```
INFO -- : 20201015T112519 GET src-opensuse:5352/source/network:ha-clustering:Factory/libdlm/libdlm.changes?rev=80 404 0.015370865
```

**Comment by jengelh** [comment] 2020-10-15 12:41
For all I know and care, libdlm.spec is shown in https://build.opensuse.org/package/show/network:ha-clustering:Factory/libdlm . (currently says revision 81, but there's no significant change with regard to 80)

**Comment by jengelh** [comment] 2021-02-04 11:30
The target link for the button is missing a `?expand=1`, says @Vogtinator , and I confirm that would fix it.

**Comment by adrianschroeter** [comment] 2021-02-04 12:39
yes, the diff is show from expanded sources for obvious reasons. So the linked files need also be shown expanded.

Should be an easy fix.

**Comment by dmarcoux** [comment] 2021-02-04 13:09
This issue is a duplicate of #7224 (thanks @eduardoj for pointing this out). I'll handle this. I'm closing this issue, but it will be fixed. Follow progress in the other issue.

**Closed by dmarcoux** 2021-02-04 13:09 UTC
Labels: Bug, Frontend, P2, good first issue
