### ISSUE TITLE
(Github) SCM Integration - follow-up build statuses not being reported to GitHub?

### ISSUE THREAD

**Issue by LebedevRI** [openSUSE/open-build-service#14613] opened 2023-07-06 13:40 UTC
I've performed OBS Workflow integration as outlined in
* https://openbuildservice.org/2021/05/31/scm-integration/
* https://github.com/openSUSE/open-build-service/wiki/Better-SCM-CI-Integration-Testing
* https://github.com/openSUSE/open-build-service/wiki/Better-SCM-CI-Integration-Workflows

for https://github.com/darktable-org/rawspeed and https://github.com/darktable-org/darktable
(https://build.opensuse.org/package/show/graphics:darktable:master/rawspeed and https://build.opensuse.org/package/show/graphics:darktable:master/darktable)

While it works, only the initial `OBS SCM/CI Workflow Integration started` status
is posted for the commit that triggered the workflow.
Even after the OBS builds finish, no new statuses are posted.
Looking at the Workflow Runs for the OBS tokens,
`Reports to the SCM` only ever lists said initial status to be sent.

I was under impression that the statuses of individual builds would be posted as commit statuses.
Is that not how it works? Or is that only for Pull Requests, and not normal pushes?
Or is that only for some specific step, and not `trigger_services`?

**Comment by hennevogel** [comment] 2023-07-06 14:47
yeah you've hit a bug, sorry. 

Duplicate of #13535

**Closed by hennevogel** 2023-07-06 14:47 UTC

**Comment by LebedevRI** [comment] 2023-07-06 14:55
@hennevogel thank you!
That's unfortunate, having those build statuses was 90% of my motivation to migrate to Workflows.

**Comment by hennevogel** [comment] 2023-07-06 15:07
@LebedevRI you are lucky, we are on the brink of fixing this in the next couple of days! :)

**Comment by LebedevRI** [comment] 2023-07-07 21:01
FWIW, i'm really confused by the functionality. It feels like it is missing links to working example repos on github.

I'm now trying with `branch_package`, and *again* not getting any indication that anything is happening:
https://github.com/darktable-org/rawspeed/pull/499
But in this case, and i don't believe it ever branches the repo.
It's not a permissions thing, i can successfully do that manually.
Navigating to the workflow run on OBS shows no artifacts at all...
