### ISSUE TITLE
Build fail. Could not resolve host: github.com

### ISSUE THREAD

**Issue by tankaras** [openSUSE/open-build-service#12569] opened 2022-05-12 05:06 UTC
```
[   37s] Preparing sources...
[   40s]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[   40s]                                  Dload  Upload   Total   Spent    Left  Speed
[   40s]   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: github.com
[   40s] Warning: Problem : timeout. Will retry in 3 seconds. 3 retries left.
[   43s]   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: github.com
[   43s] Warning: Problem : timeout. Will retry in 3 seconds. 2 retries left.
[   43s]   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: github.com
[   43s] Warning: Problem : timeout. Will retry in 3 seconds. 2 retries left.
[   46s]   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: github.com
[   46s] Warning: Problem : timeout. Will retry in 3 seconds. 1 retries left.
```

**Comment by eduardoj** [comment] 2022-05-12 05:19
Duplicate of #751. Closing.

**Closed by eduardoj** 2022-05-12 05:19 UTC
