### ISSUE TITLE
Repo has old packages

### ISSUE THREAD

**Issue by glixx** [openSUSE/open-build-service#7817] opened 2019-06-27 05:13 UTC
Repository has old packages always. After rebuilding old packages do not replace by new ones if they have same file names. At least for Arch Linux, deb.

Workaround: increase rel tag. It changes file name.

**Comment by vpereira** [comment] 2019-07-09 08:06
there is some delay between package build and package publishing, normally related with server load... if you wipe the binaries before rebuild it, does it get published faster?

**Comment by glixx** [comment] 2019-07-09 10:03
Few days is delay?

If to delete binaries, they will be old again.

**Comment by hennevogel** [comment] 2019-07-09 10:54
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support for a specific instance from us. If you have problems with build.opensuse.org please report them to admin@opensuse.org

Thank you for your consideration.

**Comment by adrianschroeter** [comment] 2019-07-09 12:08
this is about the missing release number handling support for debian and archlinux. So it is a feature request.

**Comment by glixx** [comment] 2019-07-09 12:14
Yes. RPM is ok.

**Comment by nickbroon** [comment] 2019-09-24 13:51
Is this a duplicate of #834?

**Comment by hennevogel** [comment] 2019-09-24 14:52
yeah it is, thanks

**Closed by hennevogel** 2019-09-24 14:52 UTC
Labels: Backend 🤖, Feature 💡
