### ISSUE TITLE
[production][project#save_meta] SUSE:SLE-12-SP2:Docker

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#3989] opened 2017-10-11 12:47 UTC
project#save_meta threw this 10 times
<pre>
SUSE:SLE-12-SP2:Docker
</pre>
[https://build.opensuse.org/project/save_meta/Cloud:Platform:Stack-SLE:rootfs](https://build.opensuse.org/project/save_meta/Cloud:Platform:Stack-SLE:rootfs)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59dc6f9b6d66190006450397)

**Comment by mschnitzer** [comment] 2017-10-11 12:54
This error occurred many times during the last 24h. See: https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000

**Comment by ChrisBr** [comment] 2017-10-17 10:57
Could be related to https://github.com/openSUSE/open-build-service/issues/3916
I will have a look into it later!

**Comment by adrianschroeter** [comment] 2017-10-23 07:40
Duplicate of https://github.com/openSUSE/open-build-service/issues/4051

**Closed by adrianschroeter** 2017-10-23 07:40 UTC
