### ISSUE TITLE
[production][package#binary] <status code="400">
  <summary>unknown request: GET:/build/home:olav-st/xUbuntu_16.04https:/i.img...

### ISSUE THREAD

**Issue by evanrolfe** [openSUSE/open-build-service#4405] opened 2018-01-26 09:37 UTC
package#binary threw this 0 times
<pre>
&lt;status code=&quot;400&quot;&gt;
  &lt;summary&gt;unknown request: GET:/build/home:olav-st/xUbuntu_16.04https:/i.imgur.com/bBwRy9D.png/x86_64/pythonqt-qt5/libpythonqt-qt5_3.0-1_amd64.deb&lt;/summary&gt;
  &lt;details&gt;400 unknown request: GET:/build/home:olav-st/xUbuntu_16.04https:/i.imgur.com/bBwRy9D.png/x86_64/pythonqt-qt5/libpythonqt-qt5_3.0-1_amd64.deb&lt;/details&gt;
&lt;/status&gt;

</pre>
[https://build.opensuse.org/package/binary/home:olav-st/pythonqt-qt5?arch=x86_64&amp;filename=libpythonqt-qt5_3.0-1_amd64.deb&amp;repository=xUbuntu_16.04https%3A%2F%2Fi.imgur.com%2FbBwRy9D.png](https://build.opensuse.org/package/binary/home:olav-st/pythonqt-qt5?arch=x86_64&amp;filename=libpythonqt-qt5_3.0-1_amd64.deb&amp;repository=xUbuntu_16.04https%3A%2F%2Fi.imgur.com%2FbBwRy9D.png)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5a6a8312bdb43b0006bd3aba)

**Comment by bgeuken** [comment] 2018-04-04 08:30
This looks like caused by a wrongly crafted url.

=> Closing

**Closed by bgeuken** 2018-04-04 08:30 UTC
Labels: Bug :skull:, Frontend 👻, PR welcome :two_hearts:
