### ISSUE TITLE
[production][main#index] Validation failed: Login must have more than two characters

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#8699] opened 2019-11-11 11:06 UTC
main#index threw this 4 times
<pre>
Validation failed: Login must have more than two characters
</pre>
[https://build.opensuse.org/](https://build.opensuse.org/)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5dc6e67161df890008d100f3)

**Comment by dmarcoux** [comment] 2019-12-09 10:32
I forgot to write it shortly after assigning myself to this issue, but I couldn't reproduce this in the development environment. It happened 5 times in a timeframe of about 40 seconds in production, then never again. With this in mind, I will close the issue.

**Closed by dmarcoux** 2019-12-09 10:32 UTC
Labels: Bug :skull:, Frontend
