### ISSUE TITLE
Update the API documentation

### ISSUE THREAD

**Issue by crazyscientist** [openSUSE/open-build-service#7301] opened 2019-03-29 14:20 UTC
**Is your feature request related to a problem? Please describe.**
I'm accessing the API directly (neither `osc` nor `osc2` supports Python3), so I read a lot of [documentation](https://build.opensuse.org/apidocs/index). So I have come across a series of API endpoints that are either

- not included in the documentation, e.g. `/search/package_id`
- described incompletely in the documentation, e.g. for `/request/<id>?cmd=diff` arguments are missing
- misleading, e.g. `/search/<project>/_project` suggests that `_project` is a fixed part of the URL, but actually it can be replaced with a directory name

**Describe the solution you'd like**
I'd like to see a documentation that includes 

- all API endpoints
- all arguments/parameters for each API endpoint
- at least a short description what each endpoint and argument is used for

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by crazyscientist** [comment] 2019-04-02 14:29
Not only the API documentation, also the [List of event messages / queues for the message bus](https://openbuildservice.org/help/manuals/obs-admin-guide/obs.cha.administration.html#id-1.6.7.10.3.4.6) is terribly outdated. At first glance at least the following queues are missing:

* `__prefix__.request.review_changed`
* `__prefix__.request.reviews_done`

**Comment by hennevogel** [comment] 2019-04-02 20:19
@crazyscientist it might not be obvious to you, I apologize if it is, you can contribute by sending pull requests to the documentation. We also have some documentation about how to do that in [our wiki](https://github.com/openSUSE/open-build-service/wiki/OBS-API). Just wanted to make sure you know that.

**Comment by crazyscientist** [comment] 2019-04-03 06:24
@hennevogel thanks for pointing this out, but so far my observations are only based on my specific project where I'm trying to understand and refactor as well as add a handler for RabbitMQ messages. 

If I wanted to write pull request for the docs I would have to dig into the OBS code first to actually find out what to document :wink:

**Comment by adrianschroeter** [comment] 2019-04-08 11:38
The official place is the api.txt file from git. Only what is described there is by definition the offical api.
You may request further interfaces to become official, but you need to give a reason why.

https://github.com/openSUSE/open-build-service/blob/master/docs/api/api/api.txt

/search/package_id is more or less working by accident, but /search/package/id is the offical route which is there. Same with _project.

request command diff should be enhanced indeed.

The wiki is NOT any official resource in any case and is just a duplicate of the official api.

**Comment by hennevogel** [comment] 2019-04-08 11:49
> The wiki is NOT any official resource in any case and is just a duplicate of the official api

Relax, the wiki just documents how to change this.

**Comment by crazyscientist** [comment] 2019-05-02 07:04
I just found another API endpoint that is not documented:

`/source/<project>/<package>/_aggregate`

**Comment by hennevogel** [comment] 2019-05-02 09:55
> /source/<project>/<package>/_aggregate

That is a file.

**Comment by crazyscientist** [comment] 2019-05-02 09:59
Sorry, my bad.

**Comment by crazyscientist** [comment] 2020-01-28 14:17
Since creating this issue, I found yet another nice example of outdated/incorrect documentation. 

Imagine my surprise, when I discovered that `/search/request/id` understands the GET parameters `limit` and `offset`, which is not mentioned.

Maybe somebody familiar with the code would care to update the documentation?

https://www.suse.com/c/documentation-is-cheaper-than-no-documentation/ :wink:

**Comment by hennevogel** [comment] 2020-01-29 10:31
@crazyscientist what keeps you from sending a pull-request with your findings? I'm sure we can work out anything we miss then.

**Comment by crazyscientist** [comment] 2020-01-31 07:29
> what keeps you from sending a pull-request with your findings? 

All my findings so far are based on time spent working on **clients**. Every missing piece I mentioned in this issue was an accidental discovery.

Updating the API documentation solely based on me randomly stumbling across API usage in legacy client code most certainly is a bad idea. This way the documentation will probably never describe the full potential of the API.

Just yesterday I stumbled across another API route, which is not even mentioned in the docs: `/issue_trackers/<tracker>/issues/<name>` :wink:

**Comment by adrianschroeter** [comment] 2020-08-10 14:02
* /search/package_id is compat code, /search/package/id is documented
* /request/<id>?cmd=diff got added (in review)
* /source/..?cmd=diff options as well
* /issue_trackers/* calls got fixed and completed as well.

so I close this for now, but feel free to point me to further missing parts.

**Closed by adrianschroeter** 2020-08-10 14:02 UTC
Labels: Documentation :book:

**Comment by dcermak** [comment] 2020-12-09 09:03
> @crazyscientist what keeps you from sending a pull-request with your findings? I'm sure we can work out anything we miss then.

Can't speak for @crazyscientist, but for me it's usually unfamiliarity with Rails & the perl backend. So if I contribute to the docs, I usually have to do it by trial and error/reverse engineering. Also, I'm pretty much a complete noob with respect to rng/xsd, so it takes me ages to actually get the schema right so that the CI will eventually pass (doesn't help that the CI is sometimes really not very verbose about what went wrong and figuring out stuff like this: https://github.com/openSUSE/open-build-service/pull/10411/commits/0201f84ad817ecdb21eeb413ded7699ecae66fb4#diff-f0e4b08cedbe424e02727106fc2cb8fbae9776eaa6e48ef2c1d58e541a3a47a2 takes your average contributor ages).

And it also does not help that documentation PRs are just left unreviewed for a long time. I really don't want to be salty here, but it is not encouraging to contribute further, if no one bothers to take a look after spending **hours** to document **your** work.

**Comment by crazyscientist** [comment] 2020-12-09 09:32
> Can't speak for @crazyscientist, but for me it's usually unfamiliarity with Rails & the perl backend.

I have some basic knowledge of Perl and would not mind looking into Rails, but for me there are other reasons why I won't create documentation PRs:

1. As @adrianschroeter mentioned in a meeting yesterday: The API is not one piece, but there are several components contributing to it.
1. I tried to figure out once how the API parameter `expand` actually was used in a particular API call, but never figured it out.
1. My expectation to an API documentation is already listed in the description. Me searching the haystack (aka. source code) to find just a few needles seems like a waste of time.
1. In general documenting APIs manually feels wrong, especially when you are used to tools that generate the docs in a fully automated fashion.

To me this sounds like a task for a developer familiar with the sources, and not something a user, who just wants to use the API, should do.

**Comment by dcermak** [comment] 2020-12-09 09:45
> To me this sounds like a task for a developer familiar with the sources, and not something a user, who just wants to use the API, should do.

Imho you couldn't be more correct here.

**Comment by adrianschroeter** [comment] 2020-12-09 09:56
but just re-doing everything will just replace gaps with others. Yes, it is developer work and it should be done by every developer who touches the api. But I do not see what generic requests help here, because you need to look into the missing parts and explain  the background. The biggest problem is to identify these parts and to deliver the content, not writing the same thing at a different place.

**Comment by crazyscientist** [comment] 2020-12-09 11:36
> but just re-doing everything will just replace gaps with others.

Agreed, unless this refactoring would make use of frameworks/tools to generate the documentation automatically. But this decision is also up to (experienced) build service developers :wink:
