### ISSUE TITLE
[production][request#changerequest] undefined method `can_be_modified_by?' for nil:NilClass

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#6968] opened 2019-02-12 15:29 UTC
request#changerequest threw this 0 times
<pre>
undefined method `can_be_modified_by?&#39; for nil:NilClass
</pre>
[https://build.opensuse.org/request/changerequest](https://build.opensuse.org/request/changerequest)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5c6219b7ef83cd0008b7119a)

**Comment by eduardoj** [comment] 2019-09-25 07:04
#8403 was a duplicate of this one, and has been solved. Closing.

**Closed by eduardoj** 2019-09-25 07:04 UTC
Labels: Bug :skull:, Frontend
