### ISSUE TITLE
[backend] new perl-BSSolv causes expansion errors

### ISSUE THREAD

**Issue by mmohring** [openSUSE/open-build-service#3042] opened 2017-04-26 11:15 UTC
Issue description
====================
From perl-BSSolv version 0.31 or higher on, the backend testsuite fails and also in the obs-server.spec "PreReq:         /usr/sbin/useradd /usr/sbin/groupadd" causes an expansion error when installed on an OBS instance.

Expected result
============
As with version 0.29, all should still work. But now you get an "expansion error".

How to Reproduce
===============
Install the newer versions of perl-BSSolv on your local OBS instance, restart the scheduler and trigger a rebuild of the obs-server package copy from OBS:Server:Unstable. Then you get an expansion error telling you "/usr/sbin/groupadd" is missing.

**Comment by mmohring** [comment] 2017-04-26 11:22
perl-BSSolv version 0.31 seems to cause the expansion error, and the very newest version perl-BSSolv version 0.32 seems to cause the backend testsuite failure.

**Comment by mmohring** [comment] 2017-04-26 11:30
Cross checked it: going back to perl-BSSolv version 0.29 makes it work again.

**Comment by mmohring** [comment] 2017-04-26 12:14
I am on git master like BOO, OBS:Server:Unstable/obs-server. I can see the same error in the logfile in BOO, for git commit 3cf3c584671a3c3f8b93fcb7dcfb9753e3ca1f8a . But as I wrote, it seems not related to the obs-server version, I had this errors (expansion error and now backend testsuite failure) with older versions of obs-server. Is it a perl-BSSolv incompatibility / breakage with the OBS Scheduler ?

**Comment by lethliel** [comment] 2017-04-26 12:34
It is an error in our test fixtures. 
The FileProvides causes this. 

`FileProvides: /usr/sbin/groupadd pwdutils`
must be
`FileProvides: /usr/sbin/groupadd shadow`

perl-BSSolv now handles this line a little bit different. (Background: /usr/bin/groupadd moved from pwdutils to shadow)

**Comment by mmohring** [comment] 2017-04-26 12:38
OK. I noticed your fix and was first a bit confused. I guess perl-BSSolv version 0.31 still has problems. So you have to go to perl-BSSolv version 0.32 and your patch in obs-server resolves an real error in the testsuite.

**Comment by mmohring** [comment] 2017-04-26 13:43
I will take a look what you are doing in the fixes #3044 and report back. Anyway I still have the "unresolvable nothing provides /usr/sbin/groupadd" even with perl-BSSolv version 0.32 outside of the testsuite.

**Comment by lethliel** [comment] 2017-04-26 13:45
have you changed your FileProvides line for /usr/sbin/groupadd in prjconf?

**Comment by mmohring** [comment] 2017-04-26 13:46
Which prjconf ? OBS or openSUSE ?

**Comment by mmohring** [comment] 2017-04-26 13:52
`$ osc -A <myobs> meta prjconf openSUSE:Leap:42.1 | grep groupadd` says:
FileProvides: /usr/sbin/groupadd pwdutils
Is that the problem ? So shall I testwise fix this in the prjconf for openSUSE:Leap:42.1 ? Does the "FileProvides: /usr/sbin/groupadd shadow" in the obs-server.spec not overwrite the prjconf ?

**Comment by lethliel** [comment] 2017-04-26 13:53
Yes. Please fix it in the prjconf. That should do the trick.

**Comment by mlschroe** [comment] 2017-04-26 13:53
Here's a bit of background info. The FileProvides directive is supposed to look like this:
```
FileProvides: /file/path package_that_has_the_file
```

By mistake, the perl-BSSolv implementation looked into provides when resolving package_that_has_the_file. This went unnoticed for some time, but some weeks ago we got a bugreport that /usr/bin/python was resolved to python3 leading to build failures. What happened is that the config contains:
```
FileProvides: /usr/bin/python python
```
And python3 has a "Provides: python = 3".

We had a long discussion about what to do but in the end decided to bite the bullet and change the code to work as intended. Yes, it's an incompatible change but it is much saner that way.

**Comment by mmohring** [comment] 2017-04-26 13:56
I now changed the prjconf of my local copy of OBS:Server:Unstable, and that worked. Changing the obs-server.spec did *not* work.

**Comment by mmohring** [comment] 2017-04-26 14:04
For the Leap 42.2 target, in my case a DoD, I now get "libsystemd0-mini conflicts with systemd, systemd conflicts with libsystemd0-mini" . The other targets in my test system do now build.

**Comment by mlschroe** [comment] 2017-04-26 14:07
This is probably correct. There was also a tweak in the algorithm to make the solver more deterministic. Before, it was somewhat random which systemd package was chosen.

**Comment by mmohring** [comment] 2017-04-26 14:09
@mlschroe I understand your argument. How will you resolve the compatibility problem in your main OBS instance then ? You need to fix all broken prjconf's then ?

**Comment by mmohring** [comment] 2017-04-26 14:12
OK, you are right, better fix the problem if it resulted in random behavior.

**Comment by lethliel** [comment] 2017-04-26 15:07
solved

**Closed by lethliel** 2017-04-26 15:07 UTC

**Comment by mmohring** [comment] 2017-04-26 15:11
Thx for the explaination and the fixes.
