### ISSUE TITLE
Can't hide cmake in my repository

### ISSUE THREAD

**Issue by Zenitur** [openSUSE/open-build-service#2017] opened 2016-08-14 01:10 UTC
Few days ago I successfully hide autoconf in my repository. Now I can't hide cmake, I see error 404. https://build.opensuse.org/flag/home:linux4humans:qt5/cmake?architecture=&flag=publish&status=disable

**Comment by bgeuken** [comment] 2016-08-14 08:30
That's a duplicate of #2007 

Thanks for the report!

**Closed by bgeuken** 2016-08-14 08:30 UTC
