### ISSUE TITLE
editing change log in web interface removes delimiter lines

### ISSUE THREAD

**Issue by kollix** [openSUSE/open-build-service#10369] opened 2020-11-01 20:34 UTC
# Issue Description
I used the web interface on build.opensuse.org for my project "liquidshell"
https://build.opensuse.org/package/show/home:martinkoller/liquidshell
 and changed the "changes"  file by clicking on 
https://build.opensuse.org/package/view_file/home:martinkoller/liquidshell/liquidshell.changes?expand=1
in this web page I then clicked on the link for "Insert changes entry template" added the text and clicked then the save button at the bottom.

However I was notified that the "save" also removed existing delimiter lines.
See https://build.opensuse.org/request/show/845265

Also what I do not understand looking at the above "Request 845265" page,
the diff it shows is not what I changed. This was the previous change some month ago.
Today I added a NEW change log above the "Wed May 13 17:05:02 UTC 2020",
which starts with "Sun Nov  1 14:07:21 UTC 2020" which you can see here
https://build.opensuse.org/package/view_file/home:martinkoller/liquidshell/liquidshell.changes?expand=1

Note that I did not change anything with these delimiter lines.

Expected Result
============
don't change what I did not touch.

**Comment by eduardoj** [comment] 2024-08-21 15:32
After taking a look at the revision history of the package (see https://build.opensuse.org/request/show/845265 ), I fear this issue was caused by using a non updated version of the branched package.

This can be avoided by branching the package just before creating a submit request, instead of keeping a copy of the package in the home project.

I'll close the issue. Please reopen if this is sill happening.

Please next time make sure you create submit requests with an updated version

**Closed by eduardoj** 2024-08-21 15:32 UTC
Labels: Bug, Frontend
