### ISSUE TITLE
OBS reused counters

### ISSUE THREAD

**Issue by bmwiedemann** [openSUSE/open-build-service#13279] opened 2022-10-27 07:46 UTC
While working on the openSUSE mirror infrastructure, I noticed that in a Tumbleweed update some rpm packages got replaced by different versions of identical name.

    tumbleweed/repo/oss/noarch/python310-ecdsa-0.17.0-1.8.noarch.rpm
    tumbleweed/repo/oss/noarch/python38-ecdsa-0.17.0-1.8.noarch.rpm
    tumbleweed/repo/oss/noarch/python39-ecdsa-0.17.0-1.8.noarch.rpm
    tumbleweed/repo/oss/noarch/python310-sentry-sdk-1.6.0-1.3.noarch.rpm
    tumbleweed/repo/oss/noarch/python38-sentry-sdk-1.6.0-1.3.noarch.rpm
    tumbleweed/repo/oss/noarch/python39-sentry-sdk-1.6.0-1.3.noarch.rpm

My suspicion is that it comes from the [python singlespec magic](https://code.opensuse.org/package/python-ecdsa/blob/master/f/python-ecdsa.spec#_38) that produces 3 binary packages from a single spec file but none of the outputs is named `python-ecdsa`

Interestingly, `osc jobhistory openSUSE:Factory/python-sentry-sdk standard x86_64` showed a "source change" for both

    2022-10-25 09:27:29  python-ecdsa                                       source change    succeeded                2m 45s   lamb16:2  
    
    2022-10-06 05:54:07  python-sentry-sdk                                  new build        succeeded                1m 51s   sheep86:1       
    2022-10-24 09:16:09  python-sentry-sdk                                  source change    succeeded                1m 28s   sheep88:16

`osc jobhistory openSUSE:Factory/python-sentry-sdk standard i586` seems to have a contibution:

    2022-10-06 07:35:52  python-sentry-sdk                                  rebuild counter  succeeded                4m  1s   build83:1       
    2022-10-24 09:17:06  python-sentry-sdk                                  source change    failed                   2m 46s   lamb28:5        
    2022-10-26 08:27:46  python-sentry-sdk                                  new build        succeeded                2m 52s   cloud126:1      

In the 20221024 tumbleweed snapshot, the `sheep86` build was replaced with the `build83` one.

**Comment by bmwiedemann** [comment] 2022-10-27 07:59
correction, there was 1 checkin with a version update
https://code.opensuse.org/package/python-sentry-sdk/c/f95446b58a13ba65bff865baaac0078540f3a8bf
but this is not what was published.

    rpm -qpi /ipns/opensuse.zq1.de/history/20221024/tumbleweed/repo/oss/noarch/python38-sentry-sdk-1.6.0-1.3.noarch.rpm
    Signature   : RSA/SHA256, 2022-10-06T07:35:52 UTC, Key ID b88b2fd43dbdc284

and before it was

    rpm -qpi /ipns/opensuse.zq1.de/history/20221023/tumbleweed/repo/oss/noarch/python38-sentry-sdk-1.6.0-1.3.noarch.rpm
    Signature   : RSA/SHA256, 2022-10-06T05:54:07 UTC, Key ID b88b2fd43dbdc284

[python-sentry-sdk-1.10.1](https://build.opensuse.org/package/show/openSUSE:Factory/python-sentry-sdk) shows published but is not in the repo - maybe some mixup happened there?

**Comment by bmwiedemann** [comment] 2022-10-27 08:05
OK. both got version updates:
https://code.opensuse.org/package/python-ecdsa/c/e02f21ecdf929f76ab03973d2d34a7b85f5114f7

**Comment by hennevogel** [comment] 2022-10-27 09:16
Not sure why you open an issue here? Please talk to the python maintainers.

**Comment by bmwiedemann** [comment] 2022-10-27 09:24
@hennevogel because this is a bug in the OBS publishing logic. It exchanged the x86_64 python38-sentry-sdk-1.6.0-1.3.noarch.rpm build with the i586 python38-sentry-sdk-1.6.0-1.3.noarch.rpm build when the new version was submitted and half-failed.

**Comment by hennevogel** [comment] 2022-10-27 09:27
I would say this is expected. Always was. If two packages (or magic) produce the same binaries, the last one wins. But maybe I'm wrong 😸

**Comment by bmwiedemann** [comment] 2022-10-27 09:33
Rudi said, there should always be preference for one architecture, e.g. x86_64 here.
I suspect the succeeded x86_64 build played a role here, because the failed i586 build prevented it from being published, but it might have replaced the old x86_64 binaries already at that point.

**Comment by Firstyear** [comment] 2022-11-14 22:07
@hennevogel The problem is this breaks mirrors and updates for clients because sometimes what will happen is that the package is "republished" with the exact same name/version, but will checksum differently. Mirrors/caches that check on the unique file path say "nothing changed" but the rpm metadata checksums no longer match so the client gets an invalid package error. We've seen it publicly occurring and affecting real users.

**Comment by adrianschroeter** [comment] 2022-11-15 07:42
OBS publisher itself is handling this situation fine, as the former binary stays.

But this is an issue with product builder, which has no information that there was one released in former build.

The only way to avoid this atm is not to publish when noarch builds are unfinished or have failed. In that case always the same one will be picked due to a fixed order. But when the primary arch did not build for some reason it will switch later.

However, this is not directly an OBS topic, more a workflow or product build issue.

**Closed by adrianschroeter** 2022-11-15 07:42 UTC
Labels: Backend
