### ISSUE TITLE
The project status page lists invalid requests

### ISSUE THREAD

**Issue by ciz** [openSUSE/open-build-service#2107] opened 2016-09-06 09:19 UTC
See eg. [Factory](https://build.opensuse.org/project/status/openSUSE:Factory) or [Leap](https://build.opensuse.org/project/status/openSUSE:Leap:42.2)

The generation is broken, the html links to the requests aren't rendered correctly, The arrows ("<>") are replaced by their respective html entities.
Moreover, the request numbers are bogus.
See the Leap status page, for setools the table says:
Fails for 45 days: Unknown build failure
Request <a href="/request/show/493200">493200</a> to openSUSE:Leap:42.2

There's no request with number 493200.

**Comment by bgeuken** [comment] 2016-09-06 10:03
The html links should be fixed now, except the ones that get created from comments (eg. the one to bugzilla).

I did not look into the wrong request ids yet, but this might be caused by a migration we ran to update bs request counter. Or it's another leftover from the id -> number migration. 

I'll have a look after lunch.

**Comment by bgeuken** [comment] 2016-09-06 11:33
The raw html links are fixed in production and I am preparing a PR, working on the tests right now: https://github.com/bgeuken/open-build-service/tree/bs_requests

@adrianschroeter The other issues seem to be caused by the request id / number change. Can you take care of this?

**Comment by adrianschroeter** [comment] 2016-09-06 11:57
pull request is open, but this can't be a new regression ....

**Comment by ciz** [comment] 2016-09-07 13:26
The [Leap status page](https://build.opensuse.org/project/status/openSUSE:Leap:42.2) is now displayed properly, even the request numbers are now correct.
Thank you.

**Comment by mschnitzer** [comment] 2016-10-10 07:01
@ciz so this can be closed?

**Comment by ciz** [comment] 2016-10-10 09:23
@mschnitzer, yes.

**Comment by bgeuken** [comment] 2016-10-17 06:27
Then let's close it;-)

**Closed by bgeuken** 2016-10-17 06:27 UTC
Labels: frontend, P3, Regression
