### ISSUE TITLE
webui is not validating double entries in repositories

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#2484] opened 2016-12-20 08:45 UTC
webui/repositories#create threw this 1 times
<pre>
ActiveXML::Transport::Error: &lt;status code=&quot;400&quot;&gt;
  &lt;summary&gt;repository openSUSE_Leap_42.2 listed more than once&lt;/summary&gt;
&lt;/status&gt;

</pre>
[https://build.opensuse.org/project/save_repository?project=home%3Ajspicak42](https://build.opensuse.org/project/save_repository?project=home%3Ajspicak42)"

[See this exception on Errbit](http://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5858dd8aa9fec00007000000)

**Comment by hennevogel** [comment] 2017-02-28 14:26
duplicate of #2019

**Closed by hennevogel** 2017-02-28 14:26 UTC
Labels: Bug, frontend, junior, P3, Regression
