### ISSUE TITLE
scroll bar is covered by a div containing buttons

### ISSUE THREAD

**Issue by guoyunhe** [openSUSE/open-build-service#11627] opened 2021-09-16 13:20 UTC
# Issue Description
You cannot scroll the table horizontally because the scroll bar is covered by a div containing buttons. (some times, especially when you have slow internet)

Expected Result
============
You should be able to click and drag the scrollbar.

How to Reproduce
===============
1. Go to https://build.opensuse.org/project/monitor/Emulators?blocked=0&building=0&dispatching=0&finished=0&scheduled=0&signing=0&succeeded=0
2. Try to scroll the table horizontally

Further Information
===============
I see the table is using some kind of JS library to calculate absolute position and size. But it cannot adjust it when the content loads very slow.

**Comment by guoyunhe** [comment] 2021-09-16 13:21
![图片](https://user-images.githubusercontent.com/5836790/133619725-7fc710bc-3793-4745-b154-3a8095e455d0.png)

**Comment by dmarcoux** [comment] 2021-09-16 13:27
Again, this is a duplicate of #11235.

**Closed by dmarcoux** 2021-09-16 13:27 UTC
