### ISSUE TITLE
Flickering test: Unable to find css "#flash-messages"

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#6046] opened 2018-10-08 08:09 UTC
```
  1) Bootstrap_Packages changing the package's devel project
     Failure/Error: find('#flash-messages', visible: false)
     
     Capybara::ElementNotFound:
       Unable to find css "#flash-messages"
     # ./spec/bootstrap/features/webui/packages_spec.rb:103:in `block (2 levels) in <top (required)>'
```

**Comment by hennevogel** [comment] 2018-10-08 10:18
duplicate of #6034

**Closed by hennevogel** 2018-10-08 10:18 UTC
Labels: Bootstrap :rocket:, Flickering :cyclone:, Test Suite :syringe:

**Comment by dmarcoux** [comment] 2018-10-08 14:20
It's not the same test which is flickering. The cause seems to be the same though.
