### ISSUE TITLE
WebUI: repo link for packages from linked project is broken

### ISSUE THREAD

**Issue by ggardet** [openSUSE/open-build-service#13175] opened 2022-10-05 07:48 UTC
# Issue Description
On the WebUI, repo link for packages from linked project is broken. 
For example, on https://build.opensuse.org/package/show/openSUSE:Factory:ARM/vlc if you click on `standard` on the right hand side, you will get: ` repository 'openSUSE:Factory/standard' has no architecture 'aarch64' 404 repository 'openSUSE:Factory/standard' has no architecture 'aarch64'`

**This is a regression**.

I suspect the root of the problem is similar to https://github.com/openSUSE/open-build-service/issues/13147

Expected Result
============
Link should work properly.

How to Reproduce
===============
Go to  https://build.opensuse.org/package/show/openSUSE:Factory:ARM/vlc 
Click on `standard` on the right hand side, and you will get: ` repository 'openSUSE:Factory/standard' has no architecture 'aarch64' 404 repository 'openSUSE:Factory/standard' has no architecture 'aarch64'`

Further Information
===============
* build.o.o

**Comment by ggardet** [comment] 2022-10-05 08:21
Cc @hennevogel

**Comment by hennevogel** [comment] 2022-10-05 09:02
duplicate of #13147

**Closed by hennevogel** 2022-10-05 09:02 UTC
