### ISSUE TITLE
[production][project#save_meta] SUSE:SLE-12:SP3

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#4051] opened 2017-10-20 12:13 UTC
project#save_meta threw this 66 times
<pre>
SUSE:SLE-12:SP3
</pre>
[https://build.opensuse.org/project/save_meta/devel:languages:erlang](https://build.opensuse.org/project/save_meta/devel:languages:erlang)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59d3c162ce3923000836ddd9)

**Comment by adrianschroeter** [comment] 2017-10-23 07:28
not handled validation failure when referencing a not existing project in repository config

**Comment by ChrisBr** [comment] 2017-11-06 15:33
Duplicate of https://github.com/openSUSE/open-build-service/issues/3916

**Closed by ChrisBr** 2017-11-06 15:33 UTC
Labels: Bug, Frontend, P3
