### ISSUE TITLE
[production][webui/project#destroy] SystemStackError: stack level too deep

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#2831] opened 2017-03-14 13:16 UTC
webui/project#destroy threw this 0 times
<pre>
SystemStackError: stack level too deep
</pre>
[https://build.opensuse.org/project/destroy](https://build.opensuse.org/project/destroy)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/58c7e8727725fb0007000011)

**Comment by bgeuken** [comment] 2017-11-07 11:20
Duplicate of #2554

**Closed by bgeuken** 2017-11-07 11:20 UTC
Labels: Bug, Frontend
