### ISSUE TITLE
[production][maintained_projects#index] undefined method `to_unsafe_h' for nil:NilClass

### ISSUE THREAD

**Issue by eduardoj** [openSUSE/open-build-service#8432] opened 2019-09-25 07:38 UTC
maintained_projects#index threw this 1 times
<pre>
undefined method `to_unsafe_h&#39; for nil:NilClass
</pre>
[https://build.opensuse.org/projects/openSUSE:Maintenance/maintained_projects.json?amp%3B_=1567491998337&amp;amp%3Bcolumns%5B0%5D%5Bdata%5D=name&amp;amp%3Bcolumns%5B0%5D%5Bname%5D=&amp;amp%3Bcolumns%5B0%5D%5Borderable%5D=true&amp;amp%3Bcolumns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&amp;amp%3Bcolumns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&amp;amp%3Bcolumns%5B0%5D%5Bsearchable%5D=true&amp;amp%3Bcolumns%5B1%5D%5Bdata%5D=actions&amp;amp%3Bcolumns%5B1%5D%5Bname%5D=&amp;amp%3Bcolumns%5B1%5D%5Borderable%5D=true&amp;amp%3Bcolumns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&amp;amp%3Bcolumns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&amp;amp%3Bcolumns%5B1%5D%5Bsearchable%5D=true&amp;amp%3Blength=10&amp;amp%3Border%5B0%5D%5Bcolumn%5D=0&amp;amp%3Border%5B0%5D%5Bdir%5D=asc&amp;amp%3Bsearch%5Bregex%5D=false&amp;amp%3Bsearch%5Bvalue%5D=c&amp;amp%3Bstart=0&amp;draw=2](https://build.opensuse.org/projects/openSUSE:Maintenance/maintained_projects.json?amp%3B_=1567491998337&amp;amp%3Bcolumns%5B0%5D%5Bdata%5D=name&amp;amp%3Bcolumns%5B0%5D%5Bname%5D=&amp;amp%3Bcolumns%5B0%5D%5Borderable%5D=true&amp;amp%3Bcolumns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&amp;amp%3Bcolumns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&amp;amp%3Bcolumns%5B0%5D%5Bsearchable%5D=true&amp;amp%3Bcolumns%5B1%5D%5Bdata%5D=actions&amp;amp%3Bcolumns%5B1%5D%5Bname%5D=&amp;amp%3Bcolumns%5B1%5D%5Borderable%5D=true&amp;amp%3Bcolumns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&amp;amp%3Bcolumns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&amp;amp%3Bcolumns%5B1%5D%5Bsearchable%5D=true&amp;amp%3Blength=10&amp;amp%3Border%5B0%5D%5Bcolumn%5D=0&amp;amp%3Border%5B0%5D%5Bdir%5D=asc&amp;amp%3Bsearch%5Bregex%5D=false&amp;amp%3Bsearch%5Bvalue%5D=c&amp;amp%3Bstart=0&amp;draw=2)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5d8a5b5e0218e70014027f0f)

**Comment by hennevogel** [comment] 2019-09-25 08:29
duplicate of #8431

**Closed by hennevogel** 2019-09-25 08:29 UTC
Labels: Bug :skull:, Frontend
