### ISSUE TITLE
DelayedJob queue dies afer Mysql2::Error: Data too long for column 'event_payload'

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#3339] opened 2017-07-03 09:03 UTC
delayed_job#Delayed::PerformableMethod threw this 0 times
<pre>
Mysql2::Error: Data too long for column &#39;event_payload&#39; at row 1: INSERT INTO `notifications` (`type`, `event_type`, `event_payload`, `subscription_receiver_role`, `created_at`, `updated_at`, `subscriber_type`, `subscriber_id`) VALUES (&#39;Notification::RssFeedItem&#39;, &#39;Event::RequestCreate&#39;, &#39;---\nauthor: awissu\ndescription: |-\n  - Update to 0.6.5:\n    * Correcting MimeType in .desktop file.\n    * misc code cleanups\n    * Fix text undo\n    * Make sure canvas items get freed from memory\n    * Update first presentation\n    * Add a way to launch an image editor\n    * monitor file changes\n    * Load images from file\n    * Update com.github.philip-scott.spice-up.appdata.xml\n    * Merge pull request #126 from danrabbit/patch-1\n    * Update README.md\n    * Bump version number\n    * Clone button added\n    * Readme reloaded (#125)\n    * Add link to AppCenter\n    * Style changes\n    * Style the color popover\n    * Better color palette\n    * Added mimetype icon\n    * Updated tes
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59577f34060096000e62918d)

**Comment by eduardoj** [comment] 2018-01-10 14:53
Duplicate of #4161. Closing.

**Closed by eduardoj** 2018-01-10 14:53 UTC
Labels: Bug, Frontend
