### ISSUE TITLE
Missing information in some <request>'s <review> elements

### ISSUE THREAD

**Issue by lchiquitto** [openSUSE/open-build-service#3123] opened 2017-05-18 19:09 UTC
One example of this issue can be seen in release request #131933 (IBS).

It was created by BenniBrunner at 2017-04-28T10:40:30.

The only reviewer configured in the target projects is group `"qam-auto"`, and it is correctly assigned by the Build Service as reviewer shortly after creation at 2017-04-28T10:40:35.

The `qam-auto` reviews are processed by a script that assigns additional reviewers. This script was executed around 2017-04-28T10:45:10 and assigned four reviewers to the request:

- `by_group="qam-manager"` at 2017-04-28T10:45:12
- `by_group="slepos-team"` at 2017-04-28T10:45:15
- `by_group="qam-ses"` at ??? (by inference we can guess it's 2017-04-28T10:45:17)
- `by_group="qam-sle"` at ??? (by inference we can guess it's 2017-04-28T10:45:19)

And then accepted the `"qam-auto"` review at 2017-04-28T10:45:19.

The problem I'd like to report here is exactly this inconsistency in the `<review>` elements. The four reviewers were added roughly at the same time, by the same user (maintenance-robot). Still, two of them have the creation timestamp (`"when"`) and the user (`"who"`) who changed the review's state:

```
<review state="accepted" when="2017-04-28T10:45:12" who="ktsamis" by_group="qam-manager">
<review state="accepted" when="2017-04-28T10:45:15" who="nadvornik" by_group="slepos-team">
<review state="accepted" by_group="qam-ses">
<review state="accepted" by_group="qam-sle">
```

By inspecting the request's history I think the last two `<review>` elements should look like this:

```
<review state="accepted" when="2017-04-28T10:45:17" who="SShyukriev" by_group="qam-ses">
<review state="accepted" when="2017-04-28T10:45:19" who="ktsamis" by_group="qam-sle">
```

**Comment by ChrisBr** [comment] 2017-06-26 15:16
@lchiquitto did it happen more often the last few weeks?

**Comment by lchiquitto** [comment] 2017-06-26 23:48
Hard to say.. Looks normal to my eyes. In the table below the second column is the total number of maintenance_incident + maintenance_release requests, the third column is the number of requests that have at least one review missing an `who` and/or `when` attribute.

The percentage of "broken" reviews is much higher in the last week because these requests have more open reviews and if I understand correctly the fields are sometimes filled up when the review is accepted.

```
Week All Broken
2017-01  74 21 28.38%
2017-02 161 76 47.2%
2017-03  75 24 32.0%
2017-04 104 36 34.62%
2017-05 240 93 38.75%
2017-06 118 50 42.37%
2017-07 132 41 31.06%
2017-08  33 11 33.33%
2017-09 121 42 34.71%
2017-10 167 66 39.52%
2017-11 113 44 38.94%
2017-12 196 88 44.9%
2017-13 128 54 42.19%
2017-14 154 58 37.66%
2017-15 212 97 45.75%
2017-16 106 37 34.91%
2017-17 136 46 33.82%
2017-18 124 51 41.13%
2017-19 108 51 47.22%
2017-20 129 56 43.41%
2017-21 140 75 53.57%
2017-22 140 65 46.43%
2017-23 139 76 54.68%
2017-24 146 61 41.78%
2017-25 187 70 37.43%
2017-26  31 30 96.77%
```

**Comment by lchiquitto** [comment] 2017-07-12 17:55
Some context (as an attempt to bargain a higher priority ;)): these inconsistencies make Maintenance's attempt to track the time spent in each stage of an update workflow.

Take for example these `review` elements of RR#135448 (internal Build Service instance):

```
  <review state="accepted" when="2017-07-05T14:20:10" who="pgeorgiadis" by_group="qam-openqa">
    <comment>[oscqam] Approving 135448 for group qam-openqa.</comment>
    <history who="sle-qam-openqa" when="2017-07-05T15:22:37">
      <description>Review got reopened</description>
      <comment>now testing in openQA</comment>
    </history>
    <history who="pgeorgiadis" when="2017-07-07T12:53:32">
      <description>Review got accepted</description>
      <comment>[oscqam] Approving 135448 for group qam-openqa.</comment>
    </history>
  </review>

  <review state="accepted" by_group="qam-sle">
    <comment/>
    <history who="atighineanu" when="2017-07-12T06:55:44">
      <description>Review got accepted</description>
      <comment>review assigend to user atighineanu</comment>
    </history>
  </review>

  <review state="new" by_user="atighineanu">
    <history who="atighineanu" when="2017-07-12T06:55:44">
      <description>Review got assigned</description>
      <comment>review for group qam-sle</comment>
    </history>
  </review>
```

The two `by_group` reviewers (`qam-sle` and `qam-openqa`) have been added to the request at the same time, by the same user. Both are now in state `accepted`, but only `qam-openqa`'s review contains a `when` attribute recording when the `<review>` was created. Likewise, the `Review got assigned` event seems to be recorded inconsistently: in the case above, only the `by_user` review contains it.

So, if we want to get, for each review, the timestamps of *assignment* and *acceptance*, we need to code a few special cases in our tools.

**Comment by lchiquitto** [comment] 2017-08-31 13:56
Any chance to increase the priority of this issue? Until this is fixed we cannot reliably calculate for how long a review is open.

**Comment by ChrisBr** [comment] 2017-08-31 13:59
@lchiquitto which route are you accessing?

**Comment by lchiquitto** [comment] 2017-08-31 14:05
@ChrisBr Not sure if I understand the question, but `api '/request/137617?withfullhistory=1'` for example shows (now) this incomplete review:
```
  <review state="new" by_user="djz88">
    <comment>qam-cloud</comment>
  </review>
```

**Comment by ChrisBr** [comment] 2017-08-31 14:39
@lchiquitto the problem is that the reviews don't have a reviewer (I just checked in the db, they have a creator but no reviewer attribute). However, we only render ``who`` and ``when`` if there is a reviewer.
https://github.com/openSUSE/open-build-service/blob/master/src/api/app/models/review.rb#L163 

In ``new_from_xml`` we set creator = reviewer = who. So the question is now how you get the review in without setting the reviewer (or where do you overwrite it again) :thinking: 

@adrianschroeter what is the difference between the ``reviewer`` and the ``creator``? And can we also just check for the creator?

**Comment by ChrisBr** [comment] 2017-08-31 14:43
Ok, when adding a review via the webui, the reviewer is nil :cry: 

Still open question @adrianschroeter: What is the difference between the reviewer and the creator?

**Comment by lchiquitto** [comment] 2017-08-31 14:46
I couldn't find a pattern. Sometimes for example reviews added by the Build Service itself (when the request is created) lack the `when` element.

**Comment by ChrisBr** [comment] 2017-08-31 15:00
@lchiquitto yep, the default reviewers also don't have the reviewer set ...

**Comment by ChrisBr** [comment] 2017-08-31 15:05
@lchiquitto for the default reviews I understand that the ``who`` is missing as they're created automatically. However, I don't understand why we don't render the ``when`` if there is no reviewer set.

Question now: What would be the expection for the default reviews reviewer attribute (I can render the ``when``, however, it would be still strange that the ``who`` is empty, not?)

**Comment by lchiquitto** [comment] 2017-08-31 15:10
From my point of view it's perfectly fine if `who` is missing when the review is added.

**Comment by adrianschroeter** [comment] 2017-08-31 15:28
@ChrisBr, sorry, didn't saw your question:

creator: The person who created the review. Might be empty on default creator (we may have built-in bots later on with _ prefix btw, so we could also render the nil here as "_default").
reviewer(db)=who(xml): The person who did the last state change

However, the history elements come from history_elements table, the who in xml there is the user_id entry.

**Comment by lchiquitto** [comment] 2017-08-31 15:36
For the record, created https://etherpad.nue.suse.com/p/reviewing-reviews-and-reviewers to try to document better these reviews

**Comment by ChrisBr** [comment] 2017-08-31 15:38
Ok, seems like assigning reviews does not update the reviewer.

**Comment by ChrisBr** [comment] 2017-09-01 11:29
@lchiquitto I monkey patched IBS with the PR, please checkout! I also commented on your etherpad: The problem is that assigning a review (which is the usual maintenance workflow assigning from a group to a user) does not update the reviewer attribute. If there is any additional step in between (e.g. the first one gets assigned and then reopened, the reviewer gets set which masks the problem).

Fixes I applied:
- Always render the when attribute as it is independent from the reviewer
- Set the reviewer also on assign review method
- Set the reviewer when creating a review via the webui

**Comment by ChrisBr** [comment] 2017-09-01 12:41
Fixed in https://github.com/openSUSE/open-build-service/pull/3736 and deployed to IBS. OBS will be deployed beginning of next week.

**Closed by ChrisBr** 2017-09-01 12:41 UTC
Labels: Bug, Frontend, P2

**Comment by lchiquitto** [comment] 2017-09-04 11:39
@ChrisBr, Much appreciated! `when` (created-at) is now always rendered and this makes our use case much simpler.

There still one part I don't understand completely (I updated the Etherpad page, would appreciate if you could take a look when time permits).

**Comment by lchiquitto** [comment] 2017-09-04 13:01
@ChrisBr, nevermind. Now I understand the difference.
