### ISSUE TITLE
Appliance ISO does not install OBS, it boots into a live environment

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/open-build-service#4445] opened 2018-02-04 21:41 UTC
Issue description
====================
I attempted to set up an OBS system using the v2.9.0 beta1 appliance ISO on a machine, but it did not install OBS onto the disk, instead it booted into a live environment.

Expected result
============
OEM install process should run on booting the appliance ISO to install it to disk.

How to Reproduce
===============
1. Flash the ISO to a USB stick
2. Boot the USB stick
3. Watch it boot into OBS instead of the OEM installer

Further information
===============
* Exact ISO version: 2.9.0 beta 1 Build 11.1

**Comment by mschnitzer** [comment] 2018-02-05 07:26
I can confirm that.

@hennevogel @eduardoj is this the intended behavior? At least `2.8.4` has an `Install` option.

**Comment by adrianschroeter** [comment] 2018-02-05 07:40
latest kiwi seems to have dropped this feature. We still would like to offer this, just checking with kiwi people.

@M0ses  is on it as well.

**Comment by M0ses** [comment] 2018-02-05 10:09
```installiso=true``` has been removed - I will fix this for all of our Appliance images

**Comment by Conan-Kudo** [comment] 2018-02-15 14:06
@M0ses `EFI` type is hybrid, it'll boot either BIOS or EFI. `UEFI` also adds Secure Boot support.

**Comment by bgeuken** [comment] 2018-02-23 07:22
Seems to be fixed now
=> closing

**Closed by bgeuken** 2018-02-23 07:22 UTC
Labels: 2.9, Appliance
