### ISSUE TITLE
GET /distributions/<distribution_id> returns <hash> not <status>

### ISSUE THREAD

**Issue by micrococo** [openSUSE/open-build-service#1589] opened 2016-02-28 16:20 UTC
Hi.

`api.txt` says that the XmlResult of `GET /distributions/<distribution_id>` is `<status>` but it is `<hash>`. Example: https://api.opensuse.org/distributions?format=xml

```
<?xml version="1.0" encoding="UTF-8"?>
<hash>
  <id type="integer">1366</id>
  <vendor>openSUSE</vendor>
  <version>Tumbleweed</version>
  <name>openSUSE Tumbleweed</name>
  <project>openSUSE:Factory</project>
  <reponame>openSUSE_Tumbleweed</reponame>
  <repository>snapshot</repository>
  <link>http://www.opensuse.org/</link>
  <architectures type="array">
    <architecture>i586</architecture>
    <architecture>x86_64</architecture>
  </architectures>
  <icons type="array">
    <icon>
      <id type="integer">1528</id>
      <url>https://static.opensuse.org/distributions/logos/opensuse-Factory-8.png</url>
      <width type="integer">8</width>
      <height type="integer">8</height>
    </icon>
    <icon>
      <id type="integer">1529</id>
      <url>https://static.opensuse.org/distributions/logos/opensuse-Factory-16.png</url>
      <width type="integer">16</width>
      <height type="integer">16</height>
    </icon>
  </icons>
</hash>
```

Greetings.

**Comment by eduardoj** [comment] 2022-09-06 14:11
Hi,

sorry, I couldn't reproduce the issue.

1. `GET /distributions` returns a list of distributions:
```xml
</distributions>
  <distribution vendor="Many" version="42.3" id="20">
    <name>AppImage</name>
    <project>OBS:AppImage</project>
    <reponame>AppImage</reponame>
    <repository>AppImage</repository>
    <link>http://www.appimage.org/</link>
    <icon url="https://static.opensuse.org/distributions/logos/opensuse.png" width="8" height="8"/>
    <icon url="https://static.opensuse.org/distributions/logos/opensuse.png" width="16" height="16"/>
    <architecture>x86_64</architecture>
  </distribution>
  [...]
</distributions>
```
2. `GET /distributions/20` returns one distribution:
```xml
<distribution vendor="Many" version="42.3" id="20">
  <name>AppImage</name>
  <project>OBS:AppImage</project>
  <reponame>AppImage</reponame>
  <repository>AppImage</repository>
  <link>http://www.appimage.org/</link>
  <icon url="https://static.opensuse.org/distributions/logos/opensuse.png" width="8" height="8"/>
  <icon url="https://static.opensuse.org/distributions/logos/opensuse.png" width="16" height="16"/>
  <architecture>x86_64</architecture>
</distribution>
```
3. Some other endpoints, like for example `POST /distributions/`, or `PUT /distributions/<distribution_id>`, return a `<status>` element.

The API documentation documents all these endpoints correctly. See https://build.opensuse.org/apidocs/index#8

This documentation can also be browsed and verified in the new API documentation: https://build.opensuse.org/apidocs-new/#/Distributions/get_distributions

I close the issue. Feel free to open it, if still happens.

**Closed by eduardoj** 2022-09-06 14:11 UTC
Labels: Bug, Documentation :book:
