### ISSUE TITLE
webui: unable to load build logs for repo names with %

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#12346] opened 2022-03-24 11:47 UTC
See https://build.opensuse.org/package/show/home:jengelh/test .

The build log for repository `st%2F..` has a href link of
`https://build.opensuse.org/package/live_build_log/home:jengelh/test/st%252F../x86_64` . Opening this causes a 302 redirect back to 
`https://build.opensuse.org/package/show/home:jengelh/test` (yields HTTP status 200) where then a red error box `There has been an internal error. Please try again.` is shown. Trying again does not fix the issue or provide a better message.

**Comment by hennevogel** [comment] 2022-03-24 12:04
Duplicate of #7021

**Closed by hennevogel** 2022-03-24 12:04 UTC
