### ISSUE TITLE
sequence errors when accepting a request

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#1554] opened 2016-02-17 14:57 UTC
Whenever somebody accepts an SR that was submitted with --cleanup (standard for branches) this triggers two emails instead of 1.

(the SR itself is updated with the states too, so the issue 'at hand' is not really the mailing, that's where it becomes visible to everybody and annoying)

- Request accepted (changes are checked in)
- Request revoked (source has been removed)

Sample SR: (#359992 )

State:   accepted   2016-02-17T14:46:03 Zaitor
Comment: Selfack

History: 2016-02-17T14:46:03 Zaitor       Request got accepted
         2016-02-17T14:46:03 Zaitor       Request got revoked
         2016-02-17T14:45:08 Zaitor       Request created

**Comment by hennevogel** [comment] 2016-02-18 10:40
Duplicate of #1504

**Closed by hennevogel** 2016-02-18 10:40 UTC
