### ISSUE TITLE
_multibuild hides build results in the web UI

### ISSUE THREAD

**Issue by Mailaender** [openSUSE/open-build-service#4018] opened 2017-10-15 08:53 UTC
I usually click on the built binaries on build.opensuse.org to lookup the requires/provides dependencies to spot robust things like `pkgconfig(foobar)` so I don't have redo all my packaging when someone decides to do drastic changes in Factory/Tumbleweed. For the new `_multibuild` feature those are hidden. :cry: See https://build.opensuse.org/package/show/devel:languages:lua/lua-BitOp for example.

**Comment by mmohring** [comment] 2017-10-15 15:02
I think what we see has noting to do with multibuild, but no build binaries are shown but the says they had been build, for example https://build.opensuse.org/package/binaries/devel:languages:lua/lua-BitOp:lua51?repository=openSUSE_Leap_42.3. If the packages are shown in the repository, then it also works for multibuild, see here: https://build.opensuse.org/package/show/OBS:Server:Unstable/obs-server .

**Comment by Mailaender** [comment] 2017-10-15 16:37
Haven't seen one so far. I find it pretty confusing that the binaries are shown for OBS:Server:Unstable/obs-server but not for lua-BitOp:lua51. Same in the openSUSE:Factory repository so I assume nothing is misconfigured in devel:languages:lua.

**Comment by mmohring** [comment] 2017-10-15 20:51
Could it be because the main package is "excluded". Then it would look to me like a bug.

**Comment by coolo** [comment] 2017-10-16 06:18
the binaries you see in obs-server are the ones of the obs-server.spec, aka no multibuild. You see the same binaries for all multibuild flavors - which are none for lua-BitOp.

**Comment by mmohring** [comment] 2017-10-16 07:08
@coolo anyway the question is if it is intended to be like that. At least its confusing. E.g. the logfile is for a different package than the shown packages. This "looks" like a bug.

**Comment by coolo** [comment] 2017-10-16 07:30
of course it's a bug - I'm just saying all your comments are just confusing because the bug as @Mailaender outlines is valid and reproducible :)

**Comment by mmohring** [comment] 2017-10-16 07:35
OK. Correct.

**Comment by DavidKang** [comment] 2019-11-27 13:36
I can access the binaries of the multibuild: https://build.opensuse.org/package/binaries/devel:languages:lua/lua-BitOp:lua51/openSUSE_Leap_15.0

Is this issue still valid?

**Comment by dmarcoux** [comment] 2020-02-26 13:58
As @DavidKang pointed out, this seems to be working now.

I'm closing this.

**Closed by dmarcoux** 2020-02-26 13:58 UTC
Labels: Bug :skull:, P3
