### ISSUE TITLE
[production][maintained_projects#index] Mysql2::Error: Unknown column 'projects.name' in 'where clause': SELECT COUNT(*) FROM `maintained...

### ISSUE THREAD

**Issue by danidoni** [openSUSE/open-build-service#8246] opened 2019-09-03 09:02 UTC
maintained_projects#index threw this 17 times
<pre>
Mysql2::Error: Unknown column &#39;projects.name&#39; in &#39;where clause&#39;: SELECT COUNT(*) FROM `maintained_projects` WHERE `maintained_projects`.`maintenance_project_id` = 43794 AND CAST(`projects`.`name` AS CHAR) LIKE &#39;%m%&#39;
</pre>
[https://build.opensuse.org/projects/openSUSE:Maintenance/maintained_projects.json?draw=2&amp;columns%5B0%5D%5Bdata%5D=name&amp;columns%5B0%5D%5Bname%5D=&amp;columns%5B0%5D%5Bsearchable%5D=true&amp;columns%5B0%5D%5Borderable%5D=true&amp;columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&amp;columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&amp;columns%5B1%5D%5Bdata%5D=actions&amp;columns%5B1%5D%5Bname%5D=&amp;columns%5B1%5D%5Bsearchable%5D=true&amp;columns%5B1%5D%5Borderable%5D=true&amp;columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&amp;columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&amp;order%5B0%5D%5Bcolumn%5D=0&amp;order%5B0%5D%5Bdir%5D=asc&amp;start=0&amp;length=10&amp;search%5Bvalue%5D=m&amp;search%5Bregex%5D=false&amp;_=1564763009389](https://build.opensuse.org/projects/openSUSE:Maintenance/maintained_projects.json?draw=2&amp;columns%5B0%5D%5Bdata%5D=name&amp;columns%5B0%5D%5Bname%5D=&amp;columns%5B0%5D%5Bsearchable%5D=true&amp;columns%5B0%5D%5Borderable%5D=true&amp;columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&amp;columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&amp;columns%5B1%5D%5Bdata%5D=actions&amp;columns%5B1%5D%5Bname%5D=&amp;columns%5B1%5D%5Bsearchable%5D=true&amp;columns%5B1%5D%5Borderable%5D=true&amp;columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&amp;columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&amp;order%5B0%5D%5Bcolumn%5D=0&amp;order%5B0%5D%5Bdir%5D=asc&amp;start=0&amp;length=10&amp;search%5Bvalue%5D=m&amp;search%5Bregex%5D=false&amp;_=1564763009389)"

[See this exception on Errbit](http://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5d446388315d6700168fefec)

**Comment by dmarcoux** [comment] 2019-09-03 09:17
This is a duplicate of #8242. They can be merged in Errbit.

**Closed by dmarcoux** 2019-09-03 09:17 UTC
Labels: Bug :skull:, Frontend
