### ISSUE TITLE
[production][package#branch] <status code="400">
  <summary>conflict in file libqt4.spec</summary>
</status>


### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#3683] opened 2017-08-28 11:24 UTC
package#branch threw this 0 times
<pre>
&lt;status code=&quot;400&quot;&gt;
  &lt;summary&gt;conflict in file libqt4.spec&lt;/summary&gt;
&lt;/status&gt;

</pre>
[https://build.opensuse.org/package/branch](https://build.opensuse.org/package/branch)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59a19c2abf5ad60011aef33b)

**Comment by mschnitzer** [comment] 2017-08-28 11:26
Why do we not catch this exception?

**Comment by hennevogel** [comment] 2017-08-31 13:43
Duplicate of #3684

**Closed by hennevogel** 2017-08-31 13:43 UTC
Labels: Bug, Frontend
