### ISSUE TITLE
[production][] Mysql2::Error: Field 'binary_arch' doesn't have a default value: INSERT INTO `binary_releases` (`...

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/open-build-service#4953] opened 2018-05-07 08:41 UTC
threw this 13 times
<pre>
Mysql2::Error: Field &#39;binary_arch&#39; doesn&#39;t have a default value: INSERT INTO `binary_releases` (`repository_id`, `release_package_id`, `binary_name`, `binary_version`, `binary_release`, `binary_disturl`, `binary_releasetime`) VALUES (1488791, 3077177, &#39;container:my_container-latest&#39;, &#39;0&#39;, &#39;0&#39;, &#39;obs://build.opensuse.org/SUSE:Templates:Images:SLE-15/containers/67c42a1213e7849860d65d5c04b0b655-SLE-15-Container&#39;, &#39;2018-05-04 15:26:50&#39;)
</pre>

~~[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5aec7bc2f143580006bd9ed1)~~

~~[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5af9919acb5eae000be3b2a7)~~

~~[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b191fbd75dd8d000c4e5aa6)~~

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5aa2e783ab2581001400b1b1)

**Comment by eduardoj** [comment] 2018-05-17 16:04
The exception is thrown in this [line](https://github.com/openSUSE/open-build-service/blob/a3bc82ff8d9a444688ed957e6729c911221c3685/src/api/app/models/binary_release.rb#L95).

`hash['binary_arch']` is always assigned in [line 45](https://github.com/openSUSE/open-build-service/blob/a3bc82ff8d9a444688ed957e6729c911221c3685/src/api/app/models/binary_release.rb#L45) with value of the `binaryarch` field of the results of a [notificationpayload call](https://github.com/openSUSE/open-build-service/blob/a3bc82ff8d9a444688ed957e6729c911221c3685/src/api/app/models/binary_release.rb#L23) to the backend.

So the problem seems to be that the notificationpayload call to the backend doesn't always return a set of binaries with the field `binaryarch` filled.

**Comment by hennevogel** [comment] 2018-05-22 09:56
The problem is people using the feature in #4439 which isn't merged...

**Comment by bgeuken** [comment] 2018-05-22 13:12
This happens a lot now. We should push for getting this addressed soon

**Comment by hennevogel** [comment] 2019-02-04 20:17
#4439 is merged by now

**Closed by hennevogel** 2019-02-04 20:17 UTC
Labels: Backend 🤖, Bug :skull:
