### ISSUE TITLE
Internal Server Error when opening a file using the web interface

### ISSUE THREAD

**Issue by tumic0** [openSUSE/open-build-service#5866] opened 2018-09-15 14:28 UTC
# Issue Description
I get a 500: Internal Server Error when trying to edit the gpxsee.changes file on build.opensuse.org

Expected Result
============
Working web editor, no server error

How to Reproduce
===============
https://build.opensuse.org/package/view_file/home:tumic:GPXSee/gpxsee/gpxsee.changes?expand=1

**Comment by tumic0** [comment] 2018-09-15 14:30
Other files seem to work, the issue is just with that single file.

**Comment by tumic0** [comment] 2018-09-15 17:11
And it only errors when I'm logged in. Looks like the error is caused by the server not being able to open the file for writing.

**Comment by hennevogel** [comment] 2018-09-19 08:34
See the utf8 issues

**Comment by tumic0** [comment] 2018-09-22 10:56
1.) The file can be updated using the _osc_ command line tool, so the issue is most probably not related to a file write problem.
2.) There are only ASCII characters in the file

Still getting the 500: Internal Server Error instead of the editor. As the *.changes files are quiet crucial and the most updated ones in a package, this makes OBS unusable for serious work from the browser...

**Comment by eduardoj** [comment] 2018-09-24 14:27
I branched your package and could not reproduce the error. I can edit that file and save whitout any issues.

@tumic0: Is this error still happening to you? Can you provide another example of a file in another package that throws the same error?

**Comment by tumic0** [comment] 2018-09-24 15:10
Yes, it still hapens. Changing the file (also its contents) using osc or delete/upload did also not help. If you want to know how a 500: Internal Server Error on OBS looks like, you can have a look at #5908. The error is the same although the reason will be different in this case (I guess it is the whitespace in the name)

**Comment by tumic0** [comment] 2018-09-24 15:16
https://build.opensuse.org/package/view_file/home:tumic:Hypercube/hypercube/hypercube.changes

The changes file of Hypercube also triggers the 500 Error (also only when I'm logged in).

**Comment by ChrisBr** [comment] 2018-09-24 15:30
Indeed we can now see an error in our error tracker:

It is already reported here, closing this one as the other one has more context:
https://github.com/openSUSE/open-build-service/issues/5872

**Closed by ChrisBr** 2018-09-24 15:30 UTC
Labels: Bug :skull:, Frontend 👻, P2
