### ISSUE TITLE
Blank diffs in submit requests for multiple packages

### ISSUE THREAD

**Issue by aaannz** [openSUSE/open-build-service#4697] opened 2018-03-21 09:54 UTC
Submit requests with multiple packages (created by creq -a submit .. -a submit ... ) shows proper diff only for first package. The rest packages have empty diffs until clicked on them. And even there, there are graphical glitches - line numbers are rendered over diff.

See https://build.suse.de/request/show/159791 - first package is fine, second and rest have blank space where diff should be.

This happens with Firefox 58.0.2

**Comment by DimStar77** [comment] 2018-03-21 22:05
Sounds familiar: #902

**Comment by ChrisBr** [comment] 2018-03-26 12:30
Sounds also like 
https://github.com/openSUSE/open-build-service/issues/4719

If you click into the blank space, it is rendered. Seems like the JS is broken!

**Comment by hennevogel** [comment] 2018-03-26 15:13
duplicate of #4719

**Closed by hennevogel** 2018-03-26 15:13 UTC

**Comment by adrianschroeter** [comment] 2018-05-02 10:58
![](https://github.trello.services/images/mini-trello-icon.png) [New card template](https://trello.com/c/UW3TcuoS/1408-new-card-template)

**Comment by bgeuken** [comment] 2018-05-02 12:24
![](https://github.trello.services/images/mini-trello-icon.png) [P10: JavaScript for multi requests completely broken](https://trello.com/c/0BUIqLCS/729-p10-javascript-for-multi-requests-completely-broken)
