### ISSUE TITLE
shifted name list in monitor view (firefox)

### ISSUE THREAD

**Issue by edogawa23** [openSUSE/open-build-service#13631] opened 2023-01-04 12:58 UTC
# Issue Description
Viewing any project's monitor page via Firefox in OBS (or PMBS), I get a table where the leftmost column is displayed somewhat shifted vertically upwards, the last two or three entries seem duplicated, and the whole column further moves a little bit on mousewheel scrolling, all of this obfuscates the relation between name and build result.

Expected Result
============
I'd expect to see a table with name entries matching the build results in the same line.

How to Reproduce
===============
1. Go to any project's Overview page using Firefox (version 108.0.1 here)
2. Click the Monitor Tab
3. See error

Further Information
===============
![Screenshot_20230104_135127](https://user-images.githubusercontent.com/20699214/210559858-1acc4e68-0be5-475c-afee-21499d5ced5b.png)

**Comment by dmarcoux** [comment] 2023-01-04 14:40
The current version of Firefox available on Tumbleweed could be anything, since this depends on when you last updated your repositories and computer. So what are you using?

**Comment by edogawa23** [comment] 2023-01-04 14:56
I said current Tumbleweed's Firefox, not current version of Firefox on my Tumbleweed... I thought that to be precise enough, or at least to indicate that I updated to current repos?
Anyways, it's version 108.0.1 (64-Bit) from OSS repo.

**Comment by luc14n0** [comment] 2023-01-06 05:44
I can confirm the same thing happening here. It used to not be an issue on the previous version of Firefox.

``` bash
$ rpm -q MozillaFirefox
MozillaFirefox-108.0.1-2.1.x86_64
```

**Comment by hennevogel** [comment] 2023-01-09 16:14
duplicate of #8859

**Closed by hennevogel** 2023-01-09 16:14 UTC
