### ISSUE TITLE
500: Internal Server Error when trying to access my notifications

### ISSUE THREAD

**Issue by badshah400** [openSUSE/open-build-service#14460] opened 2023-06-07 08:50 UTC
# Issue Description

For a couple of days now, I (user badshah400) see a `500: Internal Server Error` when trying to access my notifications on build.o.o, for example by clicking on the notifications (bell) icon at the top of the home page. I am signed into the beta features, but signing out of it does not help either.

Expected Result
============
Should be able to see my notifications.

How to Reproduce
===============
1. Go to <https://build.opensuse.org/my/notifications> when logged in.
2. See error: "500: Internal Server Error
Oooops, something went terribly wrong, our application crashed :-( We think it's best if you search if this issue is already reported on [GitHub](https://github.com/openSUSE/open-build-service/issues)."

**Comment by bmwiedemann** [comment] 2023-06-07 09:55
That could be #9424 we discussed today.

**Comment by saraycp** [comment] 2023-06-07 11:30
@badshah400 Can you confirm you can see your notifications again?

**Comment by badshah400** [comment] 2023-09-04 15:17
This has happened again. As of today, I cannot access my notifications, only getting a 500 error. Happened as soon as https://progress.opensuse.org/issues/135053 was resolved and the related comments, which were still in my list of unread notifications, were deleted.

**Comment by krauselukas** [comment] 2023-09-04 15:56
Can confirm, the exception occurs again https://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/64f5f7e084bf4606feacae7f

**Comment by krauselukas** [comment] 2023-09-04 15:58
I will have a look

**Comment by badshah400** [comment] 2023-09-05 16:01
@krauselukas Many thanks. I confirm that can access my notifications again.

**Comment by krauselukas** [comment] 2023-09-06 13:58
Nice to hear, alright I will close this issue then and open a new one to fix the cause of this problem

**Closed by krauselukas** 2023-09-06 13:58 UTC
Labels: Bug, Frontend
