### ISSUE TITLE
Tasks page shows incoming review counter albeit no reviews are incoming

### ISSUE THREAD

**Issue by dcermak** [openSUSE/open-build-service#11506] opened 2021-08-17 11:54 UTC
# Issue Description

I had an incoming review on OBS and accepted it. However the tasks icon still shows that there is one task left and that I have one review incoming. But no entry is actually present in the list:

![image](https://user-images.githubusercontent.com/45594031/129720899-36702fa7-e3bd-43cc-832e-8e6e3f0e45e9.png)

Force reloading the page via Ctrl+R does **not** fix the issue.

Expected Result
============
The task counter should be zero.

How to Reproduce
===============

This worked for me, cannot confirm how reproducible this is for others.

1. Accept an incoming review
2. Reload the tasks page
3. See that the task counter is still 1

**Comment by hennevogel** [comment] 2021-08-18 15:17
Duplicate of #8852

**Closed by hennevogel** 2021-08-18 15:17 UTC
