### ISSUE TITLE
[beta] links in linked projects point to package in parent project

### ISSUE THREAD

**Issue by ggardet** [openSUSE/open-build-service#6621] opened 2018-12-14 13:32 UTC
In beta webui, if you go to https://build.opensuse.org/project/show/openSUSE:Leap:15.1:ARM and click any package inherited from parent project, you will end up in package from ```openSUSE:Leap:15.1```, not ```openSUSE:Leap:15.1:ARM```. 
Which is wrong, as we should display this package in context of current project.

**Comment by ggardet** [comment] 2018-12-14 13:49
The same applies when I click on 'Branch package' link. It branches parent package instead of current package, so repos config in branched project is not right.

**Comment by Ana06** [comment] 2019-01-09 13:58
This seems to be fixed. I'll close the issue. Please reopen it if the issue is still there @ggardet :wink:

**Comment by coolo** [comment] 2019-01-09 14:41
@Ana06 go to https://build.opensuse.org/project/show/openSUSE:Leap:15.1:ARM -> 'Inherited Packages' -> 0ad and you end up in https://build.opensuse.org/package/show/openSUSE:Leap:15.1/0ad while the user expects to stay in :ARM

**Closed** 2019-01-24 15:21 UTC
Labels: Bootstrap :rocket:, Bug :skull:, Frontend 👻
