### ISSUE TITLE
diff detected, but not visible on multiaction diffs

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#680] opened 2014-05-26 13:09 UTC
In case a request has multiple submit actions, the webui shows tabs for each modified package/action. The following example has two modified packages, but when trying to extend the second one the diff looks empty. api is delivering the content and osc has no problems with it.

https://build.opensuse.org/request/show/235358

**Comment by Mailaender** [comment] 2015-11-09 19:48
Confirmed. This is still not resolved. https://build.opensuse.org/request/show/342552

![image](https://cloud.githubusercontent.com/assets/756669/11044598/301f0588-8723-11e5-9185-2b6d15842472.png)

**Comment by bgeuken** [comment] 2015-11-24 12:58
This sounds like a duplicate of #509 
I'll have a look at it

**Comment by mdeniz** [comment] 2017-11-06 12:24
Looks like this issue got fixed, if still valid please reopen, thanks.

**Closed by mdeniz** 2017-11-06 12:24 UTC
Labels: Bug, Frontend
