### ISSUE TITLE
Notification button: 'Mark all as read' should respect filter

### ISSUE THREAD

**Issue by lrupp** [openSUSE/open-build-service#12007] opened 2021-12-21 09:47 UTC
# Issue Description

When I'm in the notification page (https://build.suse.de/my/notifications?type=incoming_requests) and selected the incoming request queue, there is a "Mark all as read" button, in case the list of requests is very long.

Expected Result
============

I would expect that the "Mark all as read" button respects the current filter (as seen in the URL, I selected "type: incoming requests") and not mark *all* (incoming and outgoing) requests as read.

How to Reproduce
===============
1. Go to https://build.suse.de/my/notifications?type=incoming_requests and have some incoming and outgoing unread requests.
2. Click on 'Mark all as read' - you just see this button, if there are many (more than 200?) requests in unread state.
4. See that also the outgoing, unread requests get marked as 'read', even if you are in the incoming request queue.

**Comment by saraycp** [comment] 2021-12-22 16:26
So far, I've been able to reproduce the described problem with Group filters only.

Using the rest of the filters (Comments, Requests, Incoming Requests, Outgoing Requests, Projects) works fine for me in development environment, where I can generate any number of notifications I need to test this.

**Comment by saraycp** [comment] 2021-12-22 17:00
Well, there is a possibility to have the same notification listed in both `Incoming Requests` and `Outgoing Requests`.

![Screenshot from 2021-12-22 17-48-58](https://user-images.githubusercontent.com/2581944/147127556-e36863f0-2623-4718-9764-636324d30eaa.png)

Explanation: 

Admin user creates a request towards `package_scp`, so the corresponding notification is in Admin's `Outgoing Requests` list.

Moreover, `package_scp` is maintained by the group `Bella` and Admin belongs to that group. As Admin added the configuration to receive notifications to that group, Admin sees the same notification in the `Incoming Requests` list too.

Trying more use cases...

**Comment by saraycp** [comment] 2021-12-23 11:39
[This PR](https://github.com/openSUSE/open-build-service/pull/12015) fixes the issue with the Groups filter.

I still can't reproduce the issue with the request-related filters. @lrupp could you please check if what I explain in the [previous comment](https://github.com/openSUSE/open-build-service/issues/12007#issuecomment-999728160) is the reason why one notification disappears from both `Incoming Requests` and `Outgoing Requests` when you mark it as read? Would you expect a different behaviour?

**Comment by saraycp** [comment] 2022-01-13 10:52
@lrupp I'm going to close this issue. Please open a new one if you still find a problem with the filters or propose a different behaviour. Thanks for your feedback!

**Closed by saraycp** 2022-01-13 10:52 UTC
Labels: Bug, Frontend, Notifications

**Comment by lrupp** [comment] 2022-01-18 10:10
JFYI: I guess you are right with the assumption in [your 2nd comment](https://github.com/openSUSE/open-build-service/issues/12007#issuecomment-999728160): I was submitter and reviewer at the same time for the 'lost' requests. So - sad but true - it looks like I need again a split brain setup / multiple accounts for doing my daily duties here. Sorry for the noise.

**Comment by hennevogel** [comment] 2022-01-18 10:15
@lrupp which behavior would you expect instead?

**Comment by lrupp** [comment] 2022-01-19 19:40
> @lrupp which behavior would you expect instead?

As mentioned initially: I would expect that the "Mark all as read" button respects the current filter (as seen in the URL, I selected "type: incoming requests") and not mark all (incoming ***and*** outgoing) requests as read.
But I agree that this might be hard to achieve, if an incoming and outgoing request affects the same users. This would probably mean that you need to handle the queues completely differently.
