### ISSUE TITLE
Merged/Unmerged source view not available anymore

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#3035] opened 2017-04-25 13:50 UTC
Issue/Feature description
====================

@rjschwei reported that the "show merged/unmerged sources" button is not available anymore on an internal OBS instance.

While reproducing it on the test instance for this report I found out that this happens when you link to a remote instance. The sources of Robert were unchanged since 2 years so, it seems to be a regression when the link disappeared.

Expected result
============
The link should depend only on local _link file, no matter if the target is remote or not.

How to Reproduce
===============
https://build-test.opensuse.org/package/show/home:adrianSuSE/build
Is a package linking to remote instance, no link beside "Source Files" title

https://build-test.opensuse.org/package/show/home:adrianSuSE:branches:home:adrianSuSE/build?expand=1
Is a package with a link to local instance, it has the the "(show unmerged sources)" link beside "Source Files" title

**Comment by JanZerebecki** [comment] 2018-04-04 13:36
Duplicate of #3948?

**Comment by hennevogel** [comment] 2018-04-09 10:57
Duplicate of #673

**Closed by hennevogel** 2018-04-09 10:57 UTC
Labels: Bug :skull:, Frontend 👻, P3, Regression :smiling_imp:
