### ISSUE TITLE
/my/notifications: add "mark all read"

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#10114] opened 2020-09-03 06:34 UTC
https://build.opensuse.org/my/notifications?project=openSUSE%3AFactory

Due to membership in the `opensuse-review-team` group, I get a lot of notifications on that page, currently there are on the order of 4000 for me. Clicking the checkmarks individually feels silly; there should be a "Mark all read" button.

**Comment by saraycp** [comment] 2020-11-12 15:43
@jengelh we already implemented something that tries to solve the problem you mention.

The notifications page already contains a _Select all_ checkbox and you can _Mark as "Read"_ all the selected notifications. Moreover, you can click in the _Show all_ link before you do so to get more notifications per page and drop them all in one shot.

I'm going to close this issue, but feel free to let us know if you find some other issue.

**Closed by saraycp** 2020-11-12 15:43 UTC
Labels: Beta, Feature, Frontend, Notifications

**Comment by krop** [comment] 2020-11-12 16:19
> @jengelh we already implemented something that tries to solve the problem you mention.
> 
only partially.
by design, only 25 notifications are displayed by default. Show all only loads 300 notifications. When I last tried the new interface, I had more than 10k notifications.
I wonder how many notifications factory reviewers / maintainers have.

**Comment by jengelh** [comment] 2020-11-12 16:43
My average over the past 2 weeks is 135 per day.
