### ISSUE TITLE
[production][maintained_projects#index] Mysql2::Error: Unknown column 'projects.name' in 'where clause'

### ISSUE THREAD

**Issue by danidoni** [openSUSE/open-build-service#12806] opened 2022-07-14 07:47 UTC
[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/62cfc25184bf460547359847)
# Mysql2::Error: Unknown column &#39;projects.name&#39; in &#39;where clause&#39; #
### URL ###
[https://build.opensuse.org/projects/openSUSE:Maintenance/maintained_projects.json?draw=2&amp;columns%5B0%5D%5Bdata%5D=name&amp;columns%5B0%5D%5Bname%5D=&amp;columns%5B0%5D%5Bsearchable%5D=true&amp;columns%5B0%5D%5Borderable%5D=true&amp;columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&amp;columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&amp;columns%5B1%5D%5Bdata%5D=actions&amp;columns%5B1%5D%5Bname%5D=&amp;columns%5B1%5D%5Bsearchable%5D=false&amp;columns%5B1%5D%5Borderable%5D=false&amp;columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&amp;columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&amp;order%5B0%5D%5Bcolumn%5D=0&amp;order%5B0%5D%5Bdir%5D=asc&amp;start=0&amp;length=10&amp;search%5Bvalue%5D=1&amp;search%5Bregex%5D=false&amp;_=1657782844921](https://build.opensuse.org/projects/openSUSE:Maintenance/maintained_projects.json?draw=2&amp;columns%5B0%5D%5Bdata%5D=name&amp;columns%5B0%5D%5Bname%5D=&amp;columns%5B0%5D%5Bsearchable%5D=true&amp;columns%5B0%5D%5Borderable%5D=true&amp;columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&amp;columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&amp;columns%5B1%5D%5Bdata%5D=actions&amp;columns%5B1%5D%5Bname%5D=&amp;columns%5B1%5D%5Bsearchable%5D=false&amp;columns%5B1%5D%5Borderable%5D=false&amp;columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&amp;columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&amp;order%5B0%5D%5Bcolumn%5D=0&amp;order%5B0%5D%5Bdir%5D=asc&amp;start=0&amp;length=10&amp;search%5Bvalue%5D=1&amp;search%5Bregex%5D=false&amp;_=1657782844921)"
### Where ###
maintained_projects#index

### Occured ###
Jul 14  7:14am

### Similar ###
1

## Params ##
~~~
{
  &quot;_&quot; =&gt; &quot;1657782844921&quot;,
  &quot;action&quot; =&gt; &quot;index&quot;,
  &quot;columns&quot; =&gt; {
    &quot;0&quot; =&gt; {
      &quot;data&quot; =&gt; &quot;name&quot;,
      &quot;name&quot; =&gt; &quot;&quot;,
      &quot;orderable&quot; =&gt; &quot;true&quot;,
      &quot;search&quot; =&gt; {
        &quot;regex&quot; =&gt; &quot;false&quot;,
        &quot;value&quot; =&gt; &quot;&quot;
      },
      &quot;searchable&quot; =&gt; &quot;true&quot;
    },
    &quot;1&quot; =&gt; {
      &quot;data&quot; =&gt; &quot;actions&quot;,
      &quot;name&quot; =&gt; &quot;&quot;,
      &quot;orderable&quot; =&gt; &quot;false&quot;,
      &quot;search&quot; =&gt; {
        &quot;regex&quot; =&gt; &quot;false&quot;,
        &quot;value&quot; =&gt; &quot;&quot;
      },
      &quot;searchable&quot; =&gt; &quot;false&quot;
    }
  },
  &quot;controller&quot; =&gt; &quot;webui/projects/maintained_projects&quot;,
  &quot;draw&quot; =&gt; &quot;2&quot;,
  &quot;format&quot; =&gt; &quot;json&quot;,
  &quot;length&quot; =&gt; &quot;10&quot;,
  &quot;order&quot; =&gt; {
    &quot;0&quot; =&gt; {
      &quot;column&quot; =&gt; &quot;0&quot;,
      &quot;dir&quot; =&gt; &quot;asc&quot;
    }
  },
  &quot;project_name&quot; =&gt; &quot;openSUSE:Maintenance&quot;,
  &quot;search&quot; =&gt; {
    &quot;regex&quot; =&gt; &quot;false&quot;,
    &quot;value&quot; =&gt; &quot;1&quot;
  },
  &quot;start&quot; =&gt; &quot;0&quot;
}
~~~

## Session ##
~~~
{
  &quot;_csrf_token&quot; =&gt; &quot;9P5oA3ijFUabXJ0N3QHDQwq4qlJ-U4aMoHUJPCcgC2w=&quot;,
  &quot;session_id&quot; =&gt; &quot;6a2faf1d254011cfa93c0172d07b42ea&quot;
}
~~~

## Backtrace ##
~~~
148:  /GEM_ROOT/gems/mysql2-0.5.4/lib/mysql2/client.rb -> **_query**
148:  /GEM_ROOT/gems/mysql2-0.5.4/lib/mysql2/client.rb -> **block in query**
147:  /GEM_ROOT/gems/mysql2-0.5.4/lib/mysql2/client.rb -> **handle_interrupt**
147:  /GEM_ROOT/gems/mysql2-0.5.4/lib/mysql2/client.rb -> **query**
206:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb -> **block (2 levels) in execute**
48:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/dependencies/interlock.rb -> **block in permit_concurrent_loads**
187:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/concurrency/share_lock.rb -> **yield_shares**
47:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/dependencies/interlock.rb -> **permit_concurrent_loads**
205:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb -> **block in execute**
696:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract_adapter.rb -> **block (2 levels) in log**
26:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **block (2 levels) in synchronize**
25:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **handle_interrupt**
25:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **block in synchronize**
21:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **handle_interrupt**
21:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **synchronize**
695:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract_adapter.rb -> **block in log**
24:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/notifications/instrumenter.rb -> **instrument**
687:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract_adapter.rb -> **log**
204:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb -> **execute**
52:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/mysql/database_statements.rb -> **execute**
215:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb -> **execute_and_free**
57:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/mysql/database_statements.rb -> **exec_query**
532:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb -> **select**
69:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb -> **select_all**
101:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract/query_cache.rb -> **block in select_all**
118:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract/query_cache.rb -> **block in cache_sql**
26:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **block (2 levels) in synchronize**
25:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **handle_interrupt**
25:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **block in synchronize**
21:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **handle_interrupt**
21:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **synchronize**
109:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract/query_cache.rb -> **cache_sql**
101:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract/query_cache.rb -> **select_all**
12:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/mysql/database_statements.rb -> **select_all**
308:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/relation/calculations.rb -> **block in execute_simple_calculation**
861:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/relation.rb -> **skip_query_cache_if_necessary**
308:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/relation/calculations.rb -> **execute_simple_calculation**
269:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/relation/calculations.rb -> **perform_calculation**
144:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/relation/calculations.rb -> **calculate**
51:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/relation/calculations.rb -> **count**
124:  /GEM_ROOT/gems/ajax-datatables-rails-1.3.1/lib/ajax-datatables-rails/base.rb -> **records_filtered_count**
58:  /GEM_ROOT/gems/ajax-datatables-rails-1.3.1/lib/ajax-datatables-rails/base.rb -> **as_json**
35:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/json/encoding.rb -> **encode**
22:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/json/encoding.rb -> **encode**
43:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/core_ext/object/json.rb -> **to_json**
157:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal/renderers.rb -> **block in &lt;module:Renderers&gt;**
150:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal/renderers.rb -> **block in _render_to_body_with_renderer**
511:  /usr/lib64/ruby/3.1.0/set.rb -> **each_key**
511:  /usr/lib64/ruby/3.1.0/set.rb -> **each**
146:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal/renderers.rb -> **_render_to_body_with_renderer**
142:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal/renderers.rb -> **render_to_body**
25:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/abstract_controller/rendering.rb -> **render**
36:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal/rendering.rb -> **render**
46:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal/instrumentation.rb -> **block (2 levels) in render**
311:  /usr/lib64/ruby/3.1.0/benchmark.rb -> **realtime**
14:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/core_ext/benchmark.rb -> **ms**
46:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal/instrumentation.rb -> **block in render**
86:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal/instrumentation.rb -> **cleanup_view_runtime**
34:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/railties/controller_runtime.rb -> **cleanup_view_runtime**
45:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal/instrumentation.rb -> **render**
12:  app/controllers/webui/projects/maintained_projects_controller.rb -> **block (2 levels) in index**
214:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal/mime_responds.rb -> **respond_to**
9:  app/controllers/webui/projects/maintained_projects_controller.rb -> **index**
6:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal/basic_implicit_render.rb -> **send_action**
228:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/abstract_controller/base.rb -> **process_action**
30:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal/rendering.rb -> **process_action**
42:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/abstract_controller/callbacks.rb -> **block in process_action**
106:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **run_callbacks**
41:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/abstract_controller/callbacks.rb -> **process_action**
22:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal/rescue.rb -> **process_action**
34:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal/instrumentation.rb -> **block in process_action**
203:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/notifications/instrumenter.rb -> **instrument**
203:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/notifications.rb -> **instrument**
33:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal/instrumentation.rb -> **process_action**
249:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal/params_wrapper.rb -> **process_action**
27:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/railties/controller_runtime.rb -> **process_action**
165:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/abstract_controller/base.rb -> **process**
39:  /GEM_ROOT/gems/actionview-6.1.5.1/lib/action_view/rendering.rb -> **process**
190:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal.rb -> **dispatch**
254:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal.rb -> **dispatch**
50:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/routing/route_set.rb -> **dispatch**
33:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/routing/route_set.rb -> **serve**
19:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/routing/mapper.rb -> **block in &lt;class:Constraints&gt;**
49:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/routing/mapper.rb -> **serve**
50:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/journey/router.rb -> **block in serve**
32:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/journey/router.rb -> **each**
32:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/journey/router.rb -> **serve**
842:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/routing/route_set.rb -> **call**
72:  /GEM_ROOT/gems/flipper-0.25.0/lib/flipper/middleware/memoizer.rb -> **memoized_call**
37:  /GEM_ROOT/gems/flipper-0.25.0/lib/flipper/middleware/memoizer.rb -> **call**
37:  config/initializers/wrap_parameters.rb -> **call**
44:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/deflater.rb -> **call**
15:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/tempfile_reaper.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/etag.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/conditional_get.rb -> **call**
12:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/head.rb -> **call**
22:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/http/permissions_policy.rb -> **call**
19:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/http/content_security_policy.rb -> **call**
266:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/session/abstract/id.rb -> **context**
260:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/session/abstract/id.rb -> **call**
689:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/cookies.rb -> **call**
27:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/callbacks.rb -> **block in call**
98:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **run_callbacks**
26:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/callbacks.rb -> **call**
18:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/actionable_exceptions.rb -> **call**
32:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call!**
21:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call**
29:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/debug_exceptions.rb -> **call**
33:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/show_exceptions.rb -> **call**
18:  /GEM_ROOT/gems/lograge-0.12.0/lib/lograge/rails_ext/rack/logger.rb -> **call_app**
26:  /GEM_ROOT/gems/railties-6.1.5.1/lib/rails/rack/logger.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/tagged_logging.rb -> **block in tagged**
37:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/tagged_logging.rb -> **tagged**
99:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/tagged_logging.rb -> **tagged**
26:  /GEM_ROOT/gems/railties-6.1.5.1/lib/rails/rack/logger.rb -> **call**
81:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/remote_ip.rb -> **call**
81:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/remote_ip.rb -> **call**
19:  /GEM_ROOT/gems/request_store-1.5.1/lib/request_store/middleware.rb -> **call**
26:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/request_id.rb -> **call**
24:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/method_override.rb -> **call**
22:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/runtime.rb -> **call**
29:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/cache/strategy/local_cache_middleware.rb -> **call**
14:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/executor.rb -> **call**
18:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/lock.rb -> **call**
110:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/sendfile.rb -> **call**
142:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/host_authorization.rb -> **call**
539:  /GEM_ROOT/gems/railties-6.1.5.1/lib/rails/engine.rb -> **call**
207:  /GEM_ROOT/gems/railties-6.1.5.1/lib/rails/railtie.rb -> **public_send**
207:  /GEM_ROOT/gems/railties-6.1.5.1/lib/rails/railtie.rb -> **method_missing**
74:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/urlmap.rb -> **block in call**
58:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/urlmap.rb -> **each**
58:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/urlmap.rb -> **call**
107:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb -> **process_request**
149:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **accept_and_process_next_request**
110:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **main_loop**
419:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/request_handler.rb -> **block (3 levels) in start_threads**
113:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/utils.rb -> **block in create_thread_and_abort_on_exception**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| program_name | Passenger RubyApp: /srv/www/obs/api (production) |
| HTTP_USER_AGENT | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 Edg/103.0.1264.49 |

**Comment by eduardoj** [comment] 2023-01-12 13:48
Duplicate of #8242. Closing.

**Closed by eduardoj** 2023-01-12 13:48 UTC
Labels: Bug, Frontend
