### ISSUE TITLE
[bootstrap][mobile] Top right menu items are too close

### ISSUE THREAD

**Issue by saraycp** [openSUSE/open-build-service#5988] opened 2018-10-02 08:48 UTC
# Issue Description
Top right menu items (_username Tasks Home  ..._) are too close in small screens (phone)

![bootstrap_menu](https://user-images.githubusercontent.com/2581944/46338170-bce9c680-c62f-11e8-805c-3f2623d0e2ad.png)

How to Reproduce
===============
1. Go to 'https://build.opensuse.org'
2. Join to beta program
3. Click on the menu icon on the top right corner

**Comment by ChrisBr** [comment] 2018-10-02 09:02
Duplicate of https://github.com/openSUSE/open-build-service/issues/5977

**Closed by ChrisBr** 2018-10-02 09:02 UTC
Labels: Bootstrap :rocket:, Bug :skull:, Frontend 👻
