### ISSUE TITLE
WEBUI: isnt possible show package with dot in name

### ISSUE THREAD

**Issue by mimi1vx** [openSUSE/open-build-service#2900] opened 2017-03-24 12:05 UTC
Issue/Feature description
====================
for example inst possible open page with : https://build.opensuse.org/package/show/openSUSE:Factory/python-ruamel.yaml

Expected result
============
open package page with list of fileas and other info

How to Reproduce
===============
try open https://build.opensuse.org/package/show/openSUSE:Factory/python-ruamel.yaml

Further information
===============
* A link to an OBS instance showing the issue
* Exact server version (in case a private instance is used)

**Comment by bgeuken** [comment] 2017-03-27 06:58
As Adrian mentioned in the other bug, this might be caused by the kind of suffix, eg [.rb](https://build.opensuse.org/package/show/devel:languages:ruby:extensions/rubygem-pygments.rb) doesn't cause any problem.

**Comment by adrianschroeter** [comment] 2017-04-25 06:13
JFYI, there is a also a bugzilla entry for this, closing that one now and reference here:

 https://bugzilla.suse.com/show_bug.cgi?id=1035811

**Comment by Ana06** [comment] 2017-04-25 16:33
projects are also affected

**Comment by toddrme2178** [comment] 2017-04-25 18:41
It is definitely related to the suffix. It seemed to be related to some particular name patterns that mimic particular extensions.  So a name ending in `.yaml` or `.text` caused problems but not `.py`, for example.

**Closed** 2017-05-04 12:28 UTC
Labels: Bug, frontend, P2
