### ISSUE TITLE
Package has no source revision yet

### ISSUE THREAD

**Issue by mfatrez** [openSUSE/open-build-service#15452] opened 2024-01-08 10:28 UTC
Creating a new (kiwi) image from OBS web ui give the error : "Package has no source revision yet"

Expected Result
============
A fully functionnal kiwi repository

How to Reproduce
===============
once logged, in "Your Home Project", click "New Image", select "openSUSE Tumbleweed Minimal Images", name your appliance and cick "Create Appliance".
After this, a repo should be created but intstead the error "Package has no source revision yet" is raised

**Comment by eduardoj** [comment] 2024-01-08 10:58
Confirmed.

**Comment by Vogtinator** [comment] 2024-01-24 15:12
Looks like adrian fixed that already

**Comment by eduardoj** [comment] 2024-01-24 15:28
> Looks like adrian fixed that already

Confirmed that it works again. Thanks for checking it! Closing.

**Closed by eduardoj** 2024-01-24 15:28 UTC
Labels: Bug, Frontend

**Comment by rifux** [comment] 2025-01-03 19:50
**It seems that it happened again**

Steps to reproduce:
1. Log in to https://build.opensuse.org
2. Go to https://studioexpress.opensuse.org and click on the link https://build.opensuse.org/image_templates to create a kiwi repo
3. Select "openSUSE Tumbleweed Minimal Images", then "Create appliance"

![image](https://github.com/user-attachments/assets/b6052020-52e3-451a-a9f1-693845193879)
