### ISSUE TITLE
Uncaught exception: Package is used by following packages as devel package: home:xxx/zzz, home:aaa/bbb

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#4431] opened 2018-02-01 08:40 UTC
When trying to delete a devel package that has dependencies, the following exception is raised:

```
Package is used by following packages as devel package: home:xxx/zzz, home:aaa/bbb
```

This exception is not caught and will add an entry to errbit. We should handle it properly.

See: https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5a4b8dac8467cd0006c7479a

**Comment by hennevogel** [comment] 2018-02-28 13:45
duplicate of #4081

**Closed by hennevogel** 2018-02-28 13:45 UTC
Labels: Bug, Frontend, PR welcome, junior
