### ISSUE TITLE
[production][delayed_job#ProjectDoProjectReleaseJob] No permission to modify project 'openSUSE:Leap:15.0:Ports:ToTest' for user 'kstreitova'

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/open-build-service#4240] opened 2017-12-18 09:02 UTC
delayed_job#ProjectDoProjectReleaseJob threw this 0 times
<pre>
No permission to modify project &#39;openSUSE:Leap:15.0:Ports:ToTest&#39; for user &#39;kstreitova&#39;
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5a36272847fd36000635ad72)

**Comment by hennevogel** [comment] 2018-02-28 12:12
duplicate of #4102

**Closed by hennevogel** 2018-02-28 12:12 UTC
Labels: Bug, PR welcome
