### ISSUE TITLE
[production][image_templates#index] Mysql2::Error: Duplicate entry 'nnnnnoooooooo' for key 'users_login_index'

### ISSUE THREAD

**Issue by danidoni** [openSUSE/open-build-service#13137] opened 2022-09-26 19:34 UTC
[See this exception on Errbit](http://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/632ea28e84bf46052a43c5d5)
# Mysql2::Error: Duplicate entry &#39;nnnnnoooooooo&#39; for key &#39;users_login_index&#39; #
### URL ###
[https://build.opensuse.org/image_templates](https://build.opensuse.org/image_templates)"
### Where ###
image_templates#index

### Occured ###
Sep 24  6:24am

### Similar ###
0

## Params ##
~~~
{
  &quot;action&quot; =&gt; &quot;index&quot;,
  &quot;controller&quot; =&gt; &quot;webui/image_templates&quot;
}
~~~

## Session ##
~~~
{
  &quot;_csrf_token&quot; =&gt; &quot;QrrpRcDrH7qIYRvEA718-NRUXV4kYFAG26mZPMdyayI=&quot;,
  &quot;session_id&quot; =&gt; &quot;b372f345ea320bf12415c1d5d75e902d&quot;
}
~~~

## Backtrace ##
~~~
148:  /GEM_ROOT/gems/mysql2-0.5.4/lib/mysql2/client.rb -> **_query**
148:  /GEM_ROOT/gems/mysql2-0.5.4/lib/mysql2/client.rb -> **block in query**
147:  /GEM_ROOT/gems/mysql2-0.5.4/lib/mysql2/client.rb -> **handle_interrupt**
147:  /GEM_ROOT/gems/mysql2-0.5.4/lib/mysql2/client.rb -> **query**
206:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb -> **block (2 levels) in execute**
48:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/dependencies/interlock.rb -> **block in permit_concurrent_loads**
187:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/concurrency/share_lock.rb -> **yield_shares**
47:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/dependencies/interlock.rb -> **permit_concurrent_loads**
205:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb -> **block in execute**
696:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract_adapter.rb -> **block (2 levels) in log**
26:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **block (2 levels) in synchronize**
25:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **handle_interrupt**
25:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **block in synchronize**
21:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **handle_interrupt**
21:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **synchronize**
695:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract_adapter.rb -> **block in log**
24:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/notifications/instrumenter.rb -> **instrument**
687:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract_adapter.rb -> **log**
204:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb -> **execute**
52:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/mysql/database_statements.rb -> **execute**
215:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb -> **execute_and_free**
57:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/mysql/database_statements.rb -> **exec_query**
136:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb -> **exec_insert**
171:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb -> **insert**
22:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract/query_cache.rb -> **insert**
375:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/persistence.rb -> **_insert_record**
929:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/persistence.rb -> **_create_record**
166:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/counter_cache.rb -> **_create_record**
79:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/locking/optimistic.rb -> **_create_record**
201:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/attribute_methods/dirty.rb -> **_create_record**
461:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/callbacks.rb -> **block in _create_record**
106:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **run_callbacks**
20:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rails/active_record.rb -> **run_callbacks**
824:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **_run_create_callbacks**
461:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/callbacks.rb -> **_create_record**
108:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/timestamp.rb -> **_create_record**
900:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/persistence.rb -> **create_or_update**
457:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/callbacks.rb -> **block in create_or_update**
117:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **block in run_callbacks**
385:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/autosave_association.rb -> **around_save_collection_association**
126:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **block in run_callbacks**
137:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **run_callbacks**
20:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rails/active_record.rb -> **run_callbacks**
824:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **_run_save_callbacks**
457:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/callbacks.rb -> **create_or_update**
126:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/timestamp.rb -> **create_or_update**
507:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/persistence.rb -> **save!**
53:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/validations.rb -> **save!**
302:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/transactions.rb -> **block in save!**
354:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/transactions.rb -> **block in with_transaction_returning_status**
320:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb -> **block in transaction**
319:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract/transaction.rb -> **block in within_new_transaction**
26:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **block (2 levels) in synchronize**
25:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **handle_interrupt**
25:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **block in synchronize**
21:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **handle_interrupt**
21:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb -> **synchronize**
317:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract/transaction.rb -> **within_new_transaction**
320:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb -> **transaction**
350:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/transactions.rb -> **with_transaction_returning_status**
302:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/transactions.rb -> **save!**
48:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/suppressor.rb -> **save!**
55:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/persistence.rb -> **create!**
172:  app/models/user.rb -> **create_user_with_fake_pw!**
40:  app/services/webui_controller_service/user_checker.rb -> **find_or_create_user!**
20:  app/services/webui_controller_service/user_checker.rb -> **call**
103:  app/controllers/webui/webui_controller.rb -> **check_user**
427:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **block in make_lambda**
198:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **block (2 levels) in halting**
34:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/abstract_controller/callbacks.rb -> **block (2 levels) in &lt;module:Callbacks&gt;**
199:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **block in halting**
512:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **block in invoke_before**
512:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **each**
512:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **invoke_before**
105:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **run_callbacks**
41:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/abstract_controller/callbacks.rb -> **process_action**
22:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal/rescue.rb -> **process_action**
34:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal/instrumentation.rb -> **block in process_action**
203:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/notifications.rb -> **block in instrument**
24:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/notifications/instrumenter.rb -> **instrument**
203:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/notifications.rb -> **instrument**
33:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal/instrumentation.rb -> **process_action**
249:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal/params_wrapper.rb -> **process_action**
27:  /GEM_ROOT/gems/activerecord-6.1.5.1/lib/active_record/railties/controller_runtime.rb -> **process_action**
165:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/abstract_controller/base.rb -> **process**
39:  /GEM_ROOT/gems/actionview-6.1.5.1/lib/action_view/rendering.rb -> **process**
190:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal.rb -> **dispatch**
254:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_controller/metal.rb -> **dispatch**
50:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/routing/route_set.rb -> **dispatch**
33:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/routing/route_set.rb -> **serve**
19:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/routing/mapper.rb -> **block in &lt;class:Constraints&gt;**
49:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/routing/mapper.rb -> **serve**
50:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/journey/router.rb -> **block in serve**
32:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/journey/router.rb -> **each**
32:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/journey/router.rb -> **serve**
842:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/routing/route_set.rb -> **call**
72:  /GEM_ROOT/gems/flipper-0.25.2/lib/flipper/middleware/memoizer.rb -> **memoized_call**
37:  /GEM_ROOT/gems/flipper-0.25.2/lib/flipper/middleware/memoizer.rb -> **call**
15:  config/initializers/prefer_xml_over_html.rb -> **call**
44:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/deflater.rb -> **call**
15:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/tempfile_reaper.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/etag.rb -> **call**
27:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/conditional_get.rb -> **call**
12:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/head.rb -> **call**
22:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/http/permissions_policy.rb -> **call**
19:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/http/content_security_policy.rb -> **call**
266:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/session/abstract/id.rb -> **context**
260:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/session/abstract/id.rb -> **call**
689:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/cookies.rb -> **call**
27:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/callbacks.rb -> **block in call**
98:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/callbacks.rb -> **run_callbacks**
26:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/callbacks.rb -> **call**
18:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/actionable_exceptions.rb -> **call**
32:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call!**
21:  /GEM_ROOT/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb -> **call**
29:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/debug_exceptions.rb -> **call**
33:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/show_exceptions.rb -> **call**
18:  /GEM_ROOT/gems/lograge-0.12.0/lib/lograge/rails_ext/rack/logger.rb -> **call_app**
26:  /GEM_ROOT/gems/railties-6.1.5.1/lib/rails/rack/logger.rb -> **block in call**
99:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/tagged_logging.rb -> **block in tagged**
37:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/tagged_logging.rb -> **tagged**
99:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/tagged_logging.rb -> **tagged**
26:  /GEM_ROOT/gems/railties-6.1.5.1/lib/rails/rack/logger.rb -> **call**
81:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/remote_ip.rb -> **call**
81:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/remote_ip.rb -> **call**
19:  /GEM_ROOT/gems/request_store-1.5.1/lib/request_store/middleware.rb -> **call**
26:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/request_id.rb -> **call**
24:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/method_override.rb -> **call**
22:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/runtime.rb -> **call**
29:  /GEM_ROOT/gems/activesupport-6.1.5.1/lib/active_support/cache/strategy/local_cache_middleware.rb -> **call**
14:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/executor.rb -> **call**
18:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/lock.rb -> **call**
110:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/sendfile.rb -> **call**
142:  /GEM_ROOT/gems/actionpack-6.1.5.1/lib/action_dispatch/middleware/host_authorization.rb -> **call**
539:  /GEM_ROOT/gems/railties-6.1.5.1/lib/rails/engine.rb -> **call**
207:  /GEM_ROOT/gems/railties-6.1.5.1/lib/rails/railtie.rb -> **public_send**
207:  /GEM_ROOT/gems/railties-6.1.5.1/lib/rails/railtie.rb -> **method_missing**
74:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/urlmap.rb -> **block in call**
58:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/urlmap.rb -> **each**
58:  /GEM_ROOT/gems/rack-2.2.4/lib/rack/urlmap.rb -> **call**
107:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb -> **process_request**
149:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **accept_and_process_next_request**
110:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb -> **main_loop**
419:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/request_handler.rb -> **block (3 levels) in start_threads**
113:  /usr/lib64/ruby/gems/3.1.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/utils.rb -> **block in create_thread_and_abort_on_exception**
~~~

## Environment ##
| Key        | Value      |
|------------|------------|
| program_name | Passenger RubyApp: /srv/www/obs/api (production) |
| HTTP_USER_AGENT | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.50 |

**Comment by eduardoj** [comment] 2022-09-27 05:13
Duplicate of #5513. Closing.

**Closed by eduardoj** 2022-09-27 05:13 UTC
Labels: Bug, Frontend
