### ISSUE TITLE
Patching special files

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#3739] opened 2017-09-01 08:44 UTC
This is broken for at least `_service` files but I suspect it's true for all special files. We validate the content of those files when you upload them. Apparently we don't validate those files when we patch them. 

## How to reproduce
1. create home:blah/service_test
2. osc linkpac home:blah service_test home:blah service_test2
3. apply a custom patch to service_test2 removing the content of the `_service` file
4. osc copypac -e home:blah service_test2 home:blah service_test3

## Results
home:blah service_test3 has an empty service file

## Expected Results
Somebody validates the `_service` file and tells the user that this is not possible

**Comment by eduardoj** [comment] 2018-07-20 09:35
This [exception](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59a91a376180760006d021b2) in Errbit links here to this issue.

Also #4007 was created from Errbit to handle the same exception.

Should we keep both github issues to track the same Errbit exception?

**Comment by hennevogel** [comment] 2018-07-20 12:36
> Should we keep both github issues to track the same Errbit exception?

Why would we?

**Comment by eduardoj** [comment] 2018-07-20 12:42
@hennevogel 

> Why would we?

They provide different information.

Are you fine with closing one of them, and copying the info that provides into the other one?

**Comment by hennevogel** [comment] 2018-07-20 13:23
Sure

**Comment by eduardoj** [comment] 2018-07-20 13:53
Moving content and closing. Duplicate of #4007.

**Closed by eduardoj** 2018-07-20 13:53 UTC
Labels: Backend 🤖, Bug :skull:
