### ISSUE TITLE
Wrong redirection after branching from openSUSE:Factory

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#1421] opened 2015-12-02 12:30 UTC
Hi,

I tried to branch `rubygem-nokogiri` from `openSUSE:Factory` and (I already branched the devel project of it `devel:languages:ruby:extensions rubygem-nokogiri`) then I clicked the `OK` button. After that I got redirected to https://build.opensuse.org/package/show/home:mschnitzer:branches:openSUSE:Factory/rubygem-nokogiri (error 404) but thats actually wrong because it was not able branch it. Maybe there is a check needed if the user already has branched the devel project.

**Comment by bgeuken** [comment] 2015-12-02 12:40
Your package can be found here: https://build.opensuse.org/package/show/home:mschnitzer:branches:devel:languages:ruby:extensions/rubygem-nokogiri

This is a duplicate of #1402. The code already got deployed. Please reopen if you still be able to reproduce this.

**Closed by bgeuken** 2015-12-02 12:40 UTC
