### ISSUE TITLE
another backend test failure on CentOS

### ISSUE THREAD

**Issue by k0da** [openSUSE/open-build-service#2427] opened 2016-12-06 09:04 UTC
Even prove says all tests are passed, test still fails due to 
[   82s] t/data/0015/events/x86_64/package:project-name::test-package-name: No such file or directory at t/0015-BSSched-EventSource-Directory.t line 260.
[   82s] # Looks like your test exited with 2 just after 16.

'''
[   82s] t/0014-BSSched-EventHandler.t .............. 
[   82s] 1..1
[   82s] ok 1 - use BSSched::EventHandler;
[   82s] ok
[   82s] t/data/0015/events/x86_64/package:project-name::test-package-name: No such file or directory at t/0015-BSSched-EventSource-Directory.t line 260.
[   82s] # Looks like your test exited with 2 just after 16.
[   82s] t/0015-BSSched-EventSource-Directory.t ..... 
[   82s] 1..16
[   82s] ok 1 - use BSSched::EventSource::Directory;
[   82s] ok 2 - Checking sendevent for x86_64
[   82s] ok 3 - Checking sendevent for i586
[   82s] ok 4 - Checking error message for broken xml
[   82s] ok 5 - Checking readevents (arch: x86_64)
[   82s] ok 6 - Checking if broken file was delete
[   82s] ok 7 - Checking readevents (arch: i586)
[   82s] ok 8 - Checking ping for x86_64
[   82s] ok 9 - Checking ping for i586
[   82s] ok 10 - Checking sendevent for broken_ping_arch
[   82s] ok 11 - Checking sendevent for broken_ping_arch with overlength event name
[   82s] ok 12 - Checking sendrepochangeevent without type
[   82s] ok 13 - Checking sendrepochangeevent
[   82s] ok 14 - Checking sendunblockedevent
[   82s] ok 15 - Checking sendpublishevent
[   82s] ok 16 - Checking sendimportevent
[   82s] Dubious, test returned 2 (wstat 512, 0x200)
[   82s] All 16 subtests passed 
'''

**Comment by lethliel** [comment] 2016-12-06 09:45
It is not the testcases that are failing. It is the cleanup that fails. The test should create a file **package:project-name::test-package-name**
In the end the file will get deleted. But that doesn't work in your case, because the file cannot be found.

**Comment by lethliel** [comment] 2016-12-06 10:05
can you execute the test with perl directly and paste the output?

**Comment by k0da** [comment] 2016-12-06 15:17
```
-bash-4.2$ perl t/0015-BSSched-EventSource-Directory.t 
1..16
ok 1 - use BSSched::EventSource::Directory;
ok 2 - Checking sendevent for x86_64
ok 3 - Checking sendevent for i586
ok 4 - Checking error message for broken xml
not ok 5 - Checking readevents (arch: x86_64)
#   Failed test 'Checking readevents (arch: x86_64)'
#   at t/0015-BSSched-EventSource-Directory.t line 118.
#     Structures begin differing at:
#          $got->[1]{project} = Does not exist
#     $expected->[1]{project} = 'devel:languages:perl:CPAN-S'
ok 6 - Checking if broken file was delete
ok 7 - Checking readevents (arch: i586)
ok 8 - Checking ping for x86_64
ok 9 - Checking ping for i586
ok 10 - Checking sendevent for broken_ping_arch
ok 11 - Checking sendevent for broken_ping_arch with overlength event name
ok 12 - Checking sendrepochangeevent without type
ok 13 - Checking sendrepochangeevent
ok 14 - Checking sendunblockedevent
ok 15 - Checking sendpublishevent
ok 16 - Checking sendimportevent
t/data/0015/events/x86_64/package:project-name::test-package-name: No such file or directory at t/0015-BSSched-EventSource-Directory.t line 260.
# Looks like you failed 1 test of 16.
# Looks like your test exited with 2 just after 16.
```
@lethliel

**Comment by lethliel** [comment] 2016-12-07 07:53
looks like you are missing some data files for the tests. 
can you provide the output of 

```
find t/data/0015/events/x86_64/
```

The problem is, that i cannot reproduce your error.

**Comment by k0da** [comment] 2016-12-07 08:21
```
t/data/0015/events/x86_64/
t/data/0015/events/x86_64/.hidden_file
t/data/0015/events/x86_64/finished:devel:languages:perl:CPAN-P::openSUSE_Tumbleweed::perl-perlbench-1c7e973409998f482ce9dba10304e653
t/data/0015/events/x86_64/package:devel:languages:perl::perl-Unknown-Type
t/data/0015/events/x86_64/package:devel:languages:perl:CPAN-S::perl-SWISH
t/data/0015/events/x86_64/package:devel:languages:perl:CPAN-S::perl-Scalar-Boolean
t/data/0015/events/x86_64/package:devel:languages:perl:CPAN-S::perl-ScatterPlot
t/data/0015/events/x86_64/.ping
t/data/0015/events/x86_64/unblocked::devel:languages:perl::openSUSE_Leap_42.1
t/data/0015/events/x86_64/import.my_great_jobname
```

**Comment by k0da** [comment] 2016-12-07 08:21
to reproduce checkout home:k0da:rh-obs/obs-api-deps
uncoment make src/backend test in obs-server.spec
run osc build obs-server.spec

**Comment by lethliel** [comment] 2016-12-07 09:53
mhh. I see. It is really strange. I tested your sources in my machines (openSuSE 42.1 / Tumbleweed) and the tests run fine. 

So no problem with the test suite itself. (but in combination with CentOS)
You can apply this patch to remove the cleanup. Then it works.

[patch.zip](https://github.com/openSUSE/open-build-service/files/636241/patch.zip)

It is not the best solution, but it is the best i can do in short time. (since CentOS is not officially supported)

**Comment by lethliel** [comment] 2016-12-08 15:56
so i close this

**Closed by lethliel** 2016-12-08 15:56 UTC
Labels: backend
