### ISSUE TITLE
Inconsistent API behavior when using `deleted=0`

### ISSUE THREAD

**Issue by boiko** [openSUSE/open-build-service#12925] opened 2022-08-09 17:35 UTC
# Issue Description
The API endpoint that list project contents has an inconsistent behavior when explicitly passing `deleted=0` if the project has multibuild packages, see this example:
```
> osc api /source/devel:languages:python:Factory | grep python36
  <entry name="python36"/>
```

Now if I append `deleted=0`  to the arguments, the API endpoint lists also multibuild variants:
```
> osc api /source/devel:languages:python:Factory?deleted=0 | grep python36
  <entry name="python36"/>
  <entry name="python36:base" originpackage="python36"/>
  <entry name="python36:doc" originpackage="python36"/>
```

Expected Result
============
Setting `deleted=0` should not change the behavior or the API endpoint and return the same results as if the argument was not passed at all.

**Comment by crazyscientist** [comment] 2022-08-10 07:23
@boiko Thanks for noticing, but this is a duplicate of #9715 :wink:

**Closed** 2022-08-10 08:12 UTC
