### ISSUE TITLE
[production][] Mysql2::Error: Data too long for column 'event_payload' at row 1: INSERT INTO `notifications` (`t...

### ISSUE THREAD

**Issue by Ana06** [openSUSE/open-build-service#4319] opened 2018-01-10 08:42 UTC
threw this 0 times
<pre>
Mysql2::Error: Data too long for column &#39;event_payload&#39; at row 1: INSERT INTO `notifications` (`type`, `event_type`, `event_payload`, `subscription_receiver_role`, `created_at`, `updated_at`, `subscriber_type`, `subscriber_id`) VALUES (&#39;Notification::RssFeedItem&#39;, &#39;Event::CommentForProject&#39;, &#39;{\&quot;commenters\&quot;:[53382,55435,38447],\&quot;commenter\&quot;:55435,\&quot;comment_body\&quot;:\&quot;\\u003c!-- RepoChecker state=seen result=failed build=8548d4c --\\u003e\\n\\n## x86_64\\n\\n### [install check \\u0026 file conflicts](/package/view_file/openSUSE:Factory:Staging/dashboard/repo_checker)\\n\\n\\u003cpre\\u003e\\nfound conflict of ruby2.4-rubygem-erubis-2.7.0-6.10.x86_64 with ruby2.4-rubygem-erubis-2_7-2.7.0-3.5.x86_64:\\n  - /usr/bin/erubis.ruby2.4-2.7.0\\n  - /usr/lib64/ruby/gems/2.4.0/specifications/erubis-2.7.0.gemspec\\n  - /usr/lib64/ruby/gems/2.4.0/gems/erubis-2.7.0/CHANGES.txt\\n  - /usr/lib64/ruby/gems/2.4.0/gems/erubis-2.7.0/MIT-LICENSE\\n  - /usr/lib64/ruby/gems/2.4.0/gems/erubis-2.7.0/README.txt\\
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5a553fa106965c000b096e53)

**Comment by evanrolfe** [comment] 2018-01-10 08:56
There are already at least 2 other duplicate issues for this...

https://github.com/openSUSE/open-build-service/issues/4161
https://github.com/openSUSE/open-build-service/issues/3339

**Comment by eduardoj** [comment] 2018-01-10 14:53
Duplicate of #4161. Closing.

**Closed by eduardoj** 2018-01-10 14:53 UTC
Labels: Bug, Frontend
