### ISSUE TITLE
[production][delayed_job#ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper] wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/open-build-service#3709] opened 2017-08-30 05:27 UTC
delayed_job#ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper threw this 4 times
<pre>
wrong number of arguments (given 2, expected 1)
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59a6121684aa620008b7ca6a)

**Comment by hennevogel** [comment] 2017-08-30 09:05
duplicate of #3708

**Closed by hennevogel** 2017-08-30 09:05 UTC
Labels: Bug, Frontend
