### ISSUE TITLE
Upgrading from OBS 2.8 to 2.9 causes lots of project meta references to change to 'deleted' and break ability to build

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/open-build-service#4761] opened 2018-03-28 19:17 UTC
Issue description
====================
When upgrading from OBS 2.8 to OBS 2.9, projects wind up losing random parts of the meta configuration to getting marked as `deleted`.

### OBS 2.8 
![screenshot_20180328_151511](https://user-images.githubusercontent.com/276796/38051003-e315c346-329a-11e8-8a9a-12759e603675.png)

### OBS 2.9: 
![screenshot_20180328_151432](https://user-images.githubusercontent.com/276796/38051011-ec46460c-329a-11e8-89f5-999937942717.png)

The entries that break are somewhat random, but it renders the build service instance completely broken.

Expected result
============
OBS upgrades don't lead to broken project meta

How to Reproduce
===============
1. Set up an OBS system on 2.8 interconnected with build.opensuse.org
2. Set up some projects with targets and repos interconnected used
3. Upgrade to OBS 2.9

Further information
===============
* Exact server version: 2.9.1-37.1

**Comment by bgeuken** [comment] 2018-03-29 05:47
Just a wild guess, but it looks like your update triggered a re-sync with build.opensuse.org and since some projects got removed / unpublished they are marked as deleted. For example [Fedora 25](
https://download.opensuse.org/repositories/Fedora:/25/standard) got unpublished and does not contain any packages anymore.

**Comment by adrianschroeter** [comment] 2018-03-29 06:47
please tell us the history of the meta data. You can get it via

 osc log -M $project .

Can you find the guilty commit via

 osc blame -M $project _project _meta

?

**Comment by Conan-Kudo** [comment] 2018-03-29 10:27
Output from `osc log -M`:

### OBS 2.9
```
----------------------------------------------------------------------------
r13 | ngompa | 2017-03-20 18:00:03 | d90ae7b1db547aa8878cfdd9eebbba0f | None |

<no message>
----------------------------------------------------------------------------
r12 | ngompa | 2017-03-20 17:54:56 | a07b22f502d9335d18677f33253ca32b | None |

<no message>
----------------------------------------------------------------------------
r11 | ngompa | 2017-02-09 16:57:22 | 0a13cadc31217f40ada97a2e5763ac7e | None |

<no message>
----------------------------------------------------------------------------
r10 | ngompa | 2017-02-09 16:57:17 | aa6ec11c02a9237edb7f92c61d9f7a96 | None |

<no message>
----------------------------------------------------------------------------
r9 | ngompa | 2017-02-09 16:55:50 | fa5f287d4ee6e698cd71ba7be95dbead | None |

<no message>
----------------------------------------------------------------------------
```

### OBS 2.8
```
----------------------------------------------------------------------------
r13 | ngompa | 2017-03-20 18:00:03 | d90ae7b1db547aa8878cfdd9eebbba0f | None |

<no message>
----------------------------------------------------------------------------
r12 | ngompa | 2017-03-20 17:54:56 | a07b22f502d9335d18677f33253ca32b | None |

<no message>
----------------------------------------------------------------------------
r11 | ngompa | 2017-02-09 16:57:22 | 0a13cadc31217f40ada97a2e5763ac7e | None |

<no message>
----------------------------------------------------------------------------
r10 | ngompa | 2017-02-09 16:57:17 | aa6ec11c02a9237edb7f92c61d9f7a96 | None |

<no message>
----------------------------------------------------------------------------
r9 | ngompa | 2017-02-09 16:55:50 | fa5f287d4ee6e698cd71ba7be95dbead | None |

<no message>
----------------------------------------------------------------------------
```

**Comment by Conan-Kudo** [comment] 2018-03-29 10:28
@bgeuken That doesn't make sense, because across my system, projects with CentOS 7, Ubuntu 14.04, Ubuntu 18.04, and so on were affected.

**Comment by adrianschroeter** [comment] 2018-03-29 11:27
It means then that the database has changed without storing the data to the backend.

do you have a backup of your old database and can you check if 

20170306084558_change_repositories_remote_project_name_to_not_null.rb

migration is guilty? 

Will try to reproduce it here as well and pull 2.9 release in case it is ...

**Comment by Conan-Kudo** [comment] 2018-03-29 11:50
@adrianschroeter I do, in fact, have a backup of the old database, as this was a test upgrade cloned from a backup.

How do I check to see if the migration is the guilty party?

**Comment by Conan-Kudo** [comment] 2018-03-29 12:00
I've purged the borked database and restored it from backup, moved the "potentially" guilty migration out of the way, and am re-running migrations.

**Comment by Conan-Kudo** [comment] 2018-03-29 12:09
@adrianschroeter Removing that migration led to this:

```
<project name="home:ngompa">
  <title>ngompa's Home Project</title>
  <description>Playground of package builds</description>
  <person userid="ngompa" role="maintainer"/>
  <build>
    <disable arch="i586"/>
  </build>
</project>
```

**Comment by adrianschroeter** [comment] 2018-03-29 12:14
yes, you would need also adapt the rendering code to see repos at all.

But I can at least reproduce it partly. pulling back 2.9 release ...

**Comment by hennevogel** [comment] 2018-03-29 15:35
@adrianschroeter are you working on this?

**Comment by adrianschroeter** [comment] 2018-03-29 15:52
On Donnerstag, 29. März 2018, 17:35:28 CEST wrote Henne Vogelsang:
> @adrianschroeter are you working on this?

Not today anymore, sorry.

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by Conan-Kudo** [comment] 2018-03-29 17:18
@hennevogel @bgeuken @adrianschroeter Even manually re-inserting the project meta content does not fix this, and the frontend stops rendering any targets.

(This is after resetting and having the database have the full migration set done against it, including the suspect one).

**Comment by bgeuken** [comment] 2018-03-30 06:28
> adrianschroeter 
>commented about 19 hours ago
> It means then that the database has changed without storing the data to the backend.

> do you have a backup of your old database and can you check if

>20170306084558_change_repositories_remote_project_name_to_not_null.rb

> migration is guilty?

So is this called by the disabled global write through in that migration?

**Comment by adrianschroeter** [comment] 2018-03-30 06:51
the backend still has valid data, this is not the problem. The problem are the corrupted path entries.

Can ne1 tell why we needed the migration to empty string from NULL at all? Otherwise I would revert it (at least for 2.9 branch), drop this migration and write a new one reverting to the old state. This could be easily done in a save way. (we would also revert some of the code changes dealing with the data).

**Comment by adrianschroeter** [comment] 2018-04-03 08:43
![](https://github.trello.services/images/mini-trello-icon.png) [Release OBS 2.9.2](https://trello.com/c/ZdX6t9FW/1370-release-obs-292)

**Comment by adrianschroeter** [comment] 2018-04-03 08:43
![](https://github.trello.services/images/mini-trello-icon.png) [Release OBS 2.9.2](https://trello.com/c/ZdX6t9FW/1370-release-obs-292)

**Comment by adrianschroeter** [comment] 2018-04-03 08:45
Btw, the root cause is the "ON a.db_project_id = b.db_project_id" line in the double entry detection. Remote repositories have it NULL, so it is mixing multiple entries.

**Closed** 2018-04-05 08:57 UTC
