### ISSUE TITLE
Broken link when searching for gcc10

### ISSUE THREAD

**Issue by marxin** [openSUSE/open-build-service#9997] opened 2020-08-10 04:46 UTC
When doing a search for `gcc10` I get 500 error:
https://build.opensuse.org/search?search_text=gcc10&search_for=0&name=1&attrib_type_id=

**Comment by eduardoj** [comment] 2020-08-10 08:16
Duplicate of #9436. Closing.

**Closed by eduardoj** 2020-08-10 08:16 UTC
