### ISSUE TITLE
Broken rendering in SR diffs with longer lines

### ISSUE THREAD

**Issue by danishprakash** [openSUSE/open-build-service#17126] opened 2024-11-22 10:59 UTC
![image](https://github.com/user-attachments/assets/9f971cec-5be9-432d-ad0b-c31cf7fc8a26)

Reference SR - https://build.opensuse.org/request/show/1224845

**Comment by hennevogel** [comment] 2024-11-22 11:11
@hellcp-work sounds like eyecatchers fallout?

**Comment by hellcp-work** [comment] 2024-11-22 11:12
I think this might have always been broken, it's browser dependent

**Comment by hellcp-work** [comment] 2024-11-22 11:18
It's a duplicate of #8172

**Closed** 2024-11-22 11:35 UTC
Labels: Frontend
