### ISSUE TITLE
POST /trigger/rebuild?project= fails with an error 500 instead of an error 400

### ISSUE THREAD

**Issue by dcermak** [openSUSE/open-build-service#15114] opened 2023-10-25 10:23 UTC
# Issue Description

It appears impossible to trigger the full rebuild of a project. If you try to do that, OBS responds with an error 500 instead of 400.

Expected Result
============

`curl -H "Authorization: Token $SECRET" -X POST "https://api.opensuse.org/trigger/rebuild?project=devel:BCI:SLE-15-SP5"` should result in a Error 400, not an internal server error.

**Comment by dmarcoux** [comment] 2023-10-25 11:11
This is a duplicate of #12813, so I'll close the issue.

It happens since a package wasn't passed as stated in API documentation for this endpoint: `A package must be provided for the operations rebuild, release and runservice`. Nevertheless, this shouldn't error out with a 500 like it does right now.

**Closed by dmarcoux** 2023-10-25 11:11 UTC
