### ISSUE TITLE
Update the link to the latest revision from the UI

### ISSUE THREAD

**Issue by danidoni** [openSUSE/open-build-service#15728] opened 2024-03-01 13:17 UTC
Sometimes we need to update a link to the latest revision from upstream. Right now, you have to download the package, and do `osc setlinkrev` and then upload the changes.

A buton in the UI to update to the latest revision would speed up this process.

**Comment by hennevogel** [comment] 2024-03-04 15:34
Duplicate of #11676

**Closed** 2024-03-04 15:34 UTC
Labels: Feature, Frontend
