### ISSUE TITLE
obs web interface shows an empty package list in a project with packages

### ISSUE THREAD

**Issue by antlarr-suse** [openSUSE/open-build-service#8793] opened 2019-11-27 10:13 UTC
# Issue Description

Some days ago I opened https://build.opensuse.org/project/show/openSUSE:Factory:Staging:D , which (at that time) had more than 25 packages so I went to check the second page of packages.

Today, I went to Staging:D again but this time there are only 19 packages. OBS showed there are 19 packages but didn't show any and says there is just one page of packages. It sayd it was showing page 1 but I discovered it's showing page 2 since I clicked on the "Previous" button to go to the previous page and the packages appeared.

It seems the web interface is trying to keep the state of what I was viewing to show the same view I was vieweing the last time I visited the project but it didn't check that the state is no longer valid

Expected Result
============
Projects with packages should show the packages contained and not an empty list. Current page should be checked to be valid and if not, go to the fist page. Maybe, even the view state should be invalidated if it was stored more than n hours ago, since lately the search bar seems to be also stored and most times it contains packages I searched for a long time ago and it takes more time to remove the search text than the time saved by keeping it there between visits.

How to Reproduce
===============
I didn't check, but I think it can be reproduced by creating a project with more than 25 packages, go to the second page, then with a different user (or with osc), remove some packages to leave less than 25 and visit the project page again with the first user.

**Comment by hennevogel** [comment] 2019-11-27 13:12
duplicate of #7535

**Closed by hennevogel** 2019-11-27 13:12 UTC
Labels: Frontend
