### ISSUE TITLE
webui does not show .txt files any more

### ISSUE THREAD

**Issue by afaerber** [openSUSE/open-build-service#2126] opened 2016-09-13 11:26 UTC
Similar to #2125 but instead of an error just an empty page:

https://build.opensuse.org/package/view_file/hardware/raspberrypi-firmware/config-rpi3.txt?expand=1
https://build.opensuse.org/package/view_file/hardware/bcm43xx-firmware/brcmfmac43362-sdio-cubietruck.txt?expand=1

Other extensions such as .sh, .conf, .changes, .spec seem fine.

**Comment by bgeuken** [comment] 2016-09-13 13:35
Thanks for the report. I'll close it as duplicate of #2125 though

**Closed by bgeuken** 2016-09-13 13:35 UTC

**Comment by afaerber** [comment] 2016-09-13 17:35
Confirming fixed. Thanks, Björn!
