### ISSUE TITLE
OBS with LDAP backend experiences spurious authentication failures

### ISSUE THREAD

**Issue by seife** [openSUSE/open-build-service#3853] opened 2017-09-19 13:30 UTC
Issue/Feature description
====================

Spurious authentication failures in osc ("401 unauthorized") and in the web frontend.
OBS is configured for LDAP auth against an Microsoft AD server. This config worked fine before the update to 2.8.3.
A similar issue was seen years ago with OBS 2.3.x

Production log at the time of the auth failure shows:
`I, [2017-09-19T12:30:04.264456 #3787]  INFO -- : [4984a994-ef51-468d-a66c-b829c3e9a23b] [3787:4483.55] Search failed:  error -1: Can't contact LDAP server`

Expected result
============
LDAP auth works.

Further information
===============
It pretty much looks like commit db44312746793b8dc46651af48de231f827d0cc6 accidentally reverted the improvements made by commit 920a731d96b2d69dfec7a68e84f0c993b5d0e933 seven years ago.

I'm testing locally a revert of db44312 and have not experienced the issue again until now (but it's spurious, so it might take some time)

**Comment by evanrolfe** [comment] 2017-09-20 09:44
I'm closing this as its a duplicate of https://github.com/openSUSE/open-build-service/issues/3861 which contains more information about the issue.

**Closed by evanrolfe** 2017-09-20 09:44 UTC
