### ISSUE TITLE
No User in OBS Account

### ISSUE THREAD

**Issue by raniaamina** [openSUSE/open-build-service#11664] opened 2021-09-28 10:17 UTC
Hi devs,

This is my first time using OBS. Somehow, i accidentally delete my access to my own project, so there's no user as seen in this pic
![gambar](https://user-images.githubusercontent.com/22146607/135067390-e39cd1e9-2c07-42ae-a156-aef59ada3ea6.png)

This make me can't do anything with obs, including add/delete project.
Is there any solution about this problem?
Thanks before.

Rania Amina

**Comment by cho2** [comment] 2021-09-28 10:37
I think it's a bug.

First, I have the `maintainer` checked

![photo_2021-09-28_17-32-50](https://user-images.githubusercontent.com/6271071/135071330-c2ad8e50-6091-420b-b28d-44ffa259ba0e.jpg)

Second, when I unchecked `maintainer` and checked `reader`, I can't add any user roles.

https://user-images.githubusercontent.com/6271071/135071524-67956b2e-9c9f-4424-8fa2-36cd3a43afca.mp4

Probably, `maintainer` is mandatory that user can't unchecked.

**Comment by eduardoj** [comment] 2021-09-28 11:13
Duplicate of #10067. Closing.

**Closed by eduardoj** 2021-09-28 11:13 UTC

**Comment by adrianschroeter** [comment] 2021-09-28 11:31
I added your role again.

You could have done your self using "osc meta prj -e home:cho2" btw

**Comment by cho2** [comment] 2021-09-28 11:54
Thank you, now `maintainer` is back

**Comment by raniaamina** [comment] 2021-09-28 12:10
Thanks @adrianschroeter, it works!

**Comment by dmarcoux** [comment] 2022-07-18 14:25
If someone ever stumbles on this issue, this has been fixed in #12808. Users who accidentally removed their access to their home project can now add it back through the web interface.
