### ISSUE TITLE
SELECT statement as error message

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#14205] opened 2023-04-21 14:13 UTC
With a typo in the project name (lowercase factory)...

```shell
osc deletereq openSUSE:factory:Rebuild/rubygem-sassc-2.2
Server returned an error: HTTP Error 404: Not Found
Couldn't find Package with [WHERE `packages`.`id` NOT IN (SELECT `packages`.`id` FROM `packages` WHERE `packages`.`project_id` = ?) AND `packages`.`project_id` = ? AND `packages`.`name` = ?]
```

via @darix

**Comment by eduardoj** [comment] 2023-04-21 14:34
I couldn't reproduce it:
```bash
> osc deletereq openSUSE:factory:Rebuild/rubygem-sassc-2.2  
Server returned an error: HTTP Error 404: Not Found                                                                                                                                 
Project not found: openSUSE:factory:Rebuild
```
Are we sure the project `openSUSE:factory:Rebuild` never existed?

**Comment by hennevogel** [comment] 2023-04-21 14:41
> Are we sure the project openSUSE:factory:Rebuild never existed?

Nope...

**Comment by eduardoj** [comment] 2023-04-21 14:41
I couldn't reproduce it when the project exists, and the package doesn't:
```bash
> osc deletereq openSUSE:Factory:Rebuild/this-doesnt-exist
Server returned an error: HTTP Error 404: Not Found                                                                                                                                 
Package not found: openSUSE:Factory:Rebuild/this-doesnt-exist
```

**Comment by hennevogel** [comment] 2023-04-24 09:22
@darix?

**Comment by darix** [comment] 2023-04-24 09:27
I just copy pasted the errror message.

**Comment by darix** [comment] 2023-04-24 09:58
negative.

**Comment by eduardoj** [comment] 2023-10-13 14:33
I tried to reproduce the issue with several wrong project names and package names without success. It might be that the issue has been fixed in the meanwhile.

Please reopen if it happens again.

**Closed by eduardoj** 2023-10-13 14:33 UTC
Labels: Bug, Frontend
