### ISSUE TITLE
500: Internal Server Error

### ISSUE THREAD

**Issue by osvaldop4** [openSUSE/open-build-service#10708] opened 2021-01-28 11:44 UTC
# Issue Description
A clear and concise description of what the bug i

When login in HTTPS://build.openservice.org is happens the message
500: Internal Server Error
The issue  before was closed and not resolved.
I did the procedure that written in ticket bit the error continue.
User: osvaldopdjr

Expected Result
============

How to Reproduce
===============

Further Information
===============
* A link to an OBS instance showing the issue
* Exact server version (in case a private instance is used)

**Comment by krauselukas** [comment] 2021-01-28 12:02
@osvaldop4 yes, we got aware that the problem is unfortunately not completely resolved yet. For the latest status report see https://status.opensuse.org/ we are working on resolving the issue.

**Comment by osvaldop4** [comment] 2021-01-28 12:09
I saw the status. I did the account again.

**Comment by krauselukas** [comment] 2021-01-29 12:05
@osvaldop4 the issue should be resolved now, most likely a password reset is required in order to use your account. https://status.opensuse.org/incidents/240

After you confirm its working for you, I will close the issue

**Comment by osvaldop4** [comment] 2021-01-29 13:23
@krauselukas 
You can close the issue. Now, I login.

**Comment by krauselukas** [comment] 2021-01-29 14:33
Perfect, thanks for verifying

**Closed by krauselukas** 2021-01-29 14:33 UTC
Labels: Bug
