### ISSUE TITLE
EventMailer: incompatible character encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#3344] opened 2017-07-03 14:25 UTC
delayed_job#Delayed::PerformableMethod threw this 1 times
<pre>
incompatible character encodings: UTF-8 and ASCII-8BIT
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/595a3d2613741000069a6332)

**Comment by ChrisBr** [comment] 2017-08-09 13:25
Duplicate of https://github.com/openSUSE/open-build-service/issues/3415

@hennevogel can we somehow prohibit to not create the same erribit issue again and again?

**Closed** 2017-08-09 13:25 UTC
Labels: Bug, frontend
