### ISSUE TITLE
New UI has lot of wasted white areas

### ISSUE THREAD

**Issue by jonsger** [openSUSE/open-build-service#7033] opened 2019-02-25 11:06 UTC
## Issue Description
When using the new UI of OBS through the public beta program on build.opensuse.org I see a lot of wasted white areas. As the font size is bigger and the width smaller, text lines have many line breaks.

## New UI
![home_user_new_ui](https://user-images.githubusercontent.com/3876790/53333105-393db880-38f5-11e9-860d-68eba5df13cf.png)

## Old UI
![home_user_old_ui](https://user-images.githubusercontent.com/3876790/53333029-4eb2e280-38f5-11e9-86ac-62f02486bb5f.png)

I think it's clearly visible that the readability in the new UI is much worser, due to all those line breaks.

A "simple" mitigation would be to decrease the width of the free space on the left and right site of the page.

## How to Reproduce
1. Go to build.opensuse.org
2. Decrease the window size of your browser to something like 940px (half width of FullHD).
2. Join the public beta program on your user home directory.
3. Compare page views with the old UI.

**Comment by dmarcoux** [comment] 2019-02-25 12:29
Thank you @jonsger for the feedback.

I agree that this needs to be improved. We already worked on something quite similar regarding breakpoints (#6033), however the issue you report is about smaller viewports. We'll need to address it.

**Comment by hennevogel** [comment] 2019-02-25 21:10
There is a reason those are called **break**points. You should introduce them when your layout breaks. It does not break at 1600. Nor does it break at 768. What is mentioned is actually the point the new layout *"breaks"* (as in too much padding left and right) at ca. 800px width. The real fix would be to handle this.


BTW this particular break repeats after every *break point* + 10px we have BTW (so at 586px for SM, 778px for MD, 1002px for LG etc. etc.)

**Comment by dmarcoux** [comment] 2019-02-26 12:06
We could use fluid containers for small viewports (so `.container-fluid` instead of `.container`). Those would take the available space instead of being limited to the limit defined by breakpoints.

**Comment by coolo** [comment] 2019-02-27 08:18
I would love to hear how this works. I switched openqa to fluid layout due to similiar issues - and expected pushback from users on large views, but it didn't happen. Even though e.g. https://openqa.opensuse.org/tests is very spacy now.

**Comment by dmarcoux** [comment] 2019-02-27 09:32
@coolo The width for `.container` is defined based on [those variables](https://github.com/twbs/bootstrap/blob/bc60a22a1843928814099ef5e6e26552f55aebae/scss/_variables.scss#L203-L212) and the width for `.container-fluid` is 100% with a bit of padding, as defined [here](https://github.com/twbs/bootstrap/blob/ff29c1224c20b8fcf2d1e7c28426470f1dc3e40d/dist/css/bootstrap.css#L580-L586).

I need to take more time to explore different solutions, but my idea now would be to work with media queries and extend `.container` with `.container-fluid` for small viewports. `.container` and `.container-fluid` are pretty much the same, except for the width, so I think it would work.

**Comment by Ana06** [comment] 2019-04-16 14:49
Related to https://github.com/openSUSE/open-build-service/issues/6587

**Comment by hennevogel** [comment] 2019-06-13 14:59
duplicate of #6587

**Closed by hennevogel** 2019-06-13 14:59 UTC
Labels: Bootstrap :rocket:, Frontend
