### ISSUE TITLE
[webui] cannot trigger source service run from package view

### ISSUE THREAD

**Issue by mmohring** [openSUSE/open-build-service#1696] opened 2016-04-08 14:29 UTC
Older versions had a way to trigger a source service run from the WebUI. I cannot find this anymore.

**Comment by hennevogel** [comment] 2016-04-08 14:39
It got removed because it was broken. 

Duplicate of #84

**Closed by hennevogel** 2016-04-08 14:39 UTC

**Comment by mmohring** [comment] 2016-04-08 14:44
If this was broken why is this a reason to remove the feature and close the issue ?

**Comment by hennevogel** [comment] 2016-04-08 14:55
Because it was broken beyond repair so we need to re-implement it. This issues is closed because we already have an issue that tracks this feature: #84

**Comment by mmohring** [comment] 2016-04-08 15:06
All right. Thanks for the explaination.
