### ISSUE TITLE
WebUI shows too many archs

### ISSUE THREAD

**Issue by antlarr** [openSUSE/open-build-service#1140] opened 2015-09-18 08:04 UTC
It seems web UI is showing all archs of every repository in the repositories page next to each other without "uniq'ing" them. So if a project has a SLE_12 repository that can be built for x86_64 and an opensuse_13.2 repository that can be built for i586 and x86_64 then the repository page shows x86_64 twice.

This can be seen at https://build.opensuse.org/project/repositories/openSUSE:Factory or at https://build.opensuse.org/project/repositories/KDE:Frameworks5 for example.

**Comment by adrianschroeter** [comment] 2015-09-18 08:13
right ... and it explodes at https://build.opensuse.org/project/repositories/openSUSE:Tools

**Comment by adrianschroeter** [comment] 2015-09-18 08:23
1009b0a92eba8ca384ad8ac75d8bf90a5f94f37c is hot-fixing this. A test case is still missing and "project.architectures" in the model may need to be rediscussed, It make not really sense relationship wise.

**Comment by ChrisBr** [comment] 2015-09-18 14:09
Looked briefly into it, probably 8b4d426e63a02440ca76359f6a163ae17cdd6ca3 caused it!
@adrianschroeter is your 'hot-fix' already the final fix and we only need a test for it?

**Comment by adrianschroeter** [comment] 2015-09-18 15:13
Not sure, we should at least discussing the meaning of "project architectures". They do not make much sense to me in the current form. But a test cases is missing in any case :)

**Comment by bgeuken** [comment] 2015-09-19 14:21
+1 for tests:)

Given that this is an active record relation we should be able to add a uniq [here](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/models/project.rb#L51). This might require a migration to ensure there are no duplicated archs.

**Comment by adrianschroeter** [comment] 2015-09-21 07:01
a uniq in the model might be wrong, because if you want to loop through all architectures in all reositories you would skip some. Therefore I think it is wrong to have architectures in project model directly like the refactor commit did. This seems only to be used in the one webui view anyway, so the architectures lookup via all repos & uniq should happen there.

**Comment by bgeuken** [comment] 2015-09-25 12:03
Test got add with e7b9e3d29c8b11043e57 and Adrian fixed the regression way before. Thus I am closing this one and opened a feature: #1172

**Closed by bgeuken** 2015-09-25 12:03 UTC
Labels: Bug, P2, Regression, webui
