### ISSUE TITLE
Cleanup and accepts collide (Cleanup run to early)?

### ISSUE THREAD

**Issue by zaitor** [openSUSE/open-build-service#1367] opened 2015-11-12 10:46 UTC
Last 2 days or so, we have been getting this in our checkins.

Request History

 Zaitor	created request	about 1 hour ago
New stable
 dimstar	Review got accepted	about 1 hour ago
ok
 dimstar	Request got reviewed	about 1 hour ago
ok
 Zaitor	Request got revoked	6 minutes ago
The source package 'home:Zaitor:branches:GNOME: [+]
 Zaitor	Request got accepted	6 minutes ago
Checkin and forward

----

People involved gets 2 emails, one accepted and one revoked.

See 
https://build.opensuse.org/request/show/343958
https://build.opensuse.org/request/show/343960

**Comment by hennevogel** [comment] 2015-11-12 12:44
Duplicate of #1327

**Closed by hennevogel** 2015-11-12 12:44 UTC
