### ISSUE TITLE
Webui search returns error 500

### ISSUE THREAD

**Issue by lethliel** [openSUSE/open-build-service#3679] opened 2017-08-28 09:50 UTC
Issue/Feature description
====================
Search gives error 500

Expected result
============
To give the search result 

How to Reproduce
===============
1. Search for "Virtualization:containers" or any other string
2. Hit enter
3. look at the firefighter

Further information
===============

**Comment by mdeniz** [comment] 2017-08-28 10:13
Looks like its solved

**Comment by hennevogel** [comment] 2017-08-28 10:13
Duplicate of #3338

**Closed by mdeniz** 2017-08-28 10:13 UTC
