### ISSUE TITLE
Can't browse package from the webui if it has a dot in its name

### ISSUE THREAD

**Issue by luigino** [openSUSE/open-build-service#2513] opened 2017-01-03 10:22 UTC
e.g. [python3-ruamel.yaml](https://build.opensuse.org/package/show/devel:languages:python3/python3-ruamel.yaml).

Everything works fine via osc.

**Comment by adrianschroeter** [comment] 2017-01-03 10:25
I think it is the .yaml suffix which is caused a routing error

**Comment by bgeuken** [comment] 2017-03-27 06:56
Duplicate of #2900

**Closed by bgeuken** 2017-03-27 06:56 UTC
Labels: Bug, frontend, junior, P3
