### ISSUE TITLE
Package entry page is awfully slow for packages with a lot of history

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#12406] opened 2022-04-05 14:36 UTC
https://build.opensuse.org/package/show/openSUSE:Factory:Staging/dashboard takes 27 seconds

The time eater is the commit details for "latest revision" - in a package with less than the 67990 revisions it's faster, much faster. Compare to https://build.opensuse.org/package/show/openSUSE:Factory:ARM:Staging/dashboard with it's 941 revisions: 0.7s

https://build.opensuse.org/package/show/Kernel:HEAD/kernel-source has 9268 revisions and loads in 4.5s (but also has build status)

parse_all_history in app/models/package.rb is called from package.commit and eats all that. Even though the backend route supports a rev argument to cherry pick (which works for both srcmd5 and revision arguments). Using that route instead of parsing all the history might be easy enough.

**Comment by hennevogel** [comment] 2023-02-21 18:17
It's has started to pull our SLI so Duplicate of #13871

**Closed by hennevogel** 2023-02-21 18:17 UTC
Labels: Frontend, Refactoring :factory:
