### ISSUE TITLE
_multibuild files uploaded to build disabled package not recognized

### ISSUE THREAD

**Issue by darix** [openSUSE/open-build-service#3573] opened 2017-08-10 16:16 UTC
during a cleanup i disabled building for a complete project

while fixing one package i ran into the bug that local _multibuild files are not recognized until you commit them. now the problem is that with a build disabled package the files are still not recognized for local builds. you need to enable building of the package before you can have a successful local build.

**Comment by adrianschroeter** [comment] 2017-08-11 05:23
sounds like a duplicate of your #3523 report, no?

**Comment by darix** [comment] 2017-08-11 12:47
no.

it is related but not the same.

**Comment by lethliel** [comment] 2018-12-07 09:57
fixed with commit https://github.com/openSUSE/open-build-service/pull/6460/commits/198bca3b223328487efaf3674d777348d46214c9

**Closed by lethliel** 2018-12-07 09:57 UTC
Labels: Backend 🤖, Feature 💡
