### ISSUE TITLE
fedora package will not build locally with osc

### ISSUE THREAD

**Issue by bill-auger** [openSUSE/open-build-service#2195] opened 2016-10-04 17:23 UTC
when i try to build a fedora package with osc locally it says "chroot: failed to run command 'rpm': No such file or directory" and quits - packages for other systems build successfully locally - i have tried this on both a debian and opensuse host

.build.log here --> https://gist.github.com/bill-auger/4e88a8b6119f352c7a0d25d05725004b

**Comment by lethliel** [comment] 2016-10-05 09:58
it seems that your build system is broken. Have you tried to run the build with the clean option? 

```
osc build --clean Fedora_23 x86_64 av-caster.spec
```

**Comment by bill-auger** [comment] 2016-10-05 12:27
yes it says that every time because it will not finish - it always asks to clean in this case anyways

but i tried explicitly as you suggested and the result is the same

    $ osc build --noverify --clean Fedora_23 x86_64 av-caster.spec

and yes i need ```--noverify``` or else every packages says "public key not available" and quits immediately

**Comment by lethliel** [comment] 2016-10-05 14:27
can you move your buildroot (/var/tmp/build-root) to /tmp (or where you prefer) and rebuild again. I still think that there is something wrong with your buildroot.

**Comment by bill-auger** [comment] 2016-10-05 16:15
ok i just tried that and the result was the same

i thank you for helping but please allow me to make clear what i said before - 

* packages for other targets build ok
* only the fedora packages are giving me trouble
* i have tried this on multiple host systems and the result is exactly the same

**Comment by lethliel** [comment] 2016-10-05 19:06
Thank you for testing this again. I will have a look at it and will get back to the issue. 
I just had the feeling that your Fedora buildroot was broken. It was not my intention to needle you with my suggestions.

But if you tested it on a fresh install the buildroot is obviously not the reason.

**Comment by bill-auger** [comment] 2016-10-05 19:28
np take your time -  i will help if i can but my main problem actually fixed itself inexplicably (#2194)

i was building locally only to troubleshoot why the OBS server was building corrupted fedora packages - it will probably be some time before i need to rebuild locally again

**Comment by lethliel** [comment] 2016-10-06 09:49
can you please attach a .build.log file that fails if you use the clean option? 

```
osc build --clean --noverify Fedora_23 x86_64 av-caster.spec
```

I cannot reproduce this error. I tried several times and on different systems and for me it works every time.

**Comment by bill-auger** [comment] 2016-10-06 11:00
the gist now contains the results from both debian/testing and also opensuse tumbleweed hosts

https://gist.github.com/bill-auger/4e88a8b6119f352c7a0d25d05725004b

**Comment by lethliel** [comment] 2016-10-06 11:22
please install bsdtar on your hostsystem. Otherwise the build script will use cpio instead. 
Then it will work. (Tested) If I uninstall bsdtar on my system the build fails just as yours.

**Comment by bill-auger** [comment] 2016-10-06 11:51
yep that fixed it on debian - perhaps bsdtar should be a dependency of the osc debian package

on the opensuse system it allowed the build to proceed most of the way but then failed with a different error
```
[  452s] [290/345] installing systemd-libs-222-7.fc23
[  453s] [291/345] installing gdb-7.10-23.fc23
[  453s] error: unpacking of archive failed on file /usr/bin/gdb;57f63822: cpio: read
[  453s] error: gdb-7.10-23.fc23.x86_64: install failed
[  453s] exit ...
[  453s] 
```

the full log is here if you are interested  --> https://gist.github.com/bill-auger/4e88a8b6119f352c7a0d25d05725004b

**Comment by bill-auger** [comment] 2016-10-06 11:51
this is the log for the arch package failure

```
[    0s] Memory limit set to 2927186KB
[    0s] Using BUILD_ROOT=/var/tmp/build-root/Arch_Extra-x86_64
[    0s] Using BUILD_ARCH=x86_64:i686:i586:i486:i386
[    0s] 
[    2s] 
[    2s] debian64 started "build PKGBUILD" at Thu Oct  6 11:50:02 UTC 2016.
[    2s] 
[    2s] 
[    2s] processing recipe /mnt/data/code/osc/home:bill-auger/av-caster/PKGBUILD ...
[    2s] running changelog2spec --target rpm --file /mnt/data/code/osc/home:bill-auger/av-caster/PKGBUILD
[    2s] init_buildsystem --configdir /usr/lib/obs-build/configs --cachedir /var/cache/obs-build --rpmlist /tmp/rpmlist.pHGcfY /mnt/data/code/osc/home:bill-auger/av-caster/PKGBUILD ...
[    3s] hostname: Name or service not known
[    3s] Can't exec "xzdec": No such file or directory at /usr/lib/obs-build/Build/Arch.pm line 124.
[    3s] xzdec: No such file or directory
[    3s] GLOB(0x324de90): not an arch package file
[    3s] 
[    3s] exit ...
[    3s] 
[    3s] debian64 failed "build PKGBUILD" at Thu Oct  6 11:50:03 UTC 2016.
[    3s] 
```

**Comment by lethliel** [comment] 2016-10-07 09:38
I will close this issue for it is fixed.

**Closed by lethliel** 2016-10-07 09:38 UTC
