### ISSUE TITLE
File editor: "Save" form needs lots of scrolling

### ISSUE THREAD

**Issue by cboltz** [openSUSE/open-build-service#11396] opened 2021-07-18 10:42 UTC
# Issue Description
When editing a file in the web interface, you need to scroll down to the "Save" form/button.

This is especially annoying when editing a changelog with thousands of lines - you insert some lines at the top of it, and then have to scroll down several miles to reach the "Save" button.

Expected Result
============
No need to scroll for saving the file.

How to Reproduce
===============
1. Log in
2. Go to a package you maintain/can edit (for example in your home repo) with a big changelog
3. Click on the *.changes 
4. Insert a new changelog entry
4. Get annoyed while scrolling down to the "Save" button

Proposed solution
===============

The editor already has a toolbar with "Undo" and "Redo" buttons.

Integrating "Save" in this toolbar would avoid the need to scroll down.

(I'm aware that the input field (for the commit message) is too big for the toolbar. One option to solve that would be to let the "Save" button in the toolbar open a popup with the "Save" form.)

**Comment by hennevogel** [comment] 2021-07-19 09:16
Duplicate of #9537

**Closed by hennevogel** 2021-07-19 09:16 UTC
