### ISSUE TITLE
/project/autocomplete_packages crashes on remote prjs

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#583] opened 2014-02-07 12:59 UTC
```
NoMethodError: undefined method `project_type' for nil:NilClass
WHERE:
webui/project#autocomplete_packages

[PROJECT_ROOT]/app/models/webui_project.rb:203
[PROJECT_ROOT]/app/mixins/webui/requires_project.rb:25
[PROJECT_ROOT]/config/initializers/wrap_parameters.rb:41 
```

**Comment by bgeuken** [comment] 2017-11-06 09:05
The code changed quite a bit and I couldn't find any traces of the broken code. Also the ui doesn't seem to provide package autocomplete support anymore.
So I couldn't reproduce this either.

=> closing

**Closed by bgeuken** 2017-11-06 09:05 UTC
Labels: Bug, Frontend
