### ISSUE TITLE
File view doesn't scroll

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#7952] opened 2019-07-22 06:15 UTC
Going to e.g. https://build.opensuse.org/package/view_file/KDE:Extra/QtAV/QtAV.changes?expand=1 and then using page down keys, the file doesn't follow. it only jumps down some milimeters.

In bento the file is fully expanded and page down works.

**Comment by vpereira** [comment] 2019-07-22 10:03
hm, it works for me in chrome. I'm logged in, I click on the File view to give it focus, I use the arrows to scroll down and It scroll as it should..

**Comment by vpereira** [comment] 2019-07-22 10:07
You have to trust me that I'm using the scroll down and up to navigate through the file 

![peek6VDA5Z](https://user-images.githubusercontent.com/37418/61624598-2e573c00-ac79-11e9-9d5e-6ba576e7d18c.gif)

**Comment by coolo** [comment] 2019-07-22 10:44
you need to click into the tiny window, right. And half the screen stays. This is not a file view, this is a file peephole.

**Comment by coolo** [comment] 2019-07-22 10:46
For reference: this is a screenshot of bento viewing a file:
![screencapture-build-suse-de-package-view-file-Devel-Kernel-master-kernel-lpae-dtb-aarch64-spec-2019-07-22-12_43_14](https://user-images.githubusercontent.com/1067203/61626849-a83df400-ac7e-11e9-9c6e-cb5130814e59.png)

**Comment by coolo** [comment] 2019-07-22 10:46
Another reference: [github file view](https://github.com/openSUSE/open-build-service/blob/master/ReleaseNotes-2.11) - no click into a peep hole required

**Comment by vpereira** [comment] 2019-07-22 12:33
> For reference: this is a screenshot of bento viewing a file:
Hi @coolo 

However you don't have a scrollbar (in bento) in the file linked by you. So do you have a File where the scroll is present to check if the behavior changed with the bootstrap migration?

**Comment by coolo** [comment] 2019-07-22 12:40
you don't see a screenshot in the bento screenshot as the browser does it for you (the screenshot extensions I'm using is creating the full view)

**Comment by coolo** [comment] 2019-07-22 12:41
Just pick a random long file on ibs on nobody

**Comment by vpereira** [comment] 2019-07-22 12:42
I actually can see it in bento in production, so I'm not looking in the screenshot but actually the file in production.

**Comment by coolo** [comment] 2019-07-22 12:46
If you have a scrollbar or not doesn't matter to my report - can you scroll with the keyboard or wheel mouse without clicking into anything? Because I can in bento and github

**Comment by vpereira** [comment] 2019-07-22 12:52
In bento as in github you don't have the scrollbar in the editor, just in the browser. I'm just pointing out that the title isn't right. The file view scrolls. However you have to give the focus to the Editor. In Bento and Github the editor has no scroll, just the browser one. 

![Screenshot_2019-07-22_14-48-30](https://user-images.githubusercontent.com/37418/61633704-f1e30a80-ac8f-11e9-9aca-529b5e0e0678.png)

**Comment by coolo** [comment] 2019-07-22 12:58
You're saying my bug report is not a valid bug report because there is a workaround?

**Comment by vpereira** [comment] 2019-07-22 13:04
> You're saying my bug report is not a valid bug report because there is a workaround?

Hm, I actually said that the title is not right, not the bug report is invalid. But actually I was more concerned about adding context to whoever are going to work on the issue, than judge your issue per se.  
Said that a long file like
![61626849-a83df400-ac7e-11e9-9c6e-cb5130814e59](https://user-images.githubusercontent.com/37418/61634459-ac274180-ac91-11e9-8373-70c6d55f07c2.png)
 doesn't look right to me if it's a diff and the user have to scroll down to interact with the comments bellow that. That's not the case with GH, since they allow comment inline.

**Comment by coolo** [comment] 2019-07-22 13:28
there are no comments in view_file - don't mix things up

**Comment by vpereira** [comment] 2019-07-22 13:42
> there are no comments in view_file - don't mix things up

sorry I was assuming that you know the internals.. it uses a shared partial named `'shared/editor' `

**Comment by vpereira** [comment] 2019-07-22 13:52
BTW probably a duplicate of https://github.com/openSUSE/open-build-service/issues/7799

**Comment by vpereira** [comment] 2019-07-22 13:54
i will close it since the #7799 has much better technical details. Thank you @coolo and feel free to reopen it if you think they aren't related.

**Closed by vpereira** 2019-07-22 13:54 UTC
Labels: Bootstrap :rocket:, Frontend, Regression :smiling_imp:
