### ISSUE TITLE
webgui does not show linked package metadata across interconnects

### ISSUE THREAD

**Issue by bluca** [openSUSE/open-build-service#5106] opened 2018-06-07 16:53 UTC
If a linkpac crosses to a remote interconnect, the webgui will not show the _link file nor any other visual clue that a package is in fact linked.

Note that osc ls and osc info will show the correct information and the _link file, so it would appear to be most likely a gui problem.

Expected Result
============
_link file should be visible at a minimum, possibly the usual link to the source as well

How to Reproduce
===============
osc linkpac remote:project/package localproject and then open localproject in the local webgui.

Further Information
===============
This happens on an internal OBS 2.9 instance linking to a package on build.opensuse.org

**Comment by hennevogel** [comment] 2018-06-11 09:49
Duplicate of #3138

**Closed by hennevogel** 2018-06-11 09:49 UTC
