### ISSUE TITLE
[production][build_reason#index] undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by evanrolfe** [openSUSE/open-build-service#4407] opened 2018-01-26 09:40 UTC
build_reason#index threw this 1 times
<pre>
undefined method `[]&#39; for nil:NilClass
</pre>
[https://build.opensuse.org/packages/subversion/build_reason/openSUSE:Factory:ARM/standard/aarch64](https://build.opensuse.org/packages/subversion/build_reason/openSUSE:Factory:ARM/standard/aarch64)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5a680787aa67e3000b075a57)

**Comment by hennevogel** [comment] 2018-02-28 12:40
duplicate of #4050

**Closed by hennevogel** 2018-02-28 12:40 UTC
Labels: Bug, Frontend, PR welcome, junior
