### ISSUE TITLE
Container release stuck at 1.1 with dynamic BuildVersion values

### ISSUE THREAD

**Issue by marcosbc** [openSUSE/open-build-service#15210] opened 2023-11-15 13:40 UTC
# Issue Description

We are finding an issue in OBS when building container images, where the release number is always stuck at 1.1, no matter how many times it is rebuilt or updated.

This happens when the value of the BuildVersion tag is set to a dynamic value (i.e. from a replace_using_package_version placeholder). Note that in this case, the version is properly populated in the _.containerinfo_ file, but the release number is always stuck at the same value.

We expect this to work because in most cases in OBS, the app version is not known at the time the Dockerfile is created, and needs to be calculated from a package version. And this way we can also retrieve the proper app version from the _.containerinfo_ file.

Expected Result
============
When defining a placeholder to be replaced with replace_using_package_version, the release number is increased each time it is rebuilt (e.g. `1.1` -> `1.2`), and each time the dockerfile is updated (e.g. `1.2` -> `2.1`).

Also, in this scenario, whenever the version of the package is increased, the release number is reset to `1.1`. But after being rebuilt, or updating the Dockerfile, it gets increased again - I understand this is what `BuildVersion` is expected to do.

How to Reproduce
===============
1. Create a container package in OBS using Dockerfile.
1. Add a `replace_using_package_version` service replacing the `%VERSION%` placeholder with the version of a specific system package.
1. Ensure the Dockerfile contains the following contents: `#!BuildVersion: %VERSION%`
1. Rebuild the container many times, update the Dockerfile contents many times, but the release number will always be set to 1.1.

Further Information
===============
* A link to an OBS instance showing the issue:
  * [Working job](https://build.opensuse.org/package/show/home:mbjoerkelund:open-build-service-15210/dockerfile-example-working) where the release number can be increased (using a constant value for BuildVersion)
  * [Non-working job](https://build.opensuse.org/package/show/home:mbjoerkelund:open-build-service-15210/dockerfile-example-notworking) where the release number is stuck at 1.1 (using `#!BuildVersion: %VERSION%`)

**Comment by adrianschroeter** [comment] 2023-11-15 16:23
without deeper checking, I suppose it is caused by using % in the version string. This may considered be as rpm macro, but it is not anywhere defined most likely.

Can you just try to avoid this and use for example underscores instead?

**Comment by marcosbc** [comment] 2023-11-15 17:07
@adrianschroeter You seem to be right, since it worked in my [test job](https://build.opensuse.org/package/show/home:mbjoerkelund:open-build-service-15210/dockerfile-example-notworking).

However, it is a bit confusing for me, why would a string formatted like an RPM macro affect a Dockerfile? Would there be any plan to support this scenario?

**Comment by adrianschroeter** [comment] 2023-11-16 07:36
On Mittwoch, 15. November 2023, 18:07:35 CET Marcos Bjoerkelund wrote:
> @adrianschroeter You seem to be right, since it worked in my [test job](https://build.opensuse.org/package/show/home:mbjoerkelund:open-build-service-15210/dockerfile-example-notworking).
> 
> However, it is a bit confusing for me, why would a string formatted like an RPM macro affect a Dockerfile? Would there be any plan to support this scenario?

The mechanic is generic at this level and people do hack all kind 
things using rpm macros. For example also version handling in
kiwi builds via prjconf injected macros.

So, this is not something what we would like to change just for
a single build format if not needed.

-- 

Adrian Schroeter ***@***.***>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH, Frankenstraße 146, 90461 Nürnberg, Germany
(HRB 36809, AG Nürnberg) Geschäftsführer: Ivo Totev

**Comment by marcosbc** [comment] 2023-11-17 12:26
@adrianschroeter By removing the `%` from the string, we were able to workaround the issue for some packages.

However, for other packages we are using `replace_using_env` to obtain the package version from a multi-flavored container build, and we are now facing the challenge where this service [imposes the usage of `%%` to replace environment variables](https://code.opensuse.org/package/obs-service-replace_using_env/blob/master/f/replace_using_env#_44), so we are unable to apply any workaround for this service right now.

For example, this is how we are forced to specify the BuildVersion in such Dockerfiles:

```
#!BuildTag: packagename:%%VERSION%%-%%BUILD_FLAVOR%%-%RELEASE%
#!BuildVersion: %%VERSION%%
```

Using a service like this:

```
  <service name="replace_using_env" mode="buildtime">
    <param name="eval">
. /.build/build.data
BUILD_FLAVOR="${BUILD_FLAVOR:-elasticsearch7}"
echo "Building flavor $BUILD_FLAVOR"
PACKAGE_NAME="packagename-$BUILD_FLAVOR"
VERSION="$(
    find /usr/src/packages/SOURCES/repos \
        \( -name "$PACKAGE_NAME.rpm" -o -name "$PACKAGE_NAME-*.rpm" \) \
        -exec rpm -q --qf '%{version}\n' {} \; -quit
)"
echo "Building version $VERSION"
</param>
    <param name="file">Dockerfile</param>
    <param name="file">_service</param>
    <param name="var">BUILD_FLAVOR</param>
    <param name="var">VERSION</param>
  </service>
```

How could we resolve this issue?

**Comment by adrianschroeter** [comment] 2023-11-17 16:10
On Freitag, 17. November 2023, 13:26:41 CET Marcos Bjoerkelund wrote:
> @adrianschroeter By removing the `%` from the string, we were able to workaround the issue for some packages.
> 
> However, for other packages we are using `replace_using_env` to obtain the package version from a multi-flavored container build, and we are now facing the challenge where this service [imposes the usage of `%%` to replace environment variables](https://code.opensuse.org/package/obs-service-replace_using_env/blob/master/f/replace_using_env#_44), so we are unable to apply any workaround for this service right now.
> 
> For example, this is how we are forced to specify the BuildVersion in such Dockerfiles:
> 
> ```
> #!BuildTag: packagename:%%VERSION%%-%%BUILD_FLAVOR%%-%RELEASE%
> #!BuildVersion: %%VERSION%%
> ```
> 
> Using a service like this:
> 
> ```
>   <service name="replace_using_env" mode="buildtime">
>     <param name="eval">
> . /.build/build.data
> BUILD_FLAVOR="${BUILD_FLAVOR:-elasticsearch7}"
> echo "Building flavor $BUILD_FLAVOR"
> PACKAGE_NAME="packagename-$BUILD_FLAVOR"
> VERSION="$(
>     find /usr/src/packages/SOURCES/repos \
>         \( -name "$PACKAGE_NAME.rpm" -o -name "$PACKAGE_NAME-*.rpm" \) \
>         -exec rpm -q --qf '%{version}\n' {} \; -quit
> )"
> echo "Building version $VERSION"
> </param>
>     <param name="file">Dockerfile</param>
>     <param name="file">_service</param>
>     <param name="var">BUILD_FLAVOR</param>
>     <param name="var">VERSION</param>
>   </service>
> ```
> 
> How could we resolve this issue?

IMHO this is yet another issue as the change of the version of the source do not
happen when the source is changing at all. It only happens at build time.

So, OBS would never be able to estimate the correct version just by looking
at the source that way.

This is in general not solvable with OBS version-release mechanics, since there 
can be multiple versions for a single container source.

The only way, I can imagine to solve this is to maintain the rpm packages source
and the Dockerfile in the same OBS package.

-- 

Adrian Schroeter ***@***.***>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH, Frankenstraße 146, 90461 Nürnberg, Germany
(HRB 36809, AG Nürnberg) Geschäftsführer: Ivo Totev

**Comment by marcosbc** [comment] 2023-11-17 16:28
Note that, at this moment, we are getting `%%VERSION%% properly substituted in the Dockerfile at buildtime. And even if we add `BuildVersion: %%VERSION%%`, the _version_ field in the `.containerinfo` file contains the expected contents.

The only problem is OBS not being able to parse `BuildVersion: %%VERSION%%` when it comes to determine the release number for the reasons you mentioned above, and therefore always resetting it to 1.1. And currently we are forced to using this envvar format because of `replace_using_env`.

How can we solve this issue without needing building the Dockerfile in the same OBS package than the RPM? Do you think it would be best to contribute a new flag to `replace_using_env` to support a custom format for envvars? (e.g. such as underscores instead of %%).

**Comment by hennevogel** [comment] 2023-11-20 11:29
> Do you think it would be best to contribute a new flag to replace_using_env to support a custom format for envvars? (e.g. such as underscores instead of %%).

Yes

**Comment by adrianschroeter** [comment] 2023-11-20 12:02
no, please wait a bit more. We may can change this behaviour. But needs a bit more digging.

**Comment by adrianschroeter** [comment] 2023-11-27 07:19
this behaviouris changed now. The % cause turned out to be an escaping issue which is fixed now.

**Closed by adrianschroeter** 2023-11-27 07:19 UTC
