### ISSUE TITLE
webui binary view for multibuild not working

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#4854] opened 2018-04-13 07:29 UTC
See eg.

https://build.opensuse.org/package/binaries/openSUSE:Leap:15.0/000product:openSUSE-dvd5-dvd-x86_64/images

It shows 000 product instead of the requested 000product:openSUSE-dvd5-dvd-x86_64

**Comment by coolo** [comment] 2018-04-13 07:41
same problem as in #4802

**Comment by adrianschroeter** [comment] 2018-04-16 08:25
![](https://github.trello.services/images/mini-trello-icon.png) [Fix multibuild binary view](https://trello.com/c/Ihi8rRMj/1384-fix-multibuild-binary-view)

**Comment by hennevogel** [comment] 2018-04-16 09:05
So duplicate of  #4802

**Closed by hennevogel** 2018-04-16 09:05 UTC
Labels: Bug :skull:, Frontend 👻
