### ISSUE TITLE
apache2 not starting due to "WARNING: PassengerPreStart cannot occur within <VirtualHost> section"

### ISSUE THREAD

**Issue by johanneskastl** [openSUSE/open-build-service#14698] opened 2023-07-25 06:23 UTC
# Issue Description
apache2.service fails to start due to `WARNING: PassengerPreStart cannot occur within <VirtualHost> section`

Expected Result
============
apache2.service being started properly.

How to Reproduce
===============
1. install pattern OBS_Server on Leap 15.4 instance
2. run `/usr/lib/obs/server/setup-appliance.sh --force`
3. Check status and journal of apache2.service

```
$ sudo journalctl -lu apache2
Jul 25 08:12:45 obs systemd[1]: Starting The Apache Webserver...
Jul 25 08:12:45 obs start_apache2[18430]: WARNING: PassengerPreStart cannot occur within <VirtualHost> section
Jul 25 08:12:45 obs systemd[1]: apache2.service: Main process exited, code=exited, status=1/FAILURE
Jul 25 08:12:45 obs systemd[1]: apache2.service: Failed with result 'exit-code'.
Jul 25 08:12:45 obs systemd[1]: Failed to start The Apache Webserver.
Jul 25 08:12:46 obs systemd[1]: apache2.service: Unit cannot be reloaded because it is inactive.
```

Further Information
===============

```
$ grep Pass /etc/apache2/vhosts.d/obs.conf
# Passenger defaults
PassengerSpawnMethod "smart"
PassengerMaxPoolSize 20
        PassengerMinInstances 2
        PassengerPreStart https://api
        ProxyPass /v2 http://localhost:5352/registry
        ProxyPassReverse /v2 http://localhost:5352/registry
```

```
$ rpm -qa|grep obs|sort
obs-api-2.10.20-lp154.109.1.noarch
obs-api-deps-2.10.20-lp154.109.1.x86_64
obs-backend-testsuite-2.10.20-lp154.109.1.noarch
obs-bundled-gems-2.10.20-lp154.109.1.x86_64
obs-common-2.10.20-lp154.109.1.noarch
obs-server-2.10.20-lp154.109.1.noarch
obs-signd-2.5.10-lp154.1.1.x86_64
obs-worker-2.10.20-lp154.109.1.noarch
system-user-obsapidelayed-2.10.20-lp154.109.1.noarch
system-user-obsrun-2.10.20-lp154.109.1.noarch
system-user-obsservicerun-2.10.20-lp154.109.1.noarch
```

**Comment by hennevogel** [comment] 2023-07-25 11:20
Duplicate of #14350

**Closed by hennevogel** 2023-07-25 11:20 UTC
Labels: Packages :package:

**Comment by rhabacker** [comment] 2025-05-12 11:38
I checked this on an actual installation of obs unstable and recognized, that this issue is still existent in actual source code, see https://github.com/openSUSE/open-build-service/blob/b3372a8b1518c779d68f5a05b60c473112cc5389/dist/obs-apache24.conf#L63 and https://github.com/openSUSE/open-build-service/blob/b3372a8b1518c779d68f5a05b60c473112cc5389/dist/obs-apache2.conf#L61.

The mentioned attributes must be located outside the virtual host configuration.
