### ISSUE TITLE
[production][package#submit_request] Mysql2::Error: Incorrect string value: '\xF0\x9F\x98\xB1\xF0\x9F...' for column 'description' at ...

### ISSUE THREAD

**Issue by Ana06** [openSUSE/open-build-service#4623] opened 2018-03-06 15:25 UTC
package#submit_request threw this 7 times
<pre>
Mysql2::Error: Incorrect string value: &#39;\xF0\x9F\x98\xB1\xF0\x9F...&#39; for column &#39;description&#39; at row 1: INSERT INTO `bs_requests` (`description`, `creator`, `state`, `commenter`, `created_at`, `updated_at`, `number`) VALUES (&#39;- update to 1.4.3\r\n  * Fixed issues\r\n    - You can find issues and feature requests related to this \r\n      release on our roadmap\r\n  * User Interface\r\n    - FIX: Pagination used to be broken for some tables (#1273)\r\n  * Automation\r\n    - FIX: API calls changing only object relations and no \&quot;real\&quot;\r\n      property resulted in no change at all (#1315)\r\n- update to 1.4.2\r\n  * Fixed issues\r\n    - You can find issues and feature requests related to this \r\n      release on our roadmap\r\n  * Configuration rendering\r\n    - FIX: Caching had an influence on context-specific Custom \r\n      Variable rendering when those variables contained macros \r\n      (#1257)\r\n  * Sync\r\n    - FIX: The fix for #1223 caused a regression and broke Sync for
</pre>
[https://build.opensuse.org/package/submit_request/openSUSE:Factory/icingaweb2-module-director](https://build.opensuse.org/package/submit_request/openSUSE:Factory/icingaweb2-module-director)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5a9e9f9084f48f00061f9045)

**Comment by hennevogel** [comment] 2018-03-07 17:07
This is a duplicate of #3547

**Closed by hennevogel** 2018-03-07 17:07 UTC
Labels: Bug :skull:, Frontend 👻, PR welcome :two_hearts:
