### ISSUE TITLE
Cannot add or edit attributes via Web UI

### ISSUE THREAD

**Issue by afaerber** [openSUSE/open-build-service#1029] opened 2015-08-12 17:03 UTC
As previously reported, I was unable to add an openSUSE:DisableAutoSubmit attribute to Virtualization qemu package via the Web UI. Adding it via `osc meta attribute` worked okay (on openSUSE 13.2).

Similarly for editing, it said "Sorry you're not allowed to edit this Attrib", while `osc meta attribute` works as expected.

I am both project and package maintainer, so not being the direct maintainer can't be the problem here.

**Comment by hennevogel** [comment] 2015-08-13 10:09
This is a duplicate of #904

**Closed by hennevogel** 2015-08-13 10:09 UTC
