### ISSUE TITLE
support branching of scmsync'ed packages

### ISSUE THREAD

**Issue by dirkmueller** [openSUSE/open-build-service#14753] opened 2023-08-02 08:26 UTC
# Issue Description

Branching a package that is coming from scmsync is not possible, it fails with:

```
BuildService API error: failed to branch: <status code="404">
  <summary>_link: no such file</summary>
  <details>404 _link: no such file</details>
</status>
```

Expected Result
============
A branch project/package is created with the expanded sources of that point in time, so that the obs workflows and the like can use it for CI/CD purposes. Obviously SRs can still not be created for such packages, but that's entirely unrelated to branching imho.

How to Reproduce
===============
1. Go to 'Virtualization:containers', branch the package trivy
2. it should succeed

**Comment by hennevogel** [comment] 2023-08-02 09:09
Duplicate of #14743

**Closed by hennevogel** 2023-08-02 09:09 UTC
