### ISSUE TITLE
package#show loads the full history of the package

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#8002] opened 2019-07-31 10:11 UTC
There is some caching involved, but if you visit [openSUSE:Factory:Staging/dashboard ](https://build.opensuse.org/package/show/openSUSE:Factory:Staging/dashboard)  for the first time, it parses the full history of the package (according to backend_access.log) 

As it only wants to display the last entry, it should only fetch `_history?limit=1`

```time osc api /source/openSUSE:Factory:Staging/dashboard/_history?limit=1
real    0m0,716s

time osc api /source/openSUSE:Factory:Staging/dashboard/_history
real    0m4,243s

**Comment by hellcp** [comment] 2019-08-30 19:41
Hm, reading commits seems to only utilize cache according to:
https://github.com/openSUSE/open-build-service/blob/master/src/api/app/models/package.rb#L1487-L1489
which is used by:
https://github.com/openSUSE/open-build-service/blob/master/src/api/app/models/package.rb#L1279-L1296

However, I don't see an option to get a specific revision with `_history`, how would that work with anything but the latest revision (even then, the commit might happen while loading the view, limit=1 might not be enough for that case).

**Comment by hennevogel** [comment] 2023-02-21 18:17
It's has started to pull our SLI so Duplicate of #13871

**Closed by hennevogel** 2023-02-21 18:17 UTC
Labels: Frontend
