### ISSUE TITLE
Macro value inconsistencies - %gcc_version

### ISSUE THREAD

**Issue by afaerber** [openSUSE/open-build-service#5193] opened 2018-06-23 12:46 UTC
# Issue Description
On the openSUSE OBS instance, following the switch to `gcc8` as default C compiler package, the macro `gcc_version` has been updated in both places in [the openSUSE:Factory Project Config](https://build.opensuse.org/project/prjconf/openSUSE:Factory):

```
%define gcc_version 8
...
Macros:
...
%gcc_version 8
...
:Macros
```

Observation is that (Case C below) it is for some packages working correctly at RPM level, `%{gcc_version}` being read as `8`, whereas OBS is still treating it as its previous value of `7`. This leads to `cross-arm-none-gcc7` package getting pre-installed but the build failing due to `rpmbuild` expecting `cross-arm-none-gcc8`. Triggering a rebuild did not help.

Another observation (Case B below) is that for a different package both are being treated as its previous value of `7`. Package is not getting rescheduled either, remaining in "Build finished, but repository publishing is disabled" state.

Expected Result
============
1. `%{gcc_version}` should be read as `8` and the correct `BuildRequires` packages using `%{gcc_version}` installed for any subsequent builds.
2. If a variable is used in a `BuildRequires` and the value of that variable changes, all packages with such `BuildRequires` should get scheduled and built. If that dependency change does not make a difference, `build-compare` can discard the results.

How to Reproduce
===============
Case A - openSUSE:Factory x86_64 is GOOD
1. Verify the use of `BuildRequires:  cross-%{cross_arch}-gcc%{gcc_version}-bootstrap` (with `%cross_arch` as local define) in https://build.opensuse.org/package/view_file/openSUSE:Factory/newlib/cross-arm-none-newlib-devel.spec?expand=1
2. See in the build log that it installs `cross-arm-none-gcc8-bootstrap`: https://build.opensuse.org/build/openSUSE:Factory/standard/x86_64/cross-arm-none-newlib-devel/_log
3. Observe that build succeeds as expected.

Case B - openSUSE:Factory:ARM aarch64 is BAD
1. Verify that openSUSE:Factory:ARM does not overwrite `gcc_version` and should therefore inherit values from openSUSE:Factory: https://build.opensuse.org/project/prjconf/openSUSE:Factory:ARM
2. See in the build log that it installs `cross-arm-none-gcc7-bootstrap`: https://build.opensuse.org/build/openSUSE:Factory:ARM/standard/aarch64/cross-arm-none-newlib-devel/_log
3. See in the build log that build unexpectedly succeeds despite `7` still being used (i.e., `rpmbuild` used value `7`, too).
4. Observe the build status of the package: "Build finished, but repository publishing is disabled" (i.e., it is not getting rescheduled to build with `%{gcc_version}` as `8`, and having finished on Jun 11 the new macro value should've already been in effect)

Case C - hardware:boot aarch64 is BAD
1. Verify that hardware:boot does not overwrite `gcc_version`: https://build.opensuse.org/project/prjconf/hardware:boot
2. Verify the use of `BuildRequires:  cross-arm-none-gcc%{gcc_version}` in https://build.opensuse.org/package/view_file/hardware:boot/arm-trusted-firmware-rk3399/arm-trusted-firmware-rk3399.spec?expand=1
3. See in the build log that it installs `cross-arm-none-gcc7`: https://build.opensuse.org/build/hardware:boot/openSUSE_Factory_ARM/aarch64/arm-trusted-firmware-rk3399/_log
4. See in the build log that `rpmbuild` fails as follows:
```
[  387s] error: Failed build dependencies:
[  387s] 	cross-arm-none-gcc8 is needed by arm-trusted-firmware-rk3399-1.5-11.4.noarch
```

Further Information
===============
* https://build.opensuse.org/

**Comment by coolo** [comment] 2018-06-23 14:12
this is really something for the opensuse-factory mailing list and not a build service issue. The issue is (as you wrote) in how openSUSE:Factory is setup and this needs to be fixed by @DimStar77 or @nilxam

**Closed by coolo** 2018-06-23 14:12 UTC

**Comment by afaerber** [comment] 2018-06-23 14:14
@coolo I don't understand. What's wrong with the setup in openSUSE:Factory? As I pointed out, the values are correct there.

**Comment by afaerber** [comment] 2018-06-23 16:38
Confirming that disabling and re-enabling repositories fixed the issue in hardware:boot and in my home branch.

**Comment by coolo** [comment] 2018-06-24 07:15
I see - so most likely lost between the backends. Tough to debug now

**Comment by adrianschroeter** [comment] 2018-06-25 06:08
nah, prjconf changes don't lead to a full deep check for performance reasons.
