### ISSUE TITLE
[production][delayed_job#ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper] execution expired

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/open-build-service#3648] opened 2017-08-21 14:32 UTC
delayed_job#ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper threw this 5 times
<pre>
execution expired
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/599adc083e66930006a9c9cd)

**Comment by hennevogel** [comment] 2017-08-22 12:34
Duplicate of #3647

**Closed by hennevogel** 2017-08-22 12:34 UTC
Labels: Bug, Frontend
