### ISSUE TITLE
The new web interface for OBS has become very difficult and not pleasant to use

### ISSUE THREAD

**Issue by IlyaIndigo** [openSUSE/open-build-service#8009] opened 2019-08-01 08:49 UTC
https://bugzilla.suse.com/show_bug.cgi?id=1143760
The new web interface for OBS has become very difficult and not pleasant to use!
https://build.opensuse.org/project/show/home:13ilya

Everything became wide, empty, not compact, with very large paddings and margins.
selects became huge and wide, I don’t even perceive them as selects.

But most importantly, it stretches to almost the entire screen where it is not needed and there is emptiness in the center of the field of view, and the necessary information has to be found in the right and left edges of the screen.
Downscaling to 70% improves the appearance a little, but the font gets too small.

Please return the opportunity to switch to the old interface.

**Comment by hennevogel** [comment] 2019-08-01 09:25
Duplicate of #6587 

> Please return the opportunity to switch to the old interface.

The old interface is gone :-)

**Closed by hennevogel** 2019-08-01 09:25 UTC

**Comment by IlyaIndigo** [comment] 2019-08-01 09:47
> Duplicate of #6587
> 
> > Please return the opportunity to switch to the old interface.
> 
> The old interface is gone :-)

From git nothing can disappear.
Everything can be restored. :-)
