### ISSUE TITLE
[production][project#status] undefined local variable or method `c`

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/open-build-service#8206] opened 2019-08-29 13:30 UTC
project#status threw this 3 times
<pre>
undefined local variable or method `c&#39; for #&lt;#&lt;Class:0x0000561146b050d8&gt;:0x00007f7484ad2cd0&gt;
</pre>
[https://build.opensuse.org/project/status/openSUSE:Factory?utf8=%E2%9C%93&amp;project=openSUSE%3AFactory&amp;limit_to_fails=false&amp;include_versions=true&amp;filter_devel=All+Packages&amp;commit=Filter+results](https://build.opensuse.org/project/status/openSUSE:Factory?utf8=%E2%9C%93&amp;project=openSUSE%3AFactory&amp;limit_to_fails=false&amp;include_versions=true&amp;filter_devel=All+Packages&amp;commit=Filter+results)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5d3a299f93318600082d7d18)

**Comment by dmarcoux** [comment] 2019-08-29 13:34
I believe it's a duplicate of #6909

**Comment by DavidKang** [comment] 2019-08-29 13:39
right!

**Closed** 2019-08-29 13:39 UTC
Labels: Bug :skull:, Frontend
