### ISSUE TITLE
GitHub issue references (gh#foo/bar#42) are also parsed for other issue trackers

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/open-build-service#12074] opened 2022-01-12 15:01 UTC
If an issue such as `gh#OSInside/kiwi#1650` is mentioned in the description, it is parsed both as `gh#OSInside/kiwi#1650` as well as `i#1650`. Only the GitHub reference is correct.

Visible on e.g. https://build.opensuse.org/request/show/926196

**Comment by hennevogel** [comment] 2022-01-12 15:18
Duplicate of #12031

**Closed by hennevogel** 2022-01-12 15:18 UTC
