### ISSUE TITLE
[production][images#update] undefined method `add_child' for nil:NilClass

### ISSUE THREAD

**Issue by Ana06** [openSUSE/open-build-service#6256] opened 2018-11-14 09:41 UTC
images#update threw this 4 times
<pre>
undefined method `add_child&#39; for nil:NilClass
</pre>
[https://build.opensuse.org/kiwi_images/24000](https://build.opensuse.org/kiwi_images/24000)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5bc9d4eb0c6752000bc364af)

**Comment by Ana06** [comment] 2018-11-14 09:48
It seems related to https://github.com/openSUSE/open-build-service/pull/5851 :mag:

**Comment by adrianschroeter** [comment] 2018-11-20 08:14
keeps blocking code 15 templates

**Comment by dmarcoux** [comment] 2018-11-20 11:10
@adrianschroeter Do you have a Kiwi file with which I could reproduce this?

**Comment by adrianschroeter** [comment] 2018-11-20 12:43
On Dienstag, 20. November 2018, 12:10:19 CET Dany Marcoux wrote:
> @adrianschroeter Do you have a Kiwi file with which I could reproduce this?

  home:adrianSuSE:branches:openSUSE:Leap:15.0:Images opensuse-leap-image 

IIRC this is still the issue that the multiple preference sections were not 
handled.


-- 

Adrian Schroeter
SUSE Linux Products GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
email: adrian@suse.de

**Comment by dmarcoux** [comment] 2018-11-20 14:08
I cannot reproduce it locally with the Kiwi files from that project. Multiple preferences are handled for about 2 months now (since #5851 is merged)

**Closed** 2018-11-21 09:50 UTC
Labels: Bug :skull:, Frontend 👻, P2
