### ISSUE TITLE
Repositories with space not handled well on webui

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#12308] opened 2022-03-14 14:14 UTC
The 15.1 repo on https://build.opensuse.org/project/show/home:coolo isn't handled well. Clicking on the repository name gives internal error and links from the monitor page to live logs result in "no such repository".

And if you're curious: I'm not alone, the DB knows 62 repositories with space in 62 unique projects.

**Comment by hennevogel** [comment] 2022-03-14 14:32
Duplicate of #7021

**Closed as completed by hennevogel** 2022-03-14 14:32 UTC
