### ISSUE TITLE
Webui shows non-zero outgoing request number, but none exist

### ISSUE THREAD

**Issue by dcermak** [openSUSE/open-build-service#9194] opened 2020-03-09 10:16 UTC
# Issue Description

The OBS web ui displays that I have two outgoing requests:
![Screenshot_2020-03-09 openSUSE Build Service](https://user-images.githubusercontent.com/45594031/76203549-1ed03780-61f7-11ea-80d7-a823e48d3b23.png)

But when I click on the outgoing requests tab, none are displayed. Also, it appears that my user has no outgoing requests at all.

Expected Result
============
The webui should not display 2 outgoing requests when there are none

**Comment by dcermak** [comment] 2020-03-09 10:35
Turns out that the webui shows no outgoing requests at all, even if some **should** exist as I just created two and they don't show up in the list, but the counter increased to 4.

**Comment by DavidKang** [comment] 2020-03-09 10:37
@dcermak, the issue, is related to the datatable cache. If you look well, the pagination is on Page 2 of 1.

**Comment by dcermak** [comment] 2020-03-09 10:52
> @dcermak, the issue, is related to the datatable cache. If you look well, the pagination is on Page 2 of 1.

Indeed, when I click on previous, then the issue is gone. However, it would be nice if this state was impossible to reach in the first place.

Do you have a tracking issue for the pagination? If yes, then I'd close this issue.

**Comment by hennevogel** [comment] 2020-03-09 10:54
Duplicate of #7535

**Closed by hennevogel** 2020-03-09 10:54 UTC
