### ISSUE TITLE
provide project wide _service file mode override

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#2110] opened 2016-09-06 14:23 UTC
Factory packages require mode=disabled in _service files. For convenience however it would be good to have packages in the devel project be auto updated from e.g. github or use server side downloading of sources.

To avoid having to maintain a separate copy with mode=disabled OBS should provide a project wide override that just disables all services.

Submit requests to a project with disabled service runs would need to run the services on server side and submit a specific source state.

**Comment by lnussel** [comment] 2016-09-06 14:23
eg https://lists.opensuse.org/opensuse-factory/2016-08/msg00428.html

**Comment by adrianschroeter** [comment] 2016-09-08 06:22
Well disable *all* services is not wanted, since we rely on others for factory.

What you actually want is to select specific services (which are not in mode=disabled or =buildtime) and which rely on external resources to be disabled. We track already which services rely on external resources (therefore not reproducable) so catching them would be relative easy.

The bigger problem is that submit request usually don't copy the result of a service. So that would need an adaption here as well.

Needs a second though ....

**Comment by adrianschroeter** [comment] 2016-09-08 06:29
the problem would be that a branch of the package would re-run the service though.

Actually, I think your factory check comes from a time where a submit request accept did re-run the services in the target. But this is not the case anymore. So, why don't you just allow enables services these days now? You would get a copy of the generated sources in the devel project and it stays in your history.

We might need to think how to create maintenance updates if someone is branching a package using a service which is eq. pulling from master branch. One option would be that you try to find out if a non-fixed revision is used in your review scripts.

**Comment by KAMiKAZOW** [comment] 2020-02-17 22:15
Would be cool if that feature could be implemented before the request is old enough for Primary School.

**Comment by adrianschroeter** [comment] 2020-09-21 12:29
no answer since 4 years, closing.

**Closed by adrianschroeter** 2020-09-21 12:29 UTC
Labels: Feature
