### ISSUE TITLE
someone locked my packages ;(

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#1256] opened 2015-10-18 06:57 UTC
```
#~>osc rdelete openSUSE:Factory kernel-desktop -f -mdrop
Server returned an error: HTTP Error 400: Bad Request
Package is used by following packages as devel package: home:vmwareideas:kernel-bfs/kernel-desktop-bfs
```

There is no way for me to delete this package ;(

**Comment by adrianschroeter** [comment] 2015-10-19 07:34
yep, regression, could be there since refactoring of some coolo guy :) fixed in pull request now.

**Comment by coolo** [comment] 2015-10-27 08:15
what pull request?

I still can't delete kernel-desktop

**Comment by adrianschroeter** [comment] 2015-11-02 09:04
fixed with aca1ed8b0e0170f2bcbd453cec00e978a9e98779

**Closed by adrianschroeter** 2015-11-02 09:04 UTC
Labels: api, Bug, Regression

**Comment by coolo** [comment] 2015-11-04 07:13
it's gone! :)
