### ISSUE TITLE
project/status vanished

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#8562] opened 2019-10-11 09:22 UTC
My gem updater uses `curl -s -H 'Accept: application/json' 'https://build.opensuse.org/project/status/devel:languages:ruby:extensions?include_versions=true&limit_to_fails=false'` - this returns a 404 now

**Comment by vpereira** [comment] 2019-10-11 11:12
That's not a regression. The URL changed and now it looks like  `curl -s -H 'Accept: application/json' 'https://build.opensuse.org/projects/devel:languages:ruby:extensions/status?include_versions=true&limit_to_fails=false' ` now reaching the right route, I get a 500. Which feature is that? AFAIK we don't have/support json API. Would you mind to explain to me what is that about @coolo ?

**Comment by coolo** [comment] 2019-10-11 12:06
Well, this is not the API - this is the webui:

https://github.com/openSUSE/open-build-service/blob/master/src/api/app/controllers/webui/projects/status_controller.rb#L34

**Comment by vpereira** [comment] 2019-10-11 12:14
> Well, this is not the API - this is the webui:

sure, but you are not accessing it in the UI, not testing it in the feature spec.. I wonder if we can just drop this code, add an XML endpoint and you build the necessary logic in the client side?

**Comment by coolo** [comment] 2019-10-11 12:26
https://github.com/openSUSE/open-build-service/issues/8568 for the 500 btw

**Comment by vpereira** [comment] 2019-10-11 13:00
so we can close it, since we are tracking the issue on #8568

**Closed by vpereira** 2019-10-11 13:00 UTC
Labels: Bug :skull:, Frontend
