### ISSUE TITLE
Download patch files from file view

### ISSUE THREAD

**Issue by muelli** [openSUSE/open-build-service#2033] opened 2016-08-16 09:57 UTC
I'm looking at https://build.opensuse.org/package/show/GNOME:Apps/gnome-keysign and I'm interested in exploring patches and eventually downloading them.

I click e.g. "gnome-keysign-gpg-2.1.patch" and after some exploration I want to download it. However, on the page https://build.opensuse.org/package/view_file/GNOME:Apps/gnome-keysign/gnome-keysign-gpg-2.1.patch?expand=1  it doesn't offer me a download button.

On the project page (i.e. https://build.opensuse.org/package/show/GNOME:Apps/gnome-keysign) there is a download button which links to https://build.opensuse.org/source/GNOME:Apps/gnome-keysign/gnome-keysign-gpg-2.1.patch?rev=f1795e53a1d3d702628e428215798f56 but it doesn't let me download the file because it just brings me back to the project overview.

I expected to be able to download patches easily from both the project and the file view.

**Comment by bgeuken** [comment] 2016-08-16 15:56
That currently only works for users that are logged in. Which is a bug.

The expected behaviour for anonymous users would be to have a working download link for simple files, but not for tarballs.

**Comment by bgeuken** [comment] 2016-08-16 15:57
Thanks for reporting this.

**Comment by hennevogel** [comment] 2016-08-19 10:28
This is a duplicate of #1940

**Closed by hennevogel** 2016-08-19 10:28 UTC
Labels: Bug, frontend, P3
