### ISSUE TITLE
webui hides _link

### ISSUE THREAD

**Issue by bmwiedemann** [openSUSE/open-build-service#5394] opened 2018-07-18 10:02 UTC
# Issue Description
The OBS web-UI is not showing the "show unexpanded" link under certain circumstances.

Expected Result
============
https://build.suse.de/package/show/Devel:Cloud:8:Staging/openstack-horizon-plugin-freezer-ui
should show "Links to openSUSE.org:Cloud:OpenStack:Pike" on the top-right.

"show unexpanded" should link to
https://build.suse.de/package/show/Devel:Cloud:8:Staging/openstack-horizon-plugin-freezer-ui?expand=0
I Want to be able to see the _link file

**Comment by hennevogel** [comment] 2018-07-18 10:06
Duplicate of #3138

**Closed by hennevogel** 2018-07-18 10:06 UTC
