### ISSUE TITLE
"Detailed Information About $package" page - links in "Requires" table not working

### ISSUE THREAD

**Issue by eliroca** [openSUSE/open-build-service#13903] opened 2023-02-27 11:21 UTC
# Issue Description
"Detailed Information About $package" page - links in "Requires" table do not work

Expected Result
============
Links to packages should work.

How to Reproduce
===============
1. Go to https://build.opensuse.org/package/show/games:tools/lutris
2. Click on any repository https://build.opensuse.org/package/binaries/games:tools/lutris/openSUSE_Tumbleweed
3. Click on any Details https://build.opensuse.org/package/binary/games:tools/lutris/openSUSE_Tumbleweed/x86_64/lutris-0.5.12-80.11.noarch.rpm
4. Click on any link in Requires table https://build.opensuse.org/package/dependency/games:tools/lutris?dependant_name=fdupes&dependant_project=openSUSE%3ATumbleweed&dependant_repository=dod&filename=lutris-0.5.12-80.11.src.rpm&repository=openSUSE_Tumbleweed
5. See error  "Architecture '' is invalid"

Further Information
===============
![2023-02-27-OBS](https://user-images.githubusercontent.com/42994510/221550860-bbbd6304-c6fb-428b-adfa-8441b773500e.gif)

**Comment by hennevogel** [comment] 2023-02-27 12:04
Duplicate of #13746

**Closed by hennevogel** 2023-02-27 12:04 UTC
