### ISSUE TITLE
Styles are broken when running feature specs with the capybara mobile driver

### ISSUE THREAD

**Issue by danidoni** [openSUSE/open-build-service#10170] opened 2020-09-18 13:19 UTC
# Styles are broken when running feature specs with capybara
Our CircleCI runs some of the beta feature specs under mobile emulation. To do so, it sets the `CAPYBARA_DRIVER=mobile` environment variable before running the feature specs.

While troubleshooting [some errors in our specs](https://app.circleci.com/pipelines/github/saraycp/open-build-service/688/workflows/52fc22bf-b364-4c2a-919b-8f37866c96cb/jobs/4065/parallel-runs/1) we found out that capybara was unable to click on some elements from a page because they where below an oversized Open Build Service logo:

![capybara-screenshot](https://user-images.githubusercontent.com/2650/93601702-e093ac00-f9c1-11ea-84fe-84a5b9c0537f.png)

The logo size is clearly wrong. It is set via CSS rules, and by looking at the rest of the elements in that page, looks like some other CSS rules are broken too. 

The broken styles are interfering with the proper execution of the feature specs. On mobile environments the oversized logo covers the half of the screen, hiding elements to the Capybara runner.

Note that Using the `:desktop` capybara driver also breaks the styles. Note the oversized logo and the search box in the capture below.

![Screenshot from 2020-09-18 14-25-16](https://user-images.githubusercontent.com/2650/93601950-38321780-f9c2-11ea-9c3e-80749dfa7f97.png)

Expected Result
============
The capybara driver should not break the styles of the application.

How to Reproduce
===============
1. Put a `docker-compose.selenium.yml` in the root of the project. You can find the contents for the file below.
2. Use this command line to open a session inside the dockerized project: `docker-compose -f docker-compose.yml -f docker-compose.selenium.yml run --service-ports --use-aliases --rm frontend bash -l`
3. Open a Vnc viewer (I used TigerVNC Viewer) pointing to localhost.
3. Run `export CAPYBARA_DRIVER=mobile` inside the dockerized session.
3. Run `rspec spec/features/beta/webui/projects/status_spec.rb` inside the dockerized session.
4. The application under test shows broken styles.

Further Information
===============

Use this `docker-compose.selenium.yml` to reproduce the issue.

```docker
version: "2.1"
services:
  frontend:
    depends_on:
      - selenium
    environment:
      RSPEC_HOST: frontend
  selenium:
    image: selenium/standalone-chrome-debug
    environment:
      VNC_NO_PASSWORD: 1
    ports:
      - 5900:5900
```

**Comment by danidoni** [comment] 2020-10-09 07:40
I've been digging a bit more and looks like the capybara specs use outdated precompiled assets. Next is make the capybara specs `clobber` and `precompile` assets before running...

**Comment by dmarcoux** [comment] 2021-03-11 15:19
I can consistently reproduce this error:

1. Enable the `responsive_ux` feature flag for beta users only
```ruby
# Inside a rails console
Flipper.disable(:responsive_ux) # just to be sure it's enabled only for beta users
Flipper.enable(:responsive_ux, :beta)
```
2. As an anonymous user, you should see the broken UI with the huge logo
3. Log in as Admin:
- If you are already in the beta program, the UI will now be fine
- If you are not in the beta program, it is still broken. Join the beta program to get rid of the broken UI

**Comment by danidoni** [comment] 2021-03-12 08:52
> To conclude, I don't think it has anything to do with the mobile capybara driver. It's about feature flags and how we set a class on the body. If the class is missing, then the UI will break to various degrees.

Yes, I know the capybara driver is not the responsible for the issue. It's just that I could reproduce it when using the capybara driver. I found out that we were missing some classes but couldn't find the reason.

Thanks @dmarcoux!

**Comment by dmarcoux** [comment] 2021-03-15 08:33
I think we can close this issue since it's happening only when we're not properly setting up the feature flags in the specs.

**Closed** 2021-03-15 13:25 UTC
Labels: Bug, Frontend, Test Suite / CI :syringe:
