### ISSUE TITLE
Group members can't reopen by_group declines

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#2923] opened 2017-03-31 13:01 UTC
IBS Request 130203 (just a test request by @lnussel) is declined  
<review state="declined" when="2017-03-31T12:52:56" who="sle-changelog-checker" by_group="sle-changelog-checker">

I'm part of that group, but trying to reopen the review gives me:
/request/130203?newstate=new&by_group=sle-changelog-checker&cmd=changereviewstate

-> 
```
<status code="review_change_state_no_permission">
  <summary>The request is neither in state review nor new</summary>
</status>
```

This kind of breaks the SUSE development processes, as every reopen by bots has to be done by admins :(

**Comment by adrianschroeter** [comment] 2017-04-04 11:33
you want to reopen a review of a request which is already processed? (accepted)

Are you sure that this is a new behaviour?

**Comment by Ana06** [comment] 2017-04-04 11:54
@adrianschroeter I think @coolo mean a declined request, not an accepted one. :thinking:

**Comment by adrianschroeter** [comment] 2017-04-04 13:02
still, why should a reopen of a review work on a declined request? And what should happen here? checking all review states and implicit reopen the request also?

The request owner might disagree, so I think it is okay that a reopen is only working on the request level. Just accept or declining reviews of a request in final state is supported.

**Comment by lnussel** [comment] 2017-04-05 11:58
The use case is a bot declining requests. Persons other than maintainers in the source and target project need a way to override the bot, ie reopen the request. We tried that by putting the bot and those persons into the same group for review. It's not possible right now for members of the group to undo the decline of the bot though.

**Comment by adrianschroeter** [comment] 2017-04-05 12:35
then assign the bot to some group and add the other people there as well.

However, this is not solving the problem when the request is already in some more or less final state. 

We could extend the code handling the reopen to check if this is the only declined review and reopen the request in that case ...

**Comment by coolo** [comment] 2017-04-05 12:44
decline is not a final state

**Comment by coolo** [comment] 2017-04-05 12:44
"then assign the bot to some group and add the other people there as well." - are you even reading the reports you turn down?

**Comment by adrianschroeter** [comment] 2017-04-05 13:19
The issue is not closed and there is a proposal written:

"We could extend the code handling the reopen to check if this is the only declined review and reopen the request in that case ... "

**Comment by adrianschroeter** [comment] 2022-10-21 11:37
Should be solved by https://github.com/openSUSE/open-build-service/pull/13253

**Comment by dmarcoux** [comment] 2022-12-13 12:40
https://github.com/openSUSE/open-build-service/pull/13253 is merged

**Closed by dmarcoux** 2022-12-13 12:40 UTC
Labels: Bug, Frontend
