### ISSUE TITLE
WebUI Maintennace incidents overview page no longer shows incident request status

### ISSUE THREAD

**Issue by andreasstieger** [openSUSE/open-build-service#1792] opened 2016-05-10 19:03 UTC
on the maintenance incident overview page:
https://build.opensuse.org/project/maintenance_incidents/openSUSE:Maintenance

The incident status is no longer shown in the 5th column:

- Yellow flag for a maintenance release request in state "review"
- Green flag for a maintenance release request in state "new"
- Red flag for a maintenance release request in state "decline"

**Comment by bgeuken** [comment] 2016-05-17 13:34
@adrianschroeter That seems to be caused by the number change. The [code](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/views/webui/project/_incident_table_entries.html.erb#L42) is fetching request ids, but uses the result as it where numbers not ids: ```BsRequest.where(number: rqs_out)```. And without finding a match there isn't any flag icon.

**Comment by adrianschroeter** [comment] 2016-05-18 08:15
good spot. Fixed in git and on build.opensuse.org

**Closed by adrianschroeter** 2016-05-18 08:15 UTC
Labels: Bug, frontend, P2, Regression
