### ISSUE TITLE
request cleanup still gets invalid history entries after refactoring

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#1504] opened 2016-02-04 17:25 UTC
Accepting a request with cleanup option is still getting invalid "revoke" history elements. This happens since the request cleanup got moved into project/package containers most likely.

The attached test case shows the problem:

**Comment by adrianschroeter** [comment] 2016-02-04 17:27
I shall convert the patch to a PNG????? Grrr....

--- a/src/api/test/functional/request_controller_test.rb
+++ b/src/api/test/functional/request_controller_test.rb
@@ -2411,6 +2411,12 @@ XML
     post "/request/#{id}?cmd=changestate&newstate=accepted&force=1"
     assert_response :success
 
+    get "/request/#{id}?withfullhistory=1"
+    assert_response :success
+    # only entries are for request created and accepted. The cleanup must not be visible
+    # as revoke or decline
+    assert_xml_tag( :tag => 'history', :attributes => { matches: '2' } )
+
     # the link got transfered
     get '/source/DummY/pack2.NEW/_link'
     assert_response :success

**Comment by hennevogel** [comment] 2016-02-10 09:51
Duplicate of #1428

**Closed by hennevogel** 2016-02-10 09:51 UTC
Labels: api, Bug, P2, Regression
