### ISSUE TITLE
webui doen't detect linked package

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#3948] opened 2017-10-05 08:45 UTC
https://build.opensuse.org/package/show/openSUSE:Leap:15.0:Rings:0-Bootstrap/attr has a _link but the webui doesn't offer the 'show unmerged sources' button.

**Comment by ChrisBr** [comment] 2017-10-09 08:06
@lnussel I can't see a _link file?

**Comment by lagartoflojo** [comment] 2017-10-20 11:29
That's precisely the bug :)

Check it like this: https://build.opensuse.org/package/show/openSUSE:Leap:15.0:Rings:0-Bootstrap/attr?expand=0 and you will see the `_link` file.

**Comment by nilxam** [comment] 2017-10-31 07:13
Another example:

maxlin_factory@tigercity:~> osc api /source/openSUSE:Leap:15.0:Rings:2-TestDVD/webkitgtk
<directory name="webkitgtk" rev="2" vrev="3" srcmd5="ced60c5ce0e81305ee8a087e4281217f">
  <linkinfo project="openSUSE:Leap:15.0" package="webkitgtk" srcmd5="526cc9b2cfceb2311b75dd07882265e8" xsrcmd5="3e2798b5abf64fcee4c4053c6098a229" lsrcmd5="ced60c5ce0e81305ee8a087e4281217f" />
  <serviceinfo code="succeeded" xsrcmd5="c434af3ca12bbbe294e75ee7372d005a" />
  <entry name="_link" md5="173c7705e83f683811813a3a6e866b41" size="454" mtime="1496419351" />
</directory>
maxlin_factory@tigercity:~> osc linkpac -f openSUSE:Leap:15.0 webkitgtk openSUSE:Leap:15.0:Rings:2-TestDVD webkitgtk
forced overwrite of existing _link file
Creating _link... Done.
maxlin_factory@tigercity:~> osc api /source/openSUSE:Leap:15.0:Rings:2-TestDVD/webkitgtk
<directory name="webkitgtk" rev="3" vrev="4" srcmd5="cfa7d93a20055dc30910bc316d3d1661">
  <linkinfo project="openSUSE:Leap:15.0" package="webkitgtk" srcmd5="526cc9b2cfceb2311b75dd07882265e8" xsrcmd5="fffa4621a18d19a37f6f84f4de524746" lsrcmd5="cfa7d93a20055dc30910bc316d3d1661" />
  <entry name="_link" md5="173c7705e83f683811813a3a6e866b41" size="454" mtime="1496419351" />
</directory>

**Comment by JanZerebecki** [comment] 2018-04-04 13:38
Duplicate of #673?

**Comment by hennevogel** [comment] 2018-04-09 10:56
> Duplicate of #673?

Yes

**Closed by hennevogel** 2018-04-09 10:56 UTC
Labels: Bug :skull:, Frontend 👻
