### ISSUE TITLE
Changing flags in webui is not working anymore

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#2007] opened 2016-08-11 09:32 UTC
When changing a flag the webui redirects to an unknown URL.  Tested to disable global and architecture specfic flag with current git master.

It is also possible to click on the "Disable" popup when not logged-in which creates a not nice "nilClass" error notify.

Not routed URLs are for example:

https://build-test.opensuse.org/flag/OBS:Server:Unstable/obs-service-tar_scm?architecture=x86_64&flag=build&status=disable

https://build-test.opensuse.org/flag/OBS:Server:Unstable/obs-service-tar_scm?architecture=&flag=build&status=disable

**Comment by hennevogel** [comment] 2016-08-11 12:57
Duplicate of #1927. The urls are POST not GET :-)

**Comment by bgeuken** [comment] 2016-08-12 08:33
@hennevogel @adrianschroeter
I think that's 2 different issues. One is that pundit message is worded incorrectly in case of exceptions. That's #1927.
```
    message = "Sorry, you are not authorized to " +
              (exception.message ? "#{pundit_action} this #{exception.record.class}." : "perform this action.")
```

The other one is that changing the flags of a package is failing due to a 404. That's this issue. Changing project flags works btw.

**Comment by hennevogel** [comment] 2016-08-12 11:47
So this is also new...

**Comment by bgeuken** [comment] 2016-08-12 12:11
We only test the project flags right now. Not the package flags

**Comment by Mailaender** [comment] 2016-08-14 16:13
This bug will schedule a lot of useless builds even if the user is careful. Compare https://github.com/openSUSE/open-build-service/issues/586.

**Closed** 2016-08-15 12:04 UTC
Labels: Bug, frontend, P2, Regression

**Comment by Zenitur** [comment] 2016-08-17 10:05
Wasn't fixed.

Now I can set "Don't publish a package", but it is in repository anyway.

[Look there](http://download.opensuse.org/repositories/home:/linux4humans:/qt5/SLE_11_SP4/src/) You can see much of X11 libs, but [I've hide them](https://build.opensuse.org/repositories/home:linux4humans:qt5/xorg-x11-libICE).They're were rebuilt without libxcb-xlib.la, and the end user not required to install that. So I need hide these X11 libs.

**Comment by hennevogel** [comment] 2016-08-17 10:37
@Zenitur you can wipe the binaries with `osc wipebinaries`

**Comment by Zenitur** [comment] 2016-08-17 11:20
@hennevogel thank you!
