### ISSUE TITLE
[production][request#changerequest] Mysql2::Error: Data too long for column 'payload' at row 1: INSERT INTO `events` (`eventtype`, `p...

### ISSUE THREAD

**Issue by mdeniz** [openSUSE/open-build-service#5830] opened 2018-09-11 08:16 UTC
request#changerequest threw this 3 times
<pre>
Mysql2::Error: Data too long for column &#39;payload&#39; at row 1: INSERT INTO `events` (`eventtype`, `payload`, `created_at`, `updated_at`) VALUES (&#39;Event::RequestStatechange&#39;, &#39;{\&quot;author\&quot;:\&quot;mcepl\&quot;,\&quot;comment\&quot;:\&quot;You are removing stuff from changelog that is already integrated in tw, that aint acceptable by the changelog checking bots.\&quot;,\&quot;description\&quot;:\&quot;- Add multibuild to allow running tests.\\r\\n- specfile:\\r\\n  * updated pytest version, specified pytz version (from setup.py)\\r\\n- update to version 3.71.0:\\r\\n  * many changes, see https://hypothesis.readthedocs.io/en/latest/changes.html\\r\\n- Clean up SPEC\\r\\n- Add %check section, but make it disabled per default (circular\\r\\n  dependency on pytest)\\r\\n- Drop the pytest-xdist dependency to build on Leap 42.3, as it\\r\\n  does not run tests it was quite pointless\\r\\n- update to version 3.66.6:\\r\\n  * This patch ensures that Hypothesis fully supports Python 3.7, by\\r\\n    upgrading from_type() (issue #1264) and fixing
</pre>
[https://build.opensuse.org/request/changerequest](https://build.opensuse.org/request/changerequest)"

~~[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b963b209fc957001205bf9b)~~

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5c699f9e21614c000d235de4)

**Comment by adrianschroeter** [comment] 2018-09-13 14:37
seems to block some users, so increasing priority

**Comment by adrianschroeter** [comment] 2018-09-13 15:19
no regression, so rating it down.

**Comment by hennevogel** [comment] 2018-09-18 16:13
We need a length validation on `BsRequest.description` to make sure this fits into the resulting `Event`...

**Comment by hennevogel** [comment] 2019-02-04 20:12
Does not happen anymore...

**Comment by eduardoj** [comment] 2019-02-27 16:53
It seems it happens again. Link to Errbit added in the description of the issue.

**Comment by eduardoj** [comment] 2019-05-21 12:16
Duplicate of #5245. Closing.

**Closed by eduardoj** 2019-05-21 12:16 UTC
Labels: Bug :skull:, Frontend 👻, P3
