### ISSUE TITLE
webui: unspecific message "There has been an internal error"

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#11301] opened 2021-06-28 14:53 UTC
When logged in, calling up

https://build.opensuse.org/package/binary/GNOME:Next/at-spi2-core/openSUSE_Factory/x86_64/typelib-1_0-Atspi-2_0-2.40.2-360.3.x86_64.rpm

with a web browser just yields a red box:
```
There has been an internal error. Please try again.
```
This error message is totally unspecific. Please improve it.

**Comment by dmarcoux** [comment] 2021-06-29 14:40
I had a quick look and this is what I've found so far.

I suspect it's the following line which is causing a `Backend::Error`:

https://github.com/openSUSE/open-build-service/blob/8645a05b672220c7236b09b23f0e1c654456f06e/src/api/app/controllers/webui/package_controller.rb#L179 

It's then caught by this `rescue_from` block in `Webui::RescueHandler`:

https://github.com/openSUSE/open-build-service/blob/8645a05b672220c7236b09b23f0e1c654456f06e/src/api/app/controllers/concerns/webui/rescue_handler.rb#L21-L28

Somehow, the error is not reported to Errbit... this is weird.

**Comment by hennevogel** [comment] 2021-06-29 14:43
> Somehow, the error is not reported to Errbit... this is weird.

What is catched, may never be reported.

![What is catched, may never be reported.](https://media.giphy.com/media/FYrnftEWTRKtW/giphy.gif)

**Comment by dmarcoux** [comment] 2021-06-29 20:00
It should be reported because there is `Airbrake.notify(exception)` in that `rescue_from` block.

**Comment by eduardoj** [comment] 2024-08-21 14:52
I tried to reproduce the error without success. The codebase has been refactored several times since the issue was reported, so I'll close the issue.

Please reopen it if you still encounter this issue.

**Closed by eduardoj** 2024-08-21 14:52 UTC
Labels: Bug, Frontend
