### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#791] opened 2014-09-22 14:42 UTC
Adding a `<access><disable/></access>` line to a prjmeta results in osc outputting the following:

```
BuildService API error: change_project_protection_level (403)
admin rights are required to raise the protection level of a project (it won't be safe anyway)
```

As far as I am aware, I do have administrator rights.
Second, if it makes a stab at "it won't be safe", it should really really tell why it won't be safe.

**Comment by bgeuken** [comment] 2015-11-24 13:06
Still happening. In the ui this results in a "Project::ForbiddenError" error message

**Comment by bgeuken** [comment] 2015-11-24 13:16
@mlschroe Could you have a look at this?

**Comment by DavidKang** [comment] 2017-11-07 09:55
@mlschroe, ping!

**Comment by bgeuken** [comment] 2018-08-15 05:51
Can't reproduce it anymore. This has been fixed by now.

**Closed by bgeuken** 2018-08-15 05:51 UTC
Labels: Bug :skull:, Frontend 👻, P3
