### ISSUE TITLE
build failure log returns 500 on a project with git src.opensuse.org backend

### ISSUE THREAD

**Issue by lkocman** [openSUSE/open-build-service#16193] opened 2024-05-24 14:19 UTC
# Issue Description
Unable to see log of a build failure on project with src.opensuse.org scm backend (openSUSE:Leap:16.0:Images).

Expected Result
============
Try to see a build failure log of a package under src.opensuse.org in OBS. In my case Leap-release which is hosted in https://src.opensuse.org/openSUSE/Leap

How to Reproduce
===============
1. Go to https://build.opensuse.org/project/monitor/openSUSE:Leap:16.0:Images?arch_x86_64=1&defaults=0&failed=1&repo_standard=1
2. Click on build failure
3. error 500 appears (same happens for aarch64)

![image](https://github.com/openSUSE/open-build-service/assets/510119/a357ba79-43bf-4ffb-b771-e96c7868f600)
![image](https://github.com/openSUSE/open-build-service/assets/510119/2e270ca1-f6f9-4872-9a91-d5436fde0f3a)

Further Information
===============
* Project openSUSE:Leap:16.0:Images is set up with src.opensuse.org as scm backend

This makes debugging of build failures almost impossible :-)

**Comment by eduardoj** [comment] 2024-05-24 15:07
Duplicate of #13176. Closing.

**Closed by eduardoj** 2024-05-24 15:07 UTC
