### ISSUE TITLE
Source services occasionally fail with "See docker run --help"

### ISSUE THREAD

**Issue by lbeltrame** [openSUSE/open-build-service#2166] opened 2016-09-21 08:17 UTC
I have automated updating via _service on some projects of the KDE: hierarchy on the openSUSE OBS, and occasionally (once per day, usually) I see that some packages are in the `broken` state. The cause for the broken state is given as `See docker run --help`.

Usually re-running the service resolves the issue. 

An example _service file among those used: https://build.opensuse.org/package/view_file/KDE:Unstable:Frameworks/kcoreaddons/_service?expand=1

**Comment by adrianschroeter** [comment] 2016-09-22 09:13
osc api "/source/KDE:Unstable:Frameworks/kcoreaddons/_serviceerror?rev=88e895b58c8e8742334a982391eccfd0"
service tar_scm failed:
docker: Error response from daemon: Conflict. The name "/src-service-30404" is already in use by container 8b432a1382ee5742ca8aa2f3fdd1722789c3c1458d7598294852bd0ec2cc8c79. You have to remove (or rename) that container to be able to reuse that name..
See 'docker run --help'.

**Comment by M0ses** [comment] 2016-09-22 20:35
Problem should be fixed with https://github.com/openSUSE/open-build-service/pull/2176 

If you experience this problem again please leave a comment with my name and I will reopen it

**Comment by lbeltrame** [comment] 2016-11-05 13:19
@M0ses I occasionally see it still, usually when things are run in quick succession (~1 second between "remoterun" calls).

**Comment by M0ses** [comment] 2016-11-14 16:48
I could not reproduce this error, also I have seen these messages in the log. Anyway I changed the docker setup. I don`t see the messages in the logs any longer, so I´m closing this issue again.

Please comment if you see this problem again

**Closed by M0ses** 2016-11-14 16:48 UTC
Labels: backend, Bug, P2, Regression
