### ISSUE TITLE
Feature request: show linked packages over interconnects similar to branches

### ISSUE THREAD

**Issue by frispete** [openSUSE/open-build-service#4850] opened 2018-04-12 14:51 UTC
Given a local OBS, interconnected with openSUSE build service and others (Packman), it would be nice to see the link in the web frontend, similar to locally linked packages.

Even greater would be an additional diff, if content differs.

**Comment by adrianschroeter** [comment] 2018-04-27 08:27
doesn't matter if link or branch, it is a general bug regression when the link can not be reached direct.

**Comment by hennevogel** [comment] 2018-05-02 14:35
So a duplicate of #4916 4916?

**Comment by hennevogel** [comment] 2018-05-04 11:40
@frispete please open separate issues for distinct problems. TIA

**Closed by hennevogel** 2018-05-04 11:40 UTC
Labels: Bug :skull:, Frontend 👻
