### ISSUE TITLE
api /configuration and configuration.xml different

### ISSUE THREAD

**Issue by azouhr** [openSUSE/open-build-service#9261] opened 2020-03-20 08:49 UTC
I am trying to add a s390x scheduler to my local obs appliance. I found that this probably should be done from the API with adding s390x to the schedulers. However, after doing so the scheduler is not started.

Instead, the configuration.xml from /srv/obs/configuration.xml is used, which seems to be unaffected from the change I did to the API /configuration.

Expected Result
============
After adding an architecture to  API /configuration, the scheduler for that architecture should be added.

How to Reproduce
===============
1. Install OBS Appliance
2. Get configuration: osc api /configuration > configuration.xml
3. update xml file and add new architecture
4. Upload configuration: osc api /configuration -T configuration.xml
5. Restart obsscheduler service and check /srv/obs/log for the architecture specific log

Further Information
===============
* Using OBS Server from Unstable Project, current version: 2.10.1 Release lp151.23.1

**Comment by hennevogel** [comment] 2020-03-20 10:17
hey @azouhr are your background jobs running? We are writing out the configuration file with them. What is the output of 

`systemctl list-dependencies obs-api-support.target`

@mlschroe I guess a changed config would still need a manual restart?

**Comment by azouhr** [comment] 2020-03-20 12:42
# systemctl list-dependencies obs-api-support.target
obs-api-support.target
● ├─obs-clockwork.service
● ├─obs-delayedjob-queue-consistency_check.service
● ├─obs-delayedjob-queue-default.service
● ├─obs-delayedjob-queue-issuetracking.service
● ├─obs-delayedjob-queue-mailers.service
● ├─obs-delayedjob-queue-project_log_rotate.service
● ├─obs-delayedjob-queue-quick@0.service
● ├─obs-delayedjob-queue-quick@1.service
● ├─obs-delayedjob-queue-quick@2.service
● ├─obs-delayedjob-queue-releasetracking.service
● ├─obs-delayedjob-queue-staging.service
● └─obs-sphinx.service
(all of them green)

I actually even restarted the whole appliance after performing the change. The new entry reappeared in the API /configuration, but still did not appear in bs_admin --show-scheduler-architectures. However, the start script /usr/sbin/obsscheduler checks for configured architectures with bs_admin --show-scheduler-architectures and therefore did not start the s390x scheduler.

**Comment by eduardoj** [comment] 2022-05-10 11:45
@azouhr, you most probably got hit by the how workers' status update was working before merging #12543.

I have followed your steps on a recent appliance, with an updated `obs-server` and `obs-api` packages, and I couldn't reproduce your issue.

I close this issue. Please feel free to open it again if it still happens in your environment. Just make sure you have updated `obs-server` and `obs-api` packages, from OBS:Server:Unstable.

**Closed by eduardoj** 2022-05-10 11:45 UTC
Labels: Bug, Backend
