### ISSUE TITLE
Overly long comment causes crash instead of validating length

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/open-build-service#3614] opened 2017-08-16 14:12 UTC
Issue/Feature description
====================

Overly long comment causes crash instead of validating length.

Expected result
============

Not crash and produce proper error.

How to Reproduce
===============

Post long comment, like https://gist.githubusercontent.com/jberry-suse/d4534e57657fcfacaffdbe1591a11abe/raw/58a01b61fcefd9e38ce3e8842fbf1da01edeca92/openSUSE:Factory:Staging:adi:59.comment.

**Comment by hennevogel** [comment] 2017-08-16 14:51
duplicate of #3584

**Closed by hennevogel** 2017-08-16 14:51 UTC
