### ISSUE TITLE
"open requests" in overview page can be broken now

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#1232] opened 2015-10-14 09:30 UTC
webui controller has conflicting usage of @requests variable. One time with use role definition and one time without. The project overview page should be never use specific but showing the project state.

Seems to be a regression from 8b4d426e . will apply hotfixes for that but we need a testcase in any case.

**Comment by adrianschroeter** [comment] 2015-10-15 05:56
JFYI, the hotfix is also applied on build.opensuse.org now. But we should fix this before next deployment

**Comment by hennevogel** [comment] 2015-10-19 14:01
What's the hotfix?

**Comment by adrianschroeter** [comment] 2015-10-19 14:04
using "false" in the 

 reqs = @project.request_ids_by_class(false)

line in app/controllers/webui/project_controller.rb

**Comment by ChrisBr** [comment] 2015-10-22 14:33
@adrianschroeter in the ``` def load_project_info``` action? But then it's not a regression from  8b4d426 because it was already without ``false`` before!

**Comment by mdeniz** [comment] 2015-11-09 15:30
@adrianschroeter I don't see the bug here... can you explain it more? or just close it :confused:

**Closed** 2015-12-01 13:44 UTC
Labels: Bug, P2, Regression, webui
