### ISSUE TITLE
html entity quoting in comments with links

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#1529] opened 2016-02-11 07:54 UTC
I'm trying to put a comment on a request that has a link with & in it but can't find a way to get the quoting right. I've tried

$ osc api -X POST /comments/request/358712 -d "\[link]\(http://foo%26bar)"
$ osc api -X POST /comments/request/358712 -d "\[link]\(http://foo&bar)"

Neither result in a working link. What is the correct way to post such a link?

**Comment by lnussel** [comment] 2016-03-07 16:03
any idea for a workaround?

**Comment by lnussel** [comment] 2016-03-08 10:34
here is an example that is even more messed up:
$ osc api /comments/request/367401

The osc call shows a different content than the webui but both are garbage
https://build.opensuse.org/request/show/367401

should be
```
openQA test [passed](https://openqa.opensuse.org/tests/overview?distri=opensuse%26version=42.1%26build=openSUSE%3AMaintenance%3A4794%3A367401)
* [127717](https://openqa.opensuse.org/tests/127717) failed kde in chromium,vlc
* [127720](https://openqa.opensuse.org/tests/127720) failed textmode in yast2_nfs_server
* [127975](https://openqa.opensuse.org/tests/127975) failed gnome in chromium,chrome
```

**Comment by mdeniz** [comment] 2016-03-16 10:57
Looks like a RedCarpet bug with links https://github.com/vmg/redcarpet/issues/446, there is a PR for fixing it at https://github.com/vmg/redcarpet/pull/460, I hope they will merge it not so far away.

**Comment by bgeuken** [comment] 2016-04-12 14:32
redcarpet package got packaged with the upstream patch. This should be fixed with the next deployment

**Closed by bgeuken** 2016-04-12 14:32 UTC
Labels: Bug, frontend, P2

**Comment by coolo** [comment] 2016-04-20 13:00
As the comments in 367401 look still very fishy I had a look and the database object is already busted:

irb(main):007:0> CommentRequest.where(bs_request_id: 367401).first.body.to_s
=> "<\u0000\u0000\u0000!\u0000\u0000\u0000-\u0000\u0000\u0000-\u0000\u0000\u0000 \u0000\u0000\u0000o\u0000\u0000\u0000p\u0000\u0000\u0000e\u0000\u0000\u0000n\u0000\u0000\u0000q\u0000\u0000\u0000a\u0000\u0000\u0000 \u0000\u0000\u0000s\u0000\u0000\u0000t\u0000\u0000\u0000a\u0000\u0000\u0000t\u0000\u0000\u0000e\u0000\u0000\u0000=\u0000\u0000\u0000d\u0000\u0000\u0000o\u0000\u0000\u0000n\u0000\u0000\u0000e\u0000\u0000\u0000 \u0000\u0000\u0000r\u0000\u0000\u0000e\u0000\u0000\u0000s\u0000\u0000\u0000u\u0000\u0000\u0000l\u0000\u0000\u0000t\u0000\u0000\u0000=\u0000\u0000\u0000a\u0000\u0000\u0000c\u0000\u0000\u0000c\u0000\u0000\u0000e\u0000\u0000\u0000p\u0000\u0000\u0000t\u0000\u0000\u0000e\u0000\u0000\u0000d\u0000\u0000\u0000 \u0000\u0000\u0000-\u0000\u0000\u0000-\u0000\u0000\u0000>\u0000\u0000\u0000\n\u0000\u0000\u0000\n\u0000\u0000\u0000o\u0000\u0000\u0000p\u0000\u0000\u0000e\u0000\u0000\u0000n\u0000\u0000\u0000Q\u0000\u0000\u0000A\u0000\u0000\u0000 \u0000\u0000\u0000t\u0000\u0000\u0000e\u0000\u0000\u0000s\u0000\u0000\u0000t\u0000\u0000\u0000 \u0000\u0000\u0000[\u0000\u0000\u0000p\u0000\u0000\u0000a\u0000\u0000\u0000s\u0000\u0000\u0000s\u0000\u0000\u0000e\u0000\u0000\u0000d\u0000\u0000\u0000]\u0000\u0000\u0000(\u0000\u0000\u0000h\u0000\u0000\u0000t\u0000\u0000\u0000t\u0000\u0000\u0000p\u0000\u0000\u0000s\u0000\u0000\u0000:\u0000\u0000\u0000/\u0000\u0000\u0000/\u0000\u0000\u0000o\u0000\u0000\u0000p\u0000\u0000\u0000e\u0000\u0000\u0000n\u0000\u0000\u0000q\u0000\u0000\u0000a\u0000\u0000\u0000.\u0000\u0000\u0000o\u0000\u0000\u0000p\u0000\u0000\u0000e\u0000\u0000\u0000n\u0000\u0000\u0000s\u0000\u0000\u0000u\u0000\u0000\u0000s\u0000\u0000\u0000e\u0000\u0000\u0000.\u0000\u0000\u0000o\u0000\u0000\u0000r\u0000\u0000\u0000g\u0000\u0000\u0000/\u0000\u0000\u0000t\u0000\u0000\u0000e\u0000\u0000\u0000s\u0000\u0000\u0000t\u0000\u0000\u0000s\u0000\u0000\u0000/\u0000\u0000\u0000o\u0000\u0000\u0000v\u0000\u0000\u0000e\u0000\u0000\u0000r\u0000\u0000\u0000v\u0000\u0000\u0000i\u0000\u0000\u0000e\u0000\u0000\u0000w\u0000\u0000\u0000?\u0000\u0000\u0000d\u0000\u0000\u0000i\u0000\u0000\u0000"

**Comment by coolo** [comment] 2016-04-20 13:01
this looks like something python->real_world conversion problem

**Comment by hennevogel** [comment] 2016-04-20 13:04
python?

**Comment by coolo** [comment] 2016-04-20 14:01
lnussel posts these comments with osc

**Comment by marcus-h** [comment] 2016-04-20 17:53
On 2016-04-20 06:01:10 -0700, Stephan Kulow wrote:
> this looks like something python->real_world conversion problem
> 
Hmm osc just sends the "raw" data as application/octet-stream... so
the "real_world" should be able to handle it:)

But, I cannot reproduce it:

marcus@linux:~> curl -u Marcus_H https://api.opensuse.org/comments/request/390850
Enter host password for user 'Marcus_H':
<comments request="392310">
  <comment who="Marcus_H" when="2016-04-20 17:43:02 UTC" id="51036">[link](http://foo&amp;bar)</comment>
  <comment who="Marcus_H" when="2016-04-20 17:44:24 UTC" id="51039">[link](http://foo%26bar)</comment>
</comments>
marcus@linux:~>

Looks ok to me and also works in browser.
