### ISSUE TITLE
Task Counter Went Away

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#10611] opened 2021-01-12 08:12 UTC
The task counter is not visible anymore, just an unimportant button with now highlight of work a packager has to do.

**Comment by dmarcoux** [comment] 2021-01-12 10:11
Are you referring to the task counter which is highlighted in the screenshot below? If not, then which task counter do you mean?

![task-counter](https://user-images.githubusercontent.com/1102934/104300482-d8a6cd00-54c6-11eb-9817-0f429eb25b8e.png)

**Comment by adrianschroeter** [comment] 2021-01-12 10:29
On Dienstag, 12. Januar 2021, 11:11:51 CET Dany Marcoux wrote:
> Are you referring to the task counter which is highlighted in the screenshot below? If not, then which task counter do you mean?
> 
> ![task-counter](https://user-images.githubusercontent.com/1102934/104300482-d8a6cd00-54c6-11eb-9817-0f429eb25b8e.png)

I remember it with some red highlight, but yes, basically the number of jobs which are assigned to me.

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by dmarcoux** [comment] 2021-01-12 10:32
Do you see that counter? I'm trying to understand what is missing exactly.

**Comment by coolo** [comment] 2021-01-12 10:40
the red highlight is from the beta UI - now indicating only notifications

**Comment by adrianschroeter** [comment] 2021-01-12 10:44
I do not see it, it looks like this to me (when visiting the tasks page)
![Screenshot_20210112_114345](https://user-images.githubusercontent.com/1067148/104304268-79978700-54cb-11eb-9a53-c38324060852.png)

**Comment by dmarcoux** [comment] 2021-01-12 11:01
The screenshot I shared in my previous comment is for users which are not in the beta. What you shared is for users in the beta, with the left navigation. In this case, the task counter is replaced by the notifications. The notifications page is accessible from the top right, with the Notifications link between the Watchlist and your avatar. I don't understand why you don't have that in the screenshot you shared... It clearly seems to be a bug.

The changes from the left navigation are going to be rolled out to every user soon. We're preparing a blog post to summarize the changes which were explained in various blog posts in the past months.

Here's what I see in the top right menu while I'm in the beta. You can see the Notifications link as I explained above.
![notifications](https://user-images.githubusercontent.com/1102934/104306067-c9774d80-54cd-11eb-9199-51026e99e647.png)

**Comment by dmarcoux** [comment] 2021-01-12 12:13
@adrianschroeter: I managed to reproduce what you experienced. I can understand how this is confusing you. We decided to move the tasks from the top navigation to the left sidebar. This is part of the changes we introduced in the navigation. Those changes are available only to users in the beta program. However this morning, we rolled it out of beta only for a certain group of users. You were one of them. This is because we are going to roll out those changes to all users soon. Again, sorry for the confusion. We reverted the rollout for now. We're going to announce the changes in the news section of the OBS homepage once the rollout is live.

With this said, the tasks will still be accessible in the left sidebar (which is collapsed in your screenshot). It's the top icon of the left sidebar. You can open the sidebar by clicking on the double arrows at the bottom. As a side note, the notifications page will eventually replace the tasks page, but the rollout of this change is not planned yet.

**Comment by adrianschroeter** [comment] 2021-01-12 12:21
On Dienstag, 12. Januar 2021, 13:13:20 CET Dany Marcoux wrote:
> @adrianschroeter: I managed to reproduce what you experienced. I can understand how this is confusing you. We decided to move the tasks from the top navigation to the left sidebar. This is part of the changes we introduced in the navigation. Those changes are available only to users in the beta program. However this morning, we rolled it out of beta only for a certain group of users. You were one of them. This is because we are going to roll out those changes to all users soon. Again, sorry for the confusion. We reverted the rollout for now. We're going to announce the changes in the news section of the OBS homepage once the rollout is live.
> 
> With this said, the tasks will still be accessible in the left sidebar (which is collapsed in your screenshot). It's the top icon of the left sidebar. You can open the sidebar by clicking on the double arrows at the bottom. As a side note, the notifications page will eventually replace the tasks page, but the rollout of this change is not planned yet.

tasks can not be replaced by notifications because these are assigned jobs (not time bound).

also it needs to be in sync with osc interface.

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by dmarcoux** [comment] 2021-01-12 12:51
It's only a beta feature for now. I was perhaps a bit too eager. We're still checking if notifications could replace the tasks page.

Anyway, as for the current issue, it's fine for you if I close it? I believe the confusion was cleared out.

**Closed** 2021-01-12 15:12 UTC
Labels: Beta, Bug, Frontend
