### ISSUE TITLE
WebUI2: Status messages containing '@' lead to error 500

### ISSUE THREAD

**Issue by lrupp** [openSUSE/open-build-service#8031] opened 2019-08-05 15:28 UTC
# Issue Description
When I - as admin - add a new "status message" (news) via the WebUI2, which contains an '@' sign + some characters, the whole main page renders into an error 500.

Expected Result
============
I would expect that the '@' as well as all other characters in a status message would be correctly quoted inside the application.

How to Reproduce
===============
1. Go to 'the main page of your OBS instance'
2. Click on 'login' -> login as admin user
3. Click on 'Add status message' in the 'News' block, enter any message containing an '@' sign and some other characters behind it (so it looks like an array)
4. 'Save' the message
5. Result: error 500 page is shown

Further Information
===============
* A link can be provided on request.
* Exact server version: tested with 2.10 + 2.11~alpha.20190802T154407.0b611431e4 and the new WebUI, 
* If I delete the problematic message from the database (```delete from status_messages where id=$message_id;```), the page renders correctly again

**Comment by hennevogel** [comment] 2019-08-05 15:39
Can't reproduce on 2.10 or on master. Can you please provide the relevant portion of your logs

`/srv/www/obs/api/log/production.log`

 and the exact text you used?

**Comment by hennevogel** [comment] 2019-08-06 13:14
@lrupp ping

**Comment by lrupp** [comment] 2019-08-06 13:24
I did not find anything useful in the logs, but invite you to jump on one of the machines where it happens. PM follows...

**Comment by hennevogel** [comment] 2019-08-06 15:11
You had a missing setting (`obs_url`) in your configuration. Investigating why this was the case...

**Comment by hennevogel** [comment] 2019-08-06 15:18
How did you deploy those instances?

**Comment by lrupp** [comment] 2019-08-11 10:02
They were IMHO all upgraded from a previous 2.9 "appliance" installation.
* The one running in openStack was deployed via the 2.9 appliance.
* The other one is running bare metal - and was installed on top of a Leap 42.3, as far as I know.
I'm currently the one maintaining it - not the original admin who setup the machines...

**Comment by vpereira** [comment] 2019-08-12 07:32
![Screenshot_2019-08-12_09-31-12](https://user-images.githubusercontent.com/37418/62850710-00976d00-bce4-11e9-950b-ffb2914a4dd9.png)

at least in master it works.

**Comment by hennevogel** [comment] 2019-08-12 11:11
This has nothing to do with master or not. As soon as you don't have `Configuration.obs_url` set it'll crash. The question now is to find out why it was not set.

**Comment by eduardoj** [comment] 2019-12-17 16:01
@hennevogel:

> This has nothing to do with master or not. As soon as you don't have `Configuration.obs_url` set it'll crash. The question now is to find out why it was not set. There is a [database default](https://github.com/openSUSE/open-build-service/blob/master/src/api/db/structure.sql#L438), but apparently this was not used for some reason. Why?

For old appliances, built before 23th of February of 2018, where  7c27abd4988c0f93fd1b1deb3dce1862ff87a9ae was merged, `Configuration.obs_url` could be not set. The migration on that same commit doesn't include a data migration. That is explained in the same commit:

> We don't migrate any existing data because this would have the side effect that
all of the sudden emails would be sent, which we would like to avoid.

Should we close this issue then?

**Comment by lrupp** [comment] 2019-12-17 16:35
Let's close the issue, but make sure that people (like me) can read the important parts somewhere (release-notes/upgrade information).

**Closed** 2019-12-17 19:59 UTC
Labels: Bug :skull:
