### ISSUE TITLE
New UI creates motion sickness

### ISSUE THREAD

**Issue by rsalevsky** [openSUSE/open-build-service#7927] opened 2019-07-17 08:23 UTC
# Issue Description

The new UI which is now the default on the OBS makes me literally sick. I'm not sure why but it's similar to motion sickness. A guess would be that this is related to the different font sizes all over the place and different page setup on each page.

Discussing this with some colleges it seams I'm not the only one.

Expected Result
============
The UI uses a similar font size and the page structure is aligned.

**Comment by mschnitzer** [comment] 2019-07-17 09:55
Speaking about the font size: I agree, it should be a bit decreased I would say. I mean I got used to it now but it could still be a bit smaller.

**Comment by hennevogel** [comment] 2019-07-17 12:20
Sorry you don't feel well @rhabacker 

I agree, we might want to think about how often we use the `.small` class.

**Comment by danidoni** [comment] 2019-07-17 12:25
Hi @rsalevsky, please, can you provide us with a specific page/section do you find troubling, so we can take a look.

**Comment by hennevogel** [comment] 2019-07-17 13:17
For instance the front page. Each red dot is a different font size and weight.

![Screenshot-2019-7-17 openSUSE Build Service](https://user-images.githubusercontent.com/514785/61378567-f54c4f80-a8a5-11e9-8dbe-991041091c3a.png)

**Comment by rsalevsky** [comment] 2019-07-17 14:25
Aligning the font size is a good start and this might already be enough to resolve the issue.

**Comment by dmarcoux** [comment] 2019-07-29 13:14
Perhaps this could help: https://getbootstrap.com/docs/4.3/getting-started/accessibility/#reduced-motion

**Comment by mschnitzer** [comment] 2019-08-09 05:05
It seems the font size of the build results has been increased since the last deployment:

![build-results](https://user-images.githubusercontent.com/8287131/62755384-0dae2500-ba74-11e9-87f8-0bcd789c8acb.png)

**Comment by rsalevsky** [comment] 2019-08-09 09:33
I agree with Manuel. Can we use the same font size as e.g. GitHub?

**Comment by vpereira** [comment] 2019-08-09 09:43
> I agree with Manuel. Can we use the same font size as e.g. GitHub?

We use standard size `16px` as Github does the same.

**Comment by rsalevsky** [comment] 2019-08-09 09:53
GitHub uses 14px for most of the texts e.g. this comment is 14px. On the other hand OBS starts with a font size of 16px. (At least I found nothing smaller.)

**Comment by hennevogel** [comment] 2019-08-09 09:54
It's nice of you that you express your taste in font sizes. But we are more interested in technical arguments. We decided for a slightly larger font size (14px&16px instead of 12px&14px like on here) because most people use the OBS from larger screens according to what we measure.

**Comment by rsalevsky** [comment] 2019-08-09 10:15
I don't really understand from where these technical arguments should come from as design is about look and feel and not if it makes technical sense. A user needs to feel comfortable to use a application so that should be the decision point here.

Here is some data from other UIs I checked:

- GitHub 14px
- SCC 13px
- Google 13px
- Reddit 14px
- RockedChat 14px
- Twitter 14px

I can go on and on here but my feeling is that 14px is the (nonofficial?) default for most websites. Point is that when using all these websites on a daily basis OBS uses the biggest font which causes strange symptoms like motion sickness and the eyes get tired very fast.

PS: I spend a lot of my work time using the various OBS instances and would call my self a OBS power user. I deeply care about the OBS and the work you did with the UI redesign is awesome but there are a few smaller things which would make it even better and I would count this issue as one of them.

**Comment by vpereira** [comment] 2019-08-09 10:18
> GitHub uses 14px for most of the texts e.g. this comment is 14px. On the other hand OBS starts with a font size of 16px. (At least I found nothing smaller.)

GitHub uses a combination of fonts as we do. I don't see a reasoning behind smaller fonts just the opposite. 

We use 16px as default, because it's the most used and normally default from your browser: https://developer.mozilla.org/en-US/docs/Web/CSS/font-size

You can read more about it in many places, one of them:
https://typecast.com/blog/a-more-modern-scale-for-web-typography

We are addressing the different size of fonts in this sprint, so I would prefer to close this issue, and I hope @rsalevsky is feeling better now, and if there is any specific issue to be address, please open an issue about it providing more technical background to the discussion.

**Comment by hennevogel** [comment] 2019-08-09 11:02
> I don't really understand from where these technical arguments should come from as design is about look and feel and not if it makes technical sense.

Sorry, that is not our definition of design, especially not user interface design. There **are** technical arguments for using larger fonts like increased reading speed and more comfortable comprehension (just to name a few). This is objective **science**, @vpereira pointed you to a couple of articles already.

It also doesn't really matter how many pages you will find that use something different (I can equally find many pages that use 16px), I'm sure they all have their reasons and/or restrictions that guided their decision. 

We've told you what guided our decision. 

> Point is that when using all these websites on a daily basis OBS uses the biggest font which causes strange symptoms like motion sickness and the eyes get tired very fast.

We are currently addressing many of the reasons that might cause that you feel like this (too many different sizes, weights, line lengths etc.) and we already have more on the table (responsive typography) but **science** is pretty sure that a 16px font is not the cause for motion sickness when viewing web pages.

If it is for you anyway, I would recommend that you use what your browser provides for you (zoom, overwriting font sizes, custom css/scripts).

> I spend a lot of my work time using the various OBS instances and would call my self a OBS power user. I deeply care about the OBS and the work you did with the UI redesign is awesome but there are a few smaller things which would make it even better and I would count this issue as one of them.

Thank you for the praise and we are happy that you find our work useful. Doesn't change the arguments though, sorry...

**Closed by hennevogel** 2019-08-09 11:02 UTC
Labels: Bootstrap :rocket:, Design
