### ISSUE TITLE
undefined method `name' for "000product:openSUSE-dvd5-dvd-x86_64":String

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/open-build-service#7160] opened 2019-03-12 09:09 UTC
package#live_build_log threw this 0 times
<pre>
undefined method `name&#39; for &quot;000product:openSUSE-dvd5-dvd-x86_64&quot;:String
</pre>
[https://build.opensuse.org/package/live_build_log/openSUSE:Factory:Staging:L/000product:openSUSE-dvd5-dvd-x86_64/images/x86_64](https://build.opensuse.org/package/live_build_log/openSUSE:Factory:Staging:L/000product:openSUSE-dvd5-dvd-x86_64/images/x86_64)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5c8756464c97780014bf22ff)

**Comment by hennevogel** [comment] 2019-03-12 09:28
duplicate of #7133

**Closed by hennevogel** 2019-03-12 09:28 UTC
Labels: Bootstrap :rocket:, Bug :skull:
