### ISSUE TITLE
request gui broken if user.realname contains comma.

### ISSUE THREAD

**Issue by seife** [openSUSE/open-build-service#4168] opened 2017-11-29 08:59 UTC
Issue/Feature description
====================
If a User's real name contains a comma, then at least the request user interface is borken.

Expected result
============
It should not be broken.

How to Reproduce
===============
1. Create a user named "Seyfried, Stefan"
2. let this user create a submitrequest
3. look at the GUI.

Further information
===============
* Exact server version: 2.8.3, with the 2.8.4 fix manually patched

Broken:
![image](https://user-images.githubusercontent.com/2597362/33366497-b411082e-d4eb-11e7-8c14-284c7dbe078b.png)

How it should look:
![image](https://user-images.githubusercontent.com/2597362/33366575-f165deb6-d4eb-11e7-81f4-170b5de0b3cd.png)

**Comment by seife** [comment] 2017-11-29 09:00
--- app/helpers/webui/webui_helper.rb.orig      2017-08-30 10:59:18.000000000 +0000
+++ app/helpers/webui/webui_helper.rb   2017-11-29 08:52:51.953481139 +0000
@@ -37,7 +37,7 @@
     alt ||= user.realname
     alt = user.login if alt.empty?
     image_tag(url_for(controller: :user, action: :user_icon, icon: user.login, size: size),
-              width: size, height: size, alt: alt, class: css_class)
+              width: size, height: size, alt: %(#{alt}).gsub(",", "&#44;"), class: css_class)
   end
 
   def fuzzy_time(time, with_fulltime = true)

This is a quick fix for me, probably needs to be applied elsewhere.

**Comment by seife** [comment] 2017-11-29 09:07
```
MariaDB [api_production]> select * from users where login="my_user";
+----+---------------------+---------------------+---------------------+---------------------+---------+---------------+------------------+----------------------------------+--------------------+---------------+------------------+-----------------------+-----------+----------+
| id | created_at          | updated_at          | last_logged_in_at   | login_failure_count | login   | email         | realname         | password                         | password_hash_type | password_salt | password_crypted | adminnote             | state     | owner_id |
+----+---------------------+---------------------+---------------------+---------------------+---------+---------------+------------------+----------------------------------+--------------------+---------------+------------------+-----------------------+-----------+----------+
| 57 | 2015-09-02 07:27:33 | 2016-10-28 11:07:46 | 2017-11-29 08:54:05 |                   0 | my_user | seife@my.dom  | Seyfried, Stefan | 1234567890abcdef1234567890abcdef | md5                | eoK/PrjXtY    | ABCDEFGHIJKLM    | User created via LDAP | confirmed |     NULL |
+----+---------------------+---------------------+---------------------+---------------------+---------+---------------+------------------+----------------------------------+--------------------+---------------+------------------+-----------------------+-----------+----------+
```
This is my database entry

**Comment by mlschroe** [comment] 2017-12-04 12:58
![](https://github.trello.services/images/mini-trello-icon.png) [request gui broken if user.realname contains comma.](https://trello.com/c/XHQRsgA6/1257-request-gui-broken-if-userrealname-contains-comma)

**Comment by bgeuken** [comment] 2018-03-19 13:50
@seife I can not reproduce this (tried with opera, chrome and firefox). So it seems to be solved already.
Could you check if that still happens for you? If it does, please post us the browser you are using and it's version. Thanks!

**Comment by seife** [comment] 2018-03-20 15:55
I reverted my patch (which I still carried on top of 2.8,4) and indeed it is still working as intended, so something in 2.8.3->2.8.4 seems to have fixed this :-)
Looking at the diff, I cannot imagine what might have caused that fix, so it was maybe related to the browser, Chrome, of course updated many times since then.

Looks like this fixed itself :-)

**Comment by bgeuken** [comment] 2018-03-22 16:55
Glad that it works now:-)

Closing then

**Closed by bgeuken** 2018-03-22 16:55 UTC
Labels: Bug :skull:, Frontend 👻, PR welcome :two_hearts:, junior :baby:
