### ISSUE TITLE
Error when creating a new image based on openSUSE Tumbleweed JeOS

### ISSUE THREAD

**Issue by mvarlese** [openSUSE/open-build-service#9170] opened 2020-03-02 13:23 UTC
Issue/Feature Description
====================
Error is being thrown when trying to create a new image (https://build.opensuse.org/image_templates) selecting the **openSUSE Tumbleweed JeOS** under the section **Templates using openSUSE Tumbleweed**.

Expected Result
============
A new project is created in the home-project folder of current user.

How to Reproduce
===============
1. Go to https://build.opensuse.org/image_templates
2. Select the option **openSUSE Tumbleweed JeOS** (under Templates using openSUSE Tumbleweed)
3. Provide a new name for your appliance in the field "Name your appliance"
4. Click on "Create appliance" button

Further Information
===============
* https://build.opensuse.org/image_templates

**Comment by dmarcoux** [comment] 2020-03-02 13:34
I can reproduce it. The error is `Package has no source revision yet`.

**Comment by hennevogel** [comment] 2020-03-02 16:46
@Vogtinator sounds like something for you

**Comment by Vogtinator** [comment] 2020-03-04 09:27
Works fine here. This was probably caused by the template package being broken due to a conflict, which I noticed and fixed yesterday.

**Comment by dmarcoux** [comment] 2020-03-04 09:41
It's working again as you said @Vogtinator. I'm closing this issue.

**Closed by dmarcoux** 2020-03-04 09:41 UTC
Labels: Bug :skull:
