### ISSUE TITLE
check permissions before send jobs to delay jobs

### ISSUE THREAD

**Issue by vpereira** [openSUSE/open-build-service#5231] opened 2018-06-27 08:20 UTC
We have on errbit quite often permissions issue related with delay jobs. issue #5043 is one example.

To fix it we should check the permissions before to push it to the queue.

i.e https://github.com/openSUSE/open-build-service/blob/4eece6a24d1612a65945c5f75134b7ab3d369cdf/src/api/app/controllers/source_controller.rb#L711 should check if user has permission on target

**Comment by bgeuken** [comment] 2018-06-27 08:29
> To fix it we should check the permissions before to push it to the queue.

Sounds like a good plan.

**Comment by ChrisBr** [comment] 2018-07-02 12:36
Last time this happened was ~2 months ago! @vpereira and I looked into it last Wednesday and did not find the root cause. Let's close it and see if this still happens.

**Closed by ChrisBr** 2018-07-02 12:36 UTC
Labels: Bug :skull:, Frontend 👻
