### ISSUE TITLE
Number of tasks is not updated

### ISSUE THREAD

**Issue by antermin** [openSUSE/open-build-service#13256] opened 2022-10-22 01:33 UTC
# Issue Description
The number of tasks is not updated. It looks like the issue in #9364 has appeared again?

How to Reproduce
===============
1. A few days ago, @adrianschroeter sent automated requests to inactive projects.
2. After receiving the requests, I did not accept or decline them, instead I went ahead and cleaned up (deleted) my inactive projects (after backing up the build scripts).
3. Upon project deletion, the system automatically declined the request.
4. Go to [tasks page](https://build.opensuse.org/my/tasks).

Actual Result
============
Even though the per tab numbers are correct, the number of tasks displayed on the sidebar is still at 5.

![screenshot](https://user-images.githubusercontent.com/103918092/197310287-cc8d4be9-1c37-47f2-8974-5a88f75aae79.png)

Expected Result
============
The number should be updated and becomes 0.

Further Information
===============
* OBS instance: Official instance (build.opensuse.org)

**Comment by hennevogel** [comment] 2022-10-24 09:13
Duplicate of #8852

**Closed by hennevogel** 2022-10-24 09:13 UTC
