### ISSUE TITLE
[production][package#remove_file] <status code="403">
  <summary>package '_product:Uyuni-Proxy-ftp-ftp-x86_64' is read-only if a '_...

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#5652] opened 2018-08-15 08:55 UTC
package#remove_file threw this 0 times
<pre>
&lt;status code=&quot;403&quot;&gt;
  &lt;summary&gt;package &#39;_product:Uyuni-Proxy-ftp-ftp-x86_64&#39; is read-only if a &#39;_product&#39; package exists&lt;/summary&gt;
  &lt;details&gt;403 package &#39;_product:Uyuni-Proxy-ftp-ftp-x86_64&#39; is read-only if a &#39;_product&#39; package exists&lt;/details&gt;
&lt;/status&gt;

</pre>
[https://build.opensuse.org/package/remove_file/home:bgeuken:branches:systemsmanagement:Uyuni:Master/_product:Uyuni-Proxy-ftp-ftp-x86_64/Uyuni-Proxy-ftp-ftp-x86_64.kiwi](https://build.opensuse.org/package/remove_file/home:bgeuken:branches:systemsmanagement:Uyuni:Master/_product:Uyuni-Proxy-ftp-ftp-x86_64/Uyuni-Proxy-ftp-ftp-x86_64.kiwi)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5b73c3bbf141d40006862dcf)

**Comment by bgeuken** [comment] 2018-08-15 10:04
That's a duplicate of #3777. Gone be fixed with #5649

**Closed by bgeuken** 2018-08-15 10:04 UTC
Labels: Bug :skull:, Frontend 👻

**Comment by dmarcoux** [comment] 2018-08-15 10:27
I merged the Errbit issues.
