### ISSUE TITLE
obs-2.6: Edit account displays wrong name and email

### ISSUE THREAD

**Issue by tuminoid** [openSUSE/open-build-service#1178] opened 2015-09-28 08:34 UTC
Edit account pop-up on your profile page displays name + email of anyone who has triggered previous  page load.

Steps to reproduce on 2.6.4 appliance:
1. Sign up a new user (say, test), go to Account page (click username on top menu)
2. Login with Admin on another browser and click "Status monitor".
3. Click "Edit account" in test's window, pop-up displays Admin's name + email.

Cannot be tested in build.opensuse.org as edit account link there goes to Novell's login instead of default action.

**Comment by ChrisBr** [comment] 2017-11-07 11:27
Can't reproduce on current master. As 2.6 is anyway not supported anymore I will close this and suggest to update your OBS.

**Closed by ChrisBr** 2017-11-07 11:27 UTC
Labels: Bug, Frontend, P3
